Repository rsyslog/rsyslog, pull requests merged in 2018-12, with the labels that each got.

#3307 disable file vs directory error on symlinks
  plugins/imfile/imfile.c
Labels: bug

#3331 testbench: instrument flaky imfile-truncate test to find flake cause
  tests/imfile-truncate.sh
Labels: testbench

#3327 testbench: harden omprog tests against CI timing
  tests/omprog-output-capture-mt.sh
  tests/omprog-output-capture-vg.sh
  tests/omprog-output-capture.sh
Labels: DO-NOT-MERGE_work-in-progress

#3335 testbench: do not execute libgcrypt tests if disabled
  tests/Makefile.am
Labels: bug, testbench

#3345 mmkubernetes: add support for sslpartialchain for openssl
  contrib/mmkubernetes/mmkubernetes.c
Labels: enhancement

#3354 testbench: make mysql-actq-mt.sh more robust against slow machines
  tests/mysql-actq-mt.sh
Labels: testbench

#3358 testbench: make some more test more robust against slow CI machines
  tests/diag.sh
  tests/wr_large_async.sh
  tests/wr_large_sync.sh
Labels: testbench

#3356 testbench: improvements and fixes
  tests/Makefile.am
  tests/array_lookup_table-vg.sh
  tests/array_lookup_table.sh
  tests/array_lookup_table_misuse-vg.sh
  tests/lookup_table-vg.sh
  tests/lookup_table.sh
  tests/lookup_table_bad_configs-vg.sh
  tests/lookup_table_bad_configs.sh
  tests/lookup_table_no_hup_reload-vg.sh
  tests/lookup_table_no_hup_reload.sh
  tests/lookup_table_rscript_reload-vg.sh
  tests/lookup_table_rscript_reload.sh
  tests/lookup_table_rscript_reload_without_stub-vg.sh
  tests/lookup_table_rscript_reload_without_stub.sh
  tests/multiple_lookup_tables-vg.sh
  tests/multiple_lookup_tables.sh
  tests/sparse_array_lookup_table-vg.sh
  tests/sparse_array_lookup_table.sh
  tests/unused_lookup_table-vg.sh
Labels: testbench

#3336 new output module for DBMS Clickhouse
  Makefile.am
  configure.ac
  devtools/prepare_clickhouse.sh
  plugins/omclickhouse/Makefile.am
  plugins/omclickhouse/omclickhouse.c
  runtime/rsconf.c
  tests/Makefile.am
  tests/clickhouse-basic-vg.sh
  tests/clickhouse-basic.sh
  tests/clickhouse-bulk-load-vg.sh
  tests/clickhouse-bulk-load.sh
  tests/clickhouse-bulk-vg.sh
  tests/clickhouse-bulk.sh
  tests/clickhouse-errorfile.sh
  tests/clickhouse-limited-batch.sh
  tests/clickhouse-load-vg.sh
  tests/clickhouse-load.sh
  tests/clickhouse-select.sh
  tests/clickhouse-start.sh
  tests/clickhouse-stop.sh
  tests/clickhouse-wrong-insert-syntax.sh
  tests/clickhouse-wrong-quotation-marks.sh
  tests/clickhouse-wrong-template-option.sh
Labels: enhancement

#3363 OpenSSL Driver: bugfix authentication mode anon
  runtime/nsd_ossl.c
  tests/sndrcv_tls_anon_ipv4.sh
  tests/sndrcv_tls_anon_ipv6.sh
  tests/sndrcv_tls_anon_rebind.sh
  tests/sndrcv_tls_ossl_anon_ipv4.sh
  tests/sndrcv_tls_ossl_anon_ipv6.sh
  tests/sndrcv_tls_ossl_anon_rebind.sh
Labels: bug

#3362 testbench improvements, including new global() options
  plugins/imdiag/imdiag.c
  runtime/glbl.c
  runtime/queue.c
  runtime/queue.h
  tests/Makefile.am
  tests/diag.sh
  tests/empty-ruleset.sh
  tests/execonlyonce.sh
  tests/failover-rptd.sh
  tests/imfile-endmsg.regex-with-example.sh
  tests/imfile-endregex-timeout-with-shutdown-polling.sh
  tests/imfile-endregex-timeout-with-shutdown.sh
  tests/imfile-endregex-timeout.sh
  tests/imfile-symlink.sh
  tests/imfile-wildcards-dirs-multi.sh
  tests/imfile-wildcards-dirs-multi2.sh
  tests/imfile-wildcards-dirs-multi3.sh
  tests/imfile-wildcards-dirs-multi4.sh
  tests/imfile-wildcards-dirs-multi5-polling.sh
  tests/imfile-wildcards-dirs-multi5.sh
  tests/imfile-wildcards-dirs.sh
  tests/imfile-wildcards-dirs2.sh
  tests/imfile-wildcards.sh
  tests/mmanon_with_debug.sh
  tests/omprog-output-capture-mt.sh
  tests/omrelp_wrong_authmode.sh
  tests/pmrfc3164-defaultTag.sh
  tests/rscript_int2Hex.sh
  tests/sndrcv.sh
  tests/sndrcv_drvr_noexit.sh
  tests/sndrcv_failover.sh
  tests/testsuites/execonlyonce.data
Labels: core, doc missing, enhancement, testbench

#3367 testbench: fix issues with parallel test run
  devtools/prepare_clickhouse.sh
  tests/Makefile.am
Labels: testbench

#3368 testbench: make some elasticsearch tests more robust f/ slow machines
  tests/diag.sh
  tests/es-basic-bulk.sh
  tests/es-bulk-errfile-empty.sh
Labels: testbench

#3366 TLS Network Drivers: Add setting permitExpiredCerts
  plugins/imtcp/imtcp.c
  runtime/netstrm.c
  runtime/netstrm.h
  runtime/netstrms.c
  runtime/netstrms.h
  runtime/nsd.h
  runtime/nsd_gtls.c
  runtime/nsd_gtls.h
  runtime/nsd_ossl.c
  runtime/nsd_ossl.h
  runtime/nsd_ptcp.c
  runtime/tcpsrv.c
  runtime/tcpsrv.h
  tests/Makefile.am
  tests/sndrcv_tls_anon_ipv6.sh
  tests/sndrcv_tls_certvalid.sh
  tests/sndrcv_tls_certvalid_expired.sh
  tests/sndrcv_tls_ossl_certvalid.sh
  tests/sndrcv_tls_ossl_certvalid_expired.sh
  tests/testsuites/x.509/client-expired-cert.pem
  tests/testsuites/x.509/client-expired-key.pem
  tests/testsuites/x.509/expired-ca-key.pem
  tests/testsuites/x.509/expired-ca.pem
  tests/testsuites/x.509/expired-client-cert.pem
  tests/testsuites/x.509/expired-client-key.pem
  tests/testsuites/x.509/expired-machine-cert.pem
  tests/testsuites/x.509/expired-machine-key.pem
  tests/testsuites/x.509/request.pem
  tools/omfwd.c
Labels: enhancement

#3372 testbench: improve slow machine robstness
  .travis.yml
  plugins/imdiag/imdiag.c
  runtime/cfsysline.c
  tests/diag.sh
  tests/es-basic-bulk.sh
  tests/es-basic-errfile-empty.sh
  tests/es-basic-errfile-popul.sh
  tests/es-basic-es6.0.sh
  tests/es-basic-server.sh
  tests/es-basic-vgthread.sh
  tests/es-basic.sh
  tests/es-bulk-errfile-empty.sh
  tests/es-maxbytes-bulk.sh
  tests/imptcp_conndrop-vg.sh
  tests/omprog-output-capture-mt.sh
  tests/privdropuser.sh
  tests/sndrcv_gzip.sh
  tests/travis/run.sh
Labels: DO-NOT-MERGE_work-in-progress

#3382 mmgrok fix: build error w/ gcc-8 due to questionable code construct
  contrib/mmgrok/mmgrok.c
Labels: bug

#3376 omusrmsg: don't overwrite previous set _PATH_DEV value
  tools/omusrmsg.c
Labels: bug

#3309 testbench: add imrelp valgrind test
  tests/Makefile.am
  tests/imrelp-manyconn-vg.sh
Labels: testbench

#3386 testbench: check for clickhouse start success and complain on fail
  tests/clickhouse-start.sh
Labels: testbench
