Repository rsyslog/rsyslog, pull requests merged in 2018-10, with the labels that each got.

#3089 testbench: improve shutdown timeout diagnostics
  plugins/imdiag/imdiag.c
  tests/diag.sh
Labels: testbench

#3093 exclude KSI components from CodeCov
  .codecov.yml
Labels: QA

#3098 QA: add test for queue.cry.keyprogram parameter
  tests/Makefile.am
  tests/queue-encryption-disk_keyprog.sh
Labels: QA

#3113 bugfix core: potential hang on rsyslog termination
  runtime/queue.c
  runtime/wtp.c
  tests/diag.sh
Labels: bug

#3114 mmutf8fix: add test for no error
  tests/Makefile.am
  tests/mmutf8fix_no_error.sh
Labels: testbench

#3111 gcry crypto driver: small memleak
  runtime/libgcry.c
  runtime/queue.c
Labels: bug

#3110 imrelp: Fixed issue with oldstyle configuration caused by commit:
  plugins/imrelp/imrelp.c
  tests/Makefile.am
  tests/imrelp-basic-oldstyle.sh
Labels: bug

#3118 add test for msleep usage message
  tests/Makefile.am
  tests/msleep_usage_output.sh
Labels: testbench

#3130 CodeCov: adjust config
  .codecov.yml
  runtime/lib_ksils12.c
Labels: QA

#3124 Bugfix: issue 3105, lmsig-ksils12
  runtime/lib_ksils12.c
Labels: bug

#3136 fix invalid assert location and improve error checking
  runtime/queue.c
Labels: QA

#3131 removing result var from context
  contrib/fmhash/fmhash.c
Labels: bug

#3129 rainerscript: fix parentheses in if clause
  grammar/rainerscript.c
Labels: bug

#3140 bugfix core msg: potential deadlock (and rsyslog hang)
  plugins/mmsnmptrapd/mmsnmptrapd.c
  plugins/omjournal/omjournal.c
  runtime/msg.c
  runtime/msg.h
  tests/Makefile.am
  tests/msg-deadlock-headerless-noappname.sh
  tools/smfile.c
  tools/smfwd.c
  tools/smtradfile.c
  tools/smtradfwd.c
Labels: bug

#3146 testbench: do test error reporting only if requested
  .travis.yml
  tests/diag.sh
Labels: testbench

#3150 AIX portability: add missing symbol to export file
  tools/strippedsymbols.exp
Labels: sponsored

#3155 queue bugfix: invalid error message on queue startup
  runtime/queue.c
  runtime/stream.c
  runtime/stream.h
  tests/diag.sh
  tests/diskqueue.sh
Labels: bug

#3159 fix imkafka hang on unavailable kafaka server
  .travis.yml
  plugins/imkafka/imkafka.c
  tests/Makefile.am
  tests/diag.sh
  tests/imkafka-hang-on-no-kafka.sh
Labels: bug, sponsored

#3167 fix potential misadressing in encryption subsystem
  runtime/libgcry.c
  tests/Makefile.am
  tests/queue-encryption-disk_keyfile-vg.sh
Labels: bug

#3171 testbench: try to stabilize es-bulk-retry test
  tests/es-bulk-retry.sh
Labels: testbench

#3175 testbench: make test more reliable
  tests/sndrcv_udp_nonstdpt.sh
Labels: testbench

#3182 fix issues when imkafka is backgrounded
  plugins/imkafka/imkafka.c
  tests/Makefile.am
  tests/diag.sh
  tests/imkafka-backgrounded.sh
  tests/imkafka-config-err-param.sh
  tests/imkafka-config-err-ruleset.sh
  tests/imkafka-hang-other-action-on-no-kafka.sh
  tools/rsyslogd.c
Labels: bug, sponsored

#3189 core/debug: data written to random fd 2 under some debug settings
  tools/rsyslogd.c
Labels: bug

#3199 Enable query results for commented-out code
  .lgtm.yml
Labels: QA

#3203 testbench: make imfile check more reliable by better wait predicate
  tests/imfile-truncate-multiple.sh
Labels: testbench

#3194 Issue 3191, lmsig_ksils12: improve module debug logging
  runtime/lib_ksils12.c
  runtime/lib_ksils12.h
  runtime/lmsig_ksi-ls12.c
Labels: enhancement

#3186 bugfix tcpflood testing tool: improper parameter validation
  tests/Makefile.am
  tests/diag.sh
  tests/tcpflood.c
  tests/tcpflood_wrong_option_output.sh
Labels: bug, testbench

#3208 bugfix tcpflood: invalid type in calloc (openssl mode)
  tests/tcpflood.c
Labels: testbench

#3205 testbench: keep kafka/zookeeper running between tests
  tests/CI/buildbot_cleanup.sh
  tests/Makefile.am
  tests/diag.sh
  tests/imkafka-backgrounded.sh
  tests/imkafka-config-err-param.sh
  tests/imkafka-config-err-ruleset.sh
  tests/imkafka-vg.sh
  tests/imkafka.sh
  tests/imkafka_multi_single.sh
  tests/omkafka-vg.sh
  tests/omkafka.sh
  tests/sndrcv_kafka.sh
Labels: testbench

#3209 CodeCov: permit slight drop of coverage but still go "OK"
  .codecov.yml
Labels: QA

#3211 testbench: stabilize imptcp_large test
  tests/diag.sh
  tests/imptcp_large.sh
Labels: testbench

#3192 Fix journald excessive reloading behavior
  plugins/imjournal/imjournal.c
Labels: bug

#3215 testbench: ensure failure stats error reporting always happens
  tests/diag.sh
Labels: QA, testbench

#3214 testbench: re-enable journal test
  tests/imjournal-basic-vg.sh
Labels: testbench

#3213 testbench: add self-test for kafka subsystem
  tests/Makefile.am
  tests/kafka-selftest.sh
Labels: testbench

#3221 testbench: grep fails with option error in some tests
  tests/diag.sh
Labels: bug, testbench

#3231 testbench: support auto-start/-stop of mysqld
  tests/Makefile.am
  tests/mysqld-start.sh
  tests/mysqld-stop.sh
Labels: DO-NOT-MERGE_work-in-progress, QA, testbench
