Repository rsyslog/rsyslog, pull requests merged in 2018-11, with the labels that each got.

#3233 make distcheck did not honor "--enable-mysql-tests"
  Makefile.am
Labels: QA, bug, testbench

#3235 improve bash coding style and fix a small bug in testbench
  tests/daqueue-invld-qi.sh
  tests/daqueue-persist-drvr.sh
  tests/diag.sh
  tests/queue-persist-drvr.sh
  tests/queue-persist.sh
Labels: testbench

#3239 testbench: add test for backticks parameters
  grammar/lexer.l
  tests/Makefile.am
  tests/diag.sh
  tests/rscript_backticks_empty_envvar-vg.sh
Labels: QA, testbench

#3237 config: fix segfault in backticks "echo" expansion of undefined variables
  grammar/lexer.l
Labels: bug

#3244 testbench: add debug support for hunting small memleak on shutdown
  runtime/wtp.c
Labels: testbench

#3241 testbench: modernize "wait-file-lines" functionality
  tests/diag.sh
  tests/imfile-logrotate.sh
  tests/imfile-rename.sh
  tests/imfile-truncate-multiple.sh
  tests/imkafka.sh
  tests/imkafka_multi_single.sh
  tests/imptcp_large.sh
  tests/omkafka.sh
  tests/sndrcv_udp_nonstdpt.sh
Labels: testbench

#3245 testbench: try to make journal tests more reliable
  tests/diag.sh
  tests/imjournal-basic.sh
Labels: testbench

#3250 testbench: improve framework, harden rscript http test
  tests/diag.sh
  tests/rscript_http_request-vg.sh
  tests/rscript_http_request.sh
Labels: QA, testbench

#3243 testbench: add test for mmjsonparse w/ unparsable data
  tests/Makefile.am
  tests/mmjsonparse_extra_data-vg.sh
Labels: testbench

#3253 testbench: ensure error reporting params are urlencoded
  tests/Makefile.am
  tests/diag.sh
  tests/urlencode.py
Labels: testbench

#3255 testbench: detected kafka failure during test run and SKIP if so
  tests/diag.sh
  tests/sndrcv_kafka_multi_topics.sh
Labels: testbench

#3252 testbench: let user know if test failure reporting is not enabled
  tests/diag.sh
Labels: testbench

#3260 testbench: make rsyslog shutdown predicate more reliable for kafka tests
  tests/diag.sh
  tests/imjournal-basic-vg.sh
  tests/imkafka-backgrounded.sh
  tests/imkafka-config-err-ruleset.sh
  tests/imkafka-vg.sh
  tests/imkafka.sh
  tests/omkafka-vg.sh
Labels: testbench

#3263 testbench: debug instrument sndrcv_tls_ossl_anon_rebind
  tests/sndrcv_tls_ossl_anon_rebind.sh
Labels: testbench

#3262 testbench: modernize elasticsearch tests
  tests/diag.sh
  tests/es-basic-abort.sh
  tests/es-basic-bulk-vg.sh
  tests/es-basic-bulk.sh
  tests/es-basic-errfile-empty.sh
  tests/es-basic-es6.0.sh
  tests/es-basic-ha-vg.sh
  tests/es-basic-ha.sh
  tests/es-basic-server.sh
  tests/es-basic-vg.sh
  tests/es-basic-vgthread.sh
  tests/es-basic.sh
  tests/es-bulk-errfile-empty.sh
  tests/es-bulk-retry.sh
  tests/es-maxbytes-bulk.sh
  tests/es-writeoperation.sh
  tests/es_response_get_msgnum.py
Labels: testbench

#3261 testbench: make libdbi test more reliable
  tests/diag.sh
  tests/libdbi-asyn.sh
Labels: testbench

#3264 improvements to elasticsearch tests and framework
  tests/diag.sh
  tests/es-basic-abort.sh
  tests/es-basic-bulk-vg.sh
  tests/es-basic-bulk.sh
  tests/es-basic-errfile-empty.sh
  tests/es-basic-errfile-popul.sh
  tests/es-basic-es6.0.sh
  tests/es-basic-ha-vg.sh
  tests/es-basic-ha.sh
  tests/es-basic-server.sh
  tests/es-basic-vgthread.sh
  tests/es-basic.sh
  tests/es-bulk-errfile-empty.sh
  tests/es-bulk-errfile-popul-def-format.sh
  tests/es-bulk-errfile-popul-def-interleaved.sh
  tests/es-bulk-errfile-popul-erronly-interleaved.sh
  tests/es-bulk-errfile-popul-erronly.sh
  tests/es-bulk-errfile-popul.sh
  tests/es-bulk-retry.sh
  tests/es-maxbytes-bulk.sh
  tests/es-writeoperation.sh
  tests/mmkubernetes-basic-vg.sh
  tests/mmkubernetes-basic.sh
Labels: testbench

#3269 fix testbench error reporting under distcheck
  tests/diag.sh
Labels: bug, testbench

#3270 try to solve shutdown memory leak
  runtime/wtp.c
  tests/known_issues.supp
  tests/mmpstrucdata-invalid-vg.sh
Labels: testbench

#3274 bugfix imfile: rsyslog re-sends data for files larger 2GiB
  runtime/stream.c
Labels: bug

#3275 testbench improvements, kafka test reliability improvement
  tests/diag.sh
Labels: testbench

#3276 buildbot: gather script shall not pickup $RSYSLOG_DYNNAME*.log files
  tests/CI/gather_all_logs.sh
Labels: QA

#3271 imfile/stream: fixes and improvements
  runtime/stream.c
  tests/Makefile.am
  tests/diag.sh
  tests/imfile-basic-2GB-file.sh
  tests/imfile-truncate-2GB-file.sh
  tests/inputfilegen.c
Labels: bug, enhancement, testbench

#3283 testbench: fix core file handling when multiple core files exist
  tests/diag.sh
Labels: testbench

#3286 testbench: harden test against slow machines
  tests/action-tx-errfile.sh
Labels: testbench

#3289 testbench: some cleanup and improvements
  tests/diag.sh
Labels: testbench

#3296 travis: more error message to diagnose travis issue
  tests/travis/install.sh
Labels: DO-NOT-MERGE_work-in-progress

#3295 bugfix omrelp: emit error messages on suspension
  plugins/omrelp/omrelp.c
  tests/Makefile.am
  tests/omrelp_errmsg_no_connect.sh
  tests/sndrcv_relp.sh
Labels: bug

#3313 testbench: do not cancel uxsockrcvr on test init
  tests/diag.sh
  tests/omprog-restart-terminated-outfile.sh
  tests/omprog-restart-terminated.sh
  tests/uxsock_simple.sh
Labels: testbench

#3317 bugfix debug output: date property options output wrongly
  template.c
Labels: bug

#3321 add some info on rsyslog on AIX
  README.AIX
  README.AIX.IBM
Labels: doc

#3304 bugfix omhttp: does not compile on all platforms
  contrib/omhttp/omhttp.c
Labels: bug
