Repository rsyslog/rsyslog, pull requests merged in 2018-05, with the labels that each got.

#2598 omkafka: added implstats counters for librdkafka returned statistics …
  plugins/omkafka/omkafka.c
Labels: enhancement

#2670 add test for issue https://github.com/rsyslog/rsyslog/issues/2480
  tests/Makefile.am
  tests/wtpShutdownAll-assertionFailure.sh
Labels: QA

#2669 nsdsel_ptcp: replace select() by poll()
  runtime/nsdsel_ptcp.c
  runtime/nsdsel_ptcp.h
  runtime/rsyslog.h
  tests/hostname-getaddrinfo-fail.sh
Labels: bug, enhancement

#2687 testbench: temporarily disable test failing on FreeBSD
  tests/hostname-getaddrinfo-fail.sh
Labels: testbench

#2499 Enable ratelimit on imklog
  plugins/imklog/imklog.c
  plugins/imklog/imklog.h
Labels: doc missing, enhancement

#2686 omfwd: fix memory leak in never-released code
  tools/omfwd.c
Labels: bug

#2688 mmgrok: fix potential segfault
  contrib/mmgrok/mmgrok.c
Labels: bug

#2680 imuxsock: replace select() call by poll()
  plugins/imuxsock/imuxsock.c
Labels: DO-NOT-MERGE_work-in-progress

#2690 imudp: use rsyslog message rate-limiter instead of home-grown one
  plugins/imudp/imudp.c
Labels: bug, enhancement

#1395 testbench: new test case for testing full DA disk queue
  runtime/debug.c
  runtime/debug.h
  runtime/queue.c
  tests/Makefile.am
  tests/diag.sh
  tests/diskqueue-full.sh
Labels: testbench

#2696 testbench: fix race in threadingmqaq test
  runtime/debug.c
  runtime/queue.c
  tests/diag.sh
  tests/testsuites/threadingmqaq.conf
  tests/threadingmqaq.sh
Labels: bug, testbench

#2703 pass liblogging cflags when building fmhttp and imfile plugins
  plugins/fmhttp/Makefile.am
  plugins/imfile/Makefile.am
Labels: bug

#2716 core: fix undefined behaviour (unsigned computation may lead to value…
  runtime/msg.c
Labels: bug

#2718 imfile/core bugfix: potential misadressing in string copy routine
  runtime/stringbuf.c
Labels: bug

#2714 imrelp bugfix: error message "librelp too old" is always emitted
  plugins/imrelp/imrelp.c
Labels: bug

#2708 add statistics counter to imjournal
  plugins/imjournal/imjournal.c
Labels: enhancement

#2704 config: permit 4-digit file creation modes
  grammar/rainerscript.c
Labels: enhancement

#2726 mmkubernetes test python must encode response
  tests/mmkubernetes-basic.sh
  tests/mmkubernetes_test_server.py
Labels: bug, testbench
