Repository rsyslog/rsyslog, pull requests merged in 2018-04, with the labels that each got.

#2565 testbench bugfix: journal tests did not actually check for success
  tests/imjournal-basic-vg.sh
  tests/imjournal-basic.sh
Labels: bug, testbench

#2367 Fix tcp keepalive settings assignment
  plugins/imtcp/imtcp.c
Labels: in-depth review required

#2606 merge #2490 as experimental module
  Makefile.am
  configure.ac
  contrib/omfile-hardened/Makefile.am
  contrib/omfile-hardened/omfile-hardened.c
  runtime/rsyslog.h
Labels: enhancement

#2604 fix issues with atomic operations
  configure.ac
  plugins/omkafka/omkafka.c
  runtime/atomic.h
  runtime/dynstats.c
  tools/omfile.c
Labels: bug

#2609 omfile bugfix: segfault when empty filename is given
  tests/Makefile.am
  tests/omfile-null-filename.sh
  tests/omfile-whitespace-filename.sh
  tools/omfile.c
Labels: bug

#2209 build system: enable --unlimited-select by default
  configure.ac
Labels: DO-NOT-MERGE_work-in-progress

#2614 fmhttps bugfix: missing configure check for libcurl
  configure.ac
Labels: bug

#2561 imptcp: increase UNIX socket backlog for performance under heavy load
  plugins/imptcp/imptcp.c
Labels: enhancement

#2630 testbench: switch external testbench URL
  tests/rscript_http_request-vg.sh
  tests/rscript_http_request.sh
Labels: QA

#2631 lmsig_ksils12: fixing issues 2517 and 2621
  runtime/lib_ksi_queue.c
  runtime/lib_ksils12.c
Labels: bug

#2622 QA: re-enable some compiler warnigs AX_COMPILER_FLAGS disables
  configure.ac
  grammar/rainerscript.c
  plugins/imfile/imfile.c
  plugins/imklog/bsd.c
  plugins/omprog/omprog.c
  runtime/debug.c
  tools/omfwd.c
Labels: QA, enhancement

#2635 Several fixes for mmkubernetes
  configure.ac
  contrib/mmkubernetes/mmkubernetes.c
  contrib/mmkubernetes/sample.conf
  tests/Makefile.am
  tests/mmkubernetes-basic-vg.sh
  tests/mmkubernetes-basic.out.json
  tests/mmkubernetes-basic.sh
  tests/mmkubernetes_test_server.py
Labels: bug

#2465 adding hash64 and hash64mod functions support in rainerscript
  Makefile.am
  configure.ac
  contrib/fmhash/Makefile.am
  contrib/fmhash/fmhash.c
  grammar/rainerscript.c
  grammar/rainerscript.h
  runtime/Makefile.am
  tests/Makefile.am
  tests/rscript_hash32-vg.sh
  tests/rscript_hash32.sh
  tests/rscript_hash64-vg.sh
  tests/rscript_hash64.sh
  tests/testsuites/rscript_hash32.conf
  tests/testsuites/rscript_hash64.conf
  tools/Makefile.am
Labels: doc missing, enhancement

#2653 fmhash: fix invalid table end entry
  contrib/fmhash/fmhash.c
Labels: bug

#2668 core bugfix: segfault on queue shutdown
  runtime/queue.c
Labels: bug

#2666 core: config optimizer did not handle call_indirect
  grammar/rainerscript.c
Labels: bug

#2651 omfwd: add support for bind-to-address for UDP
  tools/omfwd.c
Labels: enhancement

#2667 imfile bugfix: statefiles contain invalid JSON
  plugins/imfile/imfile.c
Labels: bug

#2674 bugfix: rsyslog aborts on startup when specific config errors are made
  tools/rsyslogd.c
Labels: bug
