Repository rsyslog/rsyslog, pull requests merged in 2018-02, with the labels that each got.

#2450 BUGFIX, Issue 2446. Fix directory creation code in lmsig_ksils12 plugin
  runtime/lib_ksils12.c
Labels: bug

#2472 cleanup/config: remove redundant lexer rule
  grammar/lexer.l
Labels: cleanup

#2459 core/template: add format jsonf to constant template entries
  template.c
  tests/Makefile.am
  tests/template-const-jsonf.sh
Labels: enhancement
