Repository rsyslog/rsyslog, pull requests merged in 2018-06, with the labels that each got.

#2715 moved FD limit setting to correct section of unit file
  rsyslog.service.in
Labels: DO-NOT-MERGE_work-in-progress

#2748 omrelp: check for correct authmode
  plugins/omrelp/omrelp.c
Labels: bug

#2756 imrelp: segfault on startup when cert without priv key is configured
  plugins/imrelp/imrelp.c
  tests/diag.sh
  tests/imrelp-missing-privkey.sh
Labels: bug

#2755 core: misadressing when writing disk queue files
  runtime/ruleset.c
  tests/imfile-basic-vgthread.sh
  tests/imfile-basic-vgthread.supp
Labels: bug

#2727 imfile bugfix: double-free on module shutdown
  plugins/imfile/imfile.c
Labels: bug

#2763 gnutls driver: support intermediate certificates
  runtime/nsd_gtls.c
  runtime/nsd_gtls.h
Labels: enhancement

#2733 omelasticsearch: write op types; bulk rejection retries
  plugins/omelasticsearch/omelasticsearch.c
  tests/Makefile.am
  tests/README
  tests/diag.sh
  tests/es-bulk-retry.sh
  tests/es-config-errs.supp
  tests/es-writeoperation.sh
Labels: enhancement

#2724 imfile bugfix: if freshStartTail is set some initial file lines missing
  plugins/imfile/imfile.c
  tests/Makefile.am
  tests/imfile-freshStartTail1.sh
  tests/imfile-freshStartTail2.sh
  tests/imfile-freshStartTail3.sh
Labels: bug

#2779 travis: add checks for openssl drivers
  runtime/nsd_ossl.c
  tests/diag.sh
  tests/sndrcv_tls_ossl_anon_ipv6.sh
  tests/travis/run-cron.sh
  tests/travis/run.sh
Labels: QA, testbench

#2405 some testbench improvements
  .travis.yml
  configure.ac
  devtools/devcontainer.sh
  tests/Makefile.am
  tests/diag.sh
  tests/es-basic-abort.sh
  tests/es-basic-bulk-vg.sh
  tests/es-basic-bulk.sh
  tests/es-basic-errfile-empty.sh
  tests/es-basic-errfile-popul.sh
  tests/es-basic-es6.0.sh
  tests/es-basic-ha-vg.sh
  tests/es-basic-ha.sh
  tests/es-basic-server.sh
  tests/es-basic-vg.sh
  tests/es-basic-vgthread.sh
  tests/es-basic.sh
  tests/es-bulk-errfile-empty.sh
  tests/es-bulk-errfile-popul-def-format.sh
  tests/es-bulk-errfile-popul-def-interleaved.sh
  tests/es-bulk-errfile-popul-erronly-interleaved.sh
  tests/es-bulk-errfile-popul-erronly.sh
  tests/es-bulk-errfile-popul.sh
  tests/es-bulk-retry.sh
  tests/es-maxbytes-bulk.sh
  tests/testsuites/es-basic-bulk.conf
  tests/testsuites/es-basic-errfile-empty.conf
  tests/testsuites/es-basic-ha.conf
  tests/testsuites/es-basic-server.conf
  tests/testsuites/es-basic.conf
  tests/testsuites/es-bulk-errfile-empty.conf
  tests/testsuites/es-bulk-errfile-popul-def-format.conf
  tests/testsuites/es-bulk-errfile-popul-def-interleaved.conf
  tests/testsuites/es-bulk-errfile-popul-erronly-interleaved.conf
  tests/testsuites/es-bulk-errfile-popul-erronly.conf
  tests/testsuites/es-bulk-errfile-popul.conf
  tests/testsuites/es-maxbytes-bulk.conf
  tests/travis/run.sh
Labels: testbench

#2729 imptcp: experimental multiline support via regex
  plugins/imptcp/imptcp.c
  tests/Makefile.am
  tests/diag.sh
  tests/imptcp_framing_regex-oversize.sh
  tests/imptcp_framing_regex.sh
  tests/testsuites/imptcp_framing_regex-oversize.testdata
  tests/testsuites/imptcp_framing_regex.testdata
Labels: enhancement

#2487 [ommongodb] Adding possibility to ignore some insertion error code
  plugins/ommongodb/README
  plugins/ommongodb/ommongodb.c
Labels: enhancement

#2792 imrelp: fix regression from very recent commit
  plugins/imrelp/imrelp.c
Labels: bug

#2775 imjournal: journal visibility through additional impstats counters
  plugins/imjournal/imjournal.c
Labels: enhancement

#2794 Fixed race in asyncWriter
  runtime/stream.c
Labels: bug

#2796 fix some build issues on CentOS 6
  plugins/omelasticsearch/omelasticsearch.c
  tests/Makefile.am
Labels: DO-NOT-MERGE_work-in-progress, bug

#2797 core: provide a somewhat better default action name
  ChangeLog
  action.c
  tests/stats-json.sh
Labels: enhancement

#2795 omrabbitmq: one pthread mutex per connection
  contrib/omrabbitmq/omrabbitmq.c
Labels: enhancement

#2805 check for null fp before fclose
  contrib/mmkubernetes/mmkubernetes.c
Labels: bug

#2803 add global directive "abortOnUncleanConfig"
  runtime/glbl.c
  tests/abort-uncleancfg-badcfg-check.sh
  tests/testsuites/abort-uncleancfg-badcfg.conf
  tools/rsyslogd.c
Labels: doc missing, enhancement

#2807 travis: remove "merge master" test
  .travis.yml
Labels: QA
