Repository rsyslog/rsyslog, pull requests merged in 2018-07, with the labels that each got.

#2808 more explicit error msg with message modification mod on queue
  action.c
Labels: enhancement

#2809 build system: do not disable testbench tests via --disable-liblogging…
  configure.ac
  runtime/glbl.c
  runtime/glbl.h
  runtime/rsyslog.c
  tools/rsyslogd.c
Labels: testbench

#2812 default rules use container_name_and_id; include rulebase files in dist
  contrib/mmkubernetes/Makefile.am
  contrib/mmkubernetes/mmkubernetes.c
Labels: bug

#2810 impstats: Updated python based statslog analyzer sample scripts.
  plugins/impstats/statslog-analyzer.py
  plugins/impstats/statslog-graph.py
  plugins/impstats/statslog-splitter.py
  plugins/impstats/statslog_regex.py
Labels: bug

#2820 config: enhance backticks "echo" capability
  grammar/lexer.l
Labels: enhancement

#2819 Remove ?authMechanism=PLAIN to let the mongo library chooses the defa…
  plugins/ommongodb/ommongodb.c
Labels: bug

#2823 fix a typo in the rsyslog.conf man page
  tools/rsyslog.conf.5
  tools/rsyslogd.8
Labels: bug, doc

#2619 replace select() by poll()
  plugins/imudp/imudp.c
  runtime/nsd_ptcp.c
  tests/hostname-getaddrinfo-fail.sh
Labels: bug, enhancement

#2822 impstats: emit warning if log.syslog="off" and ruleset name given
  plugins/impstats/impstats.c
Labels: bug, enhancement

#2829 mmgrok bugfix: cosmetic build issue
  contrib/mmgrok/mmgrok.c
Labels: bug

#2832 imkmsg bugfix: build warnings on some platforms
  contrib/imkmsg/imkmsg.c
  contrib/imkmsg/imkmsg.h
  contrib/imkmsg/kmsg.c
  tests/hostname-getaddrinfo-fail.sh
Labels: bug

#2831 Travis: reduce distcheck tests
  .travis.yml
  tests/Makefile.am
Labels: QA

#2784 support mysql unix domain socket
  plugins/ommysql/ommysql.c
Labels: enhancement

#2840 testbench: fix tests that look awfully wrong
  tests/arrayqueue.sh
  tests/linkedlistqueue.sh
Labels: bug, testbench

#2843 fix a couple of issues with and detected by gcc 8
  grammar/rainerscript.c
  plugins/ommysql/ommysql.c
  runtime/lookup.c
  runtime/nsdsel_ossl.c
  tools/omusrmsg.c
Labels: bug

#2847 testbench: increase ElasticSearch start timeout
  tests/diag.sh
Labels: DO-NOT-MERGE_work-in-progress

#2846 more gcc-8 induced corrections
  contrib/mmkubernetes/mmkubernetes.c
  grammar/rainerscript.c
  plugins/imptcp/imptcp.c
  plugins/ompgsql/ompgsql.c
  plugins/omsnmp/omsnmp.c
  runtime/debug.c
  runtime/queue.c
  runtime/ruleset.c
Labels: bug

#2854 testbench: do not unnecessarily persist test data to disk
  tests/chkseq.c
  tests/diag.sh
Labels: enhancement, testbench

#2858 testbench: kubernetes test cannot recover from failure
  tests/CI/kill_all_kubernetes_test_server.sh
  tests/diag.sh
  tests/glbl-oversizeMsg-truncate-imfile.sh
  tests/imrelp-manyconn.sh
  tests/mmkubernetes-basic-vg.sh
  tests/mmkubernetes-basic.sh
Labels: bug, testbench

#2863 add --enable-default-tests ./configure option
  .travis.yml
  configure.ac
  tests/Makefile.am
Labels: testbench

#2878 fix build issues on armhf systems
  runtime/datetime.c
  runtime/lib_ksils12.c
Labels: bug

#2881 mmkubernetes: stops working with non-kubernetes container names
  contrib/mmkubernetes/mmkubernetes.c
  tests/mmkubernetes-basic-vg.sh
  tests/mmkubernetes-basic.out.json
  tests/mmkubernetes-basic.sh
Labels: bug

#2856 core: do not abort startup on problems setting scheduling policy
  runtime/rsyslog.c
Labels: bug

#2891 testbench: make port for imdiag dynamic
  tests/diag.sh
  tests/omtcl.sh
  tests/uxsock_simple.sh
Labels: testbench

#2889 Travis: temporarily disable kafka tests
  tests/travis/install.sh
Labels: QA

#2543 Fetching cursor on readJournal() and simplified pollJournal()
  plugins/imjournal/imjournal.c
  tests/Makefile.am
  tests/imjournal-basic-vg.sh
  tests/imjournal-basic.sh
  tests/imjournal-statefile.sh
  tests/journal_print.c
Labels: enhancement
