Repository rsyslog/rsyslog, pull requests merged in 2018-03, with the labels that each got.

#2501 CI: fix check that tarball is built correctly
  tests/Makefile.am
  tests/travis/run.sh
Labels: QA, bug

#2511 testbench: do not run some DB tests twice in split test runs
  tests/Makefile.am
Labels: QA, enhancement

#2548 Add lgtm.yml configuration for analysis on lgtm.com
  .lgtm.yml
Labels: QA, enhancement

#2550 fixing issues found by lgtm.com static analyzer
  outchannel.h
  plugins/impstats/pygal-tooltips.js
  plugins/impstats/svg.jquery.js
  runtime/glbl.c
  runtime/hashtable.h
  tools/pmrfc3164.c
Labels: QA

#2546 fix memory leak in imfile readmode 0
  runtime/stream.c
  tests/Makefile.am
  tests/imfile-readmode0-vg.sh
Labels: bug

#2545 omfile: Fix wrong order of arguments for errmsg
  tools/omfile.c
Labels: bug

#2551 QA: make lgtm.com analyze more modules
  .lgtm.yml
Labels: QA

#2553 QA: enable even more modules in lgtm.com static analyzer
  .lgtm.yml
  action.c
  plugins/mmaudit/mmaudit.c
  plugins/ompgsql/ompgsql.c
  tools/logctl.c
Labels: QA

#2527 tests/glbl-umask.sh: Improve test stability
  tests/glbl-umask.sh
Labels: QA

#1992 omprog: added tests for transactions with feedback
  tests/Makefile.am
  tests/omprog-transactions-failed-commits.sh
  tests/omprog-transactions-failed-messages.sh
  tests/omprog-transactions.sh
  tests/testsuites/omprog-transactions-bin.sh
  tests/testsuites/omprog-transactions-failed-commits.conf
  tests/testsuites/omprog-transactions-failed-messages.conf
  tests/testsuites/omprog-transactions.conf
Labels: QA

#2563 nitfix: test included invalid parameter
  tests/testsuites/sndrcv_relp_sender.conf
Labels: testbench

#2559 testbench: disable some racy omprog tests
  tests/Makefile.am
Labels: testbench

#2519 omelasticsearch - add support for CA cert, client cert auth
  plugins/omelasticsearch/omelasticsearch.c
Labels: enhancement

#2555 stream/bugfix: memory leak on stream open if filename as already gene…
  runtime/stream.c
Labels: bug

#2562 rscript: make function modules loadable
  Makefile.am
  configure.ac
  grammar/rainerscript.c
  grammar/rainerscript.h
  plugins/fmhttp/Makefile.am
  plugins/fmhttp/fmhttp.c
  runtime/module-template.h
  runtime/modules.c
  runtime/modules.h
  tests/Makefile.am
  tests/rscript_http_request-vg.sh
  tests/rscript_http_request.sh
  tests/rscript_num2ipv4.sh
  tests/rscript_re_match.sh
Labels: enhancement

#2570 Make configuration setting SystemLogRateLimitBurst unsigned int
  runtime/ratelimit.c
  runtime/ratelimit.h
Labels: bug

#2556 testbench: improve cleanup
  tests/diag.sh
Labels: bug, testbench

#2590 CI: enable mmkubernates in lgtm.com static analyzer
  .lgtm.yml
Labels: QA

#2466 Add the mmkubernetes plugin
  Makefile.am
  configure.ac
  contrib/mmkubernetes/Makefile.am
  contrib/mmkubernetes/k8s_container_name.rulebase
  contrib/mmkubernetes/k8s_filename.rulebase
  contrib/mmkubernetes/mmkubernetes.c
  contrib/mmkubernetes/sample.conf
Labels: enhancement

#2589 imfile: refactor state file format
  plugins/imfile/imfile.c
  runtime/stream.c
  runtime/stream.h
  tests/imfile-endregex-timeout-with-shutdown-polling.sh
  tests/imfile-readmode2-with-persists-data-during-stop.sh
Labels: DO-NOT-MERGE_work-in-progress, enhancement
