Repository rsyslog/rsyslog, pull requests merged in 2018-09, with the labels that each got.

#2969 imdiag: port 0 is now accepted
  plugins/imgssapi/imgssapi.c
  plugins/imtcp/imtcp.c
  runtime/tcpsrv.c
Labels: testbench

#2968 testbench: short test id and make more reliable
  tests/Makefile.am
  tests/diag.sh
  tests/es-writeoperation.sh
  tests/omprog-restart-terminated-outfile.sh
  tests/sndrcv_gzip.sh
  tests/test_id.c
Labels: testbench

#2978 testbench: streamline plumbing
  tests/CI/buildbot_cleanup.sh
  tests/diag.sh
  tests/mmkubernetes-basic-vg.sh
  tests/mmkubernetes-basic.sh
  tests/mmpstrucdata-case.sh
  tests/mmpstrucdata-invalid-vg.sh
  tests/omprog-close-unresponsive-vg.sh
  tests/omprog-close-unresponsive.sh
  tests/omprog-defaults-vg.sh
  tests/omprog-defaults.sh
  tests/omprog-feedback-vg.sh
  tests/omprog-feedback.sh
  tests/omprog-restart-terminated-outfile.sh
  tests/omprog-restart-terminated-vg.sh
  tests/omprog-restart-terminated.sh
  tests/omprog-transactions-failed-commits.sh
  tests/omprog-transactions-failed-messages.sh
  tests/omprog-transactions-vg.sh
  tests/omprog-transactions.sh
  tests/rulesetmultiqueue-v6.sh
  tests/rulesetmultiqueue.sh
  tests/sndrcv.sh
  tests/sndrcv_drvr_noexit.sh
  tests/sndrcv_failover.sh
  tests/sndrcv_gzip.sh
  tests/sndrcv_kafka-vg-rcvr.sh
  tests/sndrcv_kafka-vg-sender.sh
  tests/sndrcv_kafka.sh
  tests/sndrcv_kafka_fail.sh
  tests/sndrcv_kafka_failresume.sh
  tests/sndrcv_kafka_multi.sh
  tests/sndrcv_kafka_multi_topics.sh
  tests/sndrcv_omudpspoof.sh
  tests/sndrcv_omudpspoof_nonstdpt.sh
  tests/sndrcv_relp.sh
  tests/sndrcv_relp_dflt_pt.sh
  tests/sndrcv_relp_rebind.sh
  tests/sndrcv_relp_tls.sh
  tests/sndrcv_relp_tls_prio.sh
  tests/sndrcv_tls_anon_hostname.sh
  tests/sndrcv_tls_anon_ipv4.sh
  tests/sndrcv_tls_anon_ipv6.sh
  tests/sndrcv_tls_anon_rebind.sh
  tests/sndrcv_tls_ossl_anon_ipv4.sh
  tests/sndrcv_tls_ossl_anon_ipv6.sh
  tests/sndrcv_tls_ossl_anon_rebind.sh
  tests/sndrcv_tls_priorityString.sh
  tests/sndrcv_udp.sh
  tests/sndrcv_udp_nonstdpt.sh
  tests/sndrcv_udp_nonstdpt_v6.sh
  tests/tcp-msgreduc-vg.sh
  tests/udp-msgreduc-orgmsg-vg.sh
  tests/udp-msgreduc-vg.sh
Labels: testbench

#2990 omfwd: remove invalid error message
  tools/omfwd.c
Labels: bug

#3003 core: improve error message on module load fail
  runtime/modules.c
Labels: enhancement

#2993 add contrib module omhttp
  .lgtm.yml
  Makefile.am
  configure.ac
  contrib/omhttp/Makefile.am
  contrib/omhttp/omhttp.c
  tests/CI/clang-analyzer-build.sh
  tests/travis/run-cron.sh
  tests/travis/run.sh
Labels: enhancement

#3004 testbench: modernize, next part
  tests/array_lookup_table-vg.sh
  tests/array_lookup_table.sh
  tests/array_lookup_table_misuse-vg.sh
  tests/diag.sh
  tests/dynstats_nometric.sh
  tests/dynstats_overflow-vg.sh
  tests/dynstats_overflow.sh
  tests/impstats-hup.sh
  tests/json_nonarray_looping.sh
  tests/json_object_looping-vg.sh
  tests/json_object_looping.sh
  tests/json_object_suicide_in_loop-vg.sh
  tests/lookup_table-vg.sh
  tests/lookup_table.sh
  tests/lookup_table_bad_configs-vg.sh
  tests/lookup_table_bad_configs.sh
  tests/lookup_table_no_hup_reload-vg.sh
  tests/lookup_table_no_hup_reload.sh
  tests/lookup_table_rscript_reload-vg.sh
  tests/lookup_table_rscript_reload.sh
  tests/lookup_table_rscript_reload_without_stub-vg.sh
  tests/lookup_table_rscript_reload_without_stub.sh
  tests/mmnormalize_regex_defaulted.sh
  tests/mmnormalize_regex_disabled.sh
  tests/multiple_lookup_tables-vg.sh
  tests/multiple_lookup_tables.sh
  tests/omprog-output-capture-mt.sh
  tests/sparse_array_lookup_table-vg.sh
  tests/sparse_array_lookup_table.sh
  tests/stop_when_array_has_element.sh
Labels: testbench

#3005 testbench: some more modernization
  tests/diag.sh
  tests/dynstats_nometric.sh
  tests/dynstats_overflow-vg.sh
  tests/dynstats_overflow.sh
  tests/dynstats_reset-vg.sh
  tests/dynstats_reset.sh
  tests/rcvr_fail_restore.sh
  tests/sndrcv_tls_anon_rebind.sh
  tests/stats-json-es.sh
  tests/stats-json-vg.sh
  tests/stats-json.sh
Labels: testbench

#3008 testbench: fix imdiag memory leak reported by valgrind
  plugins/imdiag/imdiag.c
Labels: bug, testbench

#2999 imfile: experimental input throtteling feature
  plugins/imfile/imfile.c
  runtime/ratelimit.c
Labels: doc missing, enhancement

#3010 imdiag: add capability to specify input flow control mode
  plugins/imdiag/imdiag.c
Labels: testbench

#3007 testbench: improve plumbing, especially in kafka tests
  plugins/imdiag/imdiag.c
  tests/CI/buildbot_cleanup.sh
  tests/Makefile.am
  tests/diag.sh
  tests/imkafka.sh
  tests/omkafka.sh
  tests/sndrcv_kafka-vg-rcvr.sh
  tests/sndrcv_kafka-vg-sender.sh
  tests/sndrcv_kafka.sh
  tests/sndrcv_kafka_fail.sh
  tests/sndrcv_kafka_failresume.sh
  tests/sndrcv_kafka_multi.sh
  tests/sndrcv_kafka_multi_topics.sh
Labels: testbench

#3016 testbench: make imrelp tests faster and avoid imtcp
  tests/sndrcv_relp.sh
  tests/sndrcv_relp_dflt_pt.sh
  tests/sndrcv_relp_rebind.sh
  tests/sndrcv_relp_tls.sh
  tests/sndrcv_relp_tls_prio.sh
Labels: testbench

#3014 imfile: support for endmsg.regex
  plugins/imfile/imfile.c
  plugins/imptcp/imptcp.c
  runtime/stream.c
  runtime/stream.h
  tests/Makefile.am
  tests/imfile-endmsg.regex-vg.sh
  tests/imfile-endmsg.regex-with-example-vg.sh
  tests/imfile-endmsg.regex-with-example.sh
  tests/imfile-endmsg.regex.crio.rulebase
  tests/imfile-endmsg.regex.json.rulebase
  tests/imfile-endmsg.regex.sh
Labels: enhancement

#3020 pmnormalize: fix memory leak
  plugins/pmnormalize/pmnormalize.c
  runtime/msg.c
  tests/pmnormalize-rule-vg.sh
Labels: bug

#2959 omrelp: permit new authmode certvalid
  plugins/omrelp/omrelp.c
  tests/Makefile.am
  tests/omrelp_wrong_authmode.sh
  tests/sndrcv_relp_tls_certvalid.sh
Labels: enhancement

#3026 imrelp: do not fail build if librelp does not have relpSrvSetLstnAddr
  configure.ac
  plugins/imrelp/imrelp.c
Labels: bug

#3040 CI: add valgrind suppressions for -coverage gcc option
  .codecov.yml
  tests/CI/gcov.supp
  tests/Makefile.am
  tests/diag.sh
Labels: DO-NOT-MERGE_work-in-progress

#3038 testbench: fix incompatibility of one omprog test with Python3
  tests/omprog-output-capture-mt.sh
  tests/testsuites/omprog-output-capture-mt-bin.py
Labels: bug, testbench

#3043 CI: customize CodeCov settings
  .codecov.yml
Labels: QA

#3049 bugfix testbench: kafka test startup was racy
  tests/diag.sh
Labels: bug, testbench

#3056 testbench: add very basic ommail test
  tests/Makefile.am
  tests/ommail_errmsg_no_params.sh
Labels: QA, testbench

#3059 testbench: restart kafka if brokers do not come up
  tests/diag.sh
Labels: bug, testbench

#3054 CI: clean hanging kafka and zookeeper instances on test startup
  tests/CI/buildbot_cleanup.sh
Labels: testbench

#3062 testbench: skip sndrcv_kafka.sh as it fails quite frequently
  tests/sndrcv_kafka.sh
Labels: testbench

#3061 testbench: add simple omsnmp test
  tests/Makefile.am
  tests/omsnmp_errmsg_no_params.sh
Labels: testbench

#3051 bugfix imfile: file change was not reliably detected
  plugins/imfile/imfile.c
  runtime/stream.c
  runtime/stream.h
  tests/Makefile.am
  tests/imfile-logrotate.sh
  tests/imfile-wildcards-dirs-multi5-polling.sh
Labels: bug

#3029 testbench: fixed imfile parallel issues
  tests/imfile-endmsg.regex-with-example.sh
  tests/imfile-endregex-timeout-with-shutdown-polling.sh
  tests/imfile-endregex-timeout-with-shutdown.sh
  tests/imfile-endregex-timeout.sh
  tests/imfile-freshStartTail2.sh
  tests/imfile-rename.sh
  tests/imfile-symlink.sh
  tests/imfile-wildcards-dirs-multi.sh
  tests/imfile-wildcards-dirs-multi2.sh
  tests/imfile-wildcards-dirs-multi3.sh
  tests/imfile-wildcards-dirs-multi4.sh
  tests/imfile-wildcards-dirs-multi5-polling.sh
  tests/imfile-wildcards-dirs-multi5.sh
  tests/imfile-wildcards-dirs.sh
  tests/imfile-wildcards-dirs2.sh
  tests/imfile-wildcards.sh
Labels: testbench

#3077 testbench: re-enable test sndrcv_relp_dflt_pt.sh
  tests/Makefile.am
  tests/sndrcv_relp_dflt_pt.sh
Labels: bug, testbench

#3078 testbench: remove useless "cat" command (cosmetic)
  tests/diag.sh
Labels: testbench

#3079 testbench: work around shellcheck false positive
  tests/imrelp-missing-privkey.sh
  tests/omprog-close-unresponsive-noterm.sh
  tests/omprog-close-unresponsive.sh
  tests/omprog-defaults.sh
  tests/omprog-feedback-timeout.sh
  tests/omprog-feedback.sh
  tests/omprog-output-capture.sh
  tests/omprog-restart-terminated-outfile.sh
  tests/omprog-restart-terminated.sh
  tests/pmnormalize-rule-vg.sh
  tests/pmrfc3164-json.sh
  tests/prop-programname.sh
  tests/rscript_bare_var_root-empty.sh
  tests/rscript_bare_var_root.sh
  tests/rscript_format_time.sh
  tests/rscript_is_time.sh
  tests/rscript_parse_json-vg.sh
  tests/rscript_parse_json.sh
  tests/rscript_parse_time.sh
  tests/rscript_script_error.sh
  tests/template-const-jsonf.sh
  tests/template-pure-json.sh
Labels: testbench

#3081 bugfix queue subsystem: DA queue did ignore encryption settings
  runtime/Makefile.am
  runtime/libgcry.c
  runtime/queue.c
  tests/Makefile.am
  tests/daqueue-dirty-shutdown.sh
  tests/daqueue-invld-qi.sh
  tests/daqueue-persist-drvr.sh
  tests/diag.sh
  tests/imudp_thread_hang.sh
  tests/internal-errmsg-memleak-vg.sh
  tests/nested-call-shutdown.sh
  tests/queue-encryption-da.sh
  tests/queue-encryption-disk.sh
  tests/queue-persist-drvr.sh
  tests/sndrcv_relp_tls_certvalid.sh
Labels: bug

#3090 testbench: detect kafka broker failure and skip test if so
  tests/diag.sh
  tests/omkafka-vg.sh
  tests/omkafka.sh
  tests/sndrcv_kafka.sh
Labels: testbench
