Repository rsyslog/rsyslog, pull requests merged in 2018-08, with the labels that each got.

#2894 testbench: prototype of sndrcv test in modern style
  tests/diag.sh
  tests/sndrcv_relp.sh
Labels: testbench

#2904 testbench: cleanup hanging uxsocksrvr instances
  tests/diag.sh
Labels: testbench

#2749 Symlink support for imfile
  plugins/imfile/imfile.c
  tests/Makefile.am
  tests/diag.sh
  tests/imfile-symlink-multi.sh
  tests/imfile-symlink.sh
Labels: do_first, enhancement

#2903 testbench: suppress known issue
  tests/Makefile.am
  tests/diag.sh
  tests/known_issues.supp
Labels: testbench

#2911 testbench: uxsockrcvr cleanup did try to kill "grep" process
  tests/diag.sh
Labels: testbench

#2926 testbench: support dynamic pidfile naming
  tests/Makefile.am
  tests/daqueue-dirty-shutdown.sh
  tests/diag.sh
  tests/hostname-with-slash-dflt-invld.sh
  tests/imjournal-basic-vg.sh
  tests/imjournal-basic.sh
  tests/mmkubernetes-basic-vg.sh
  tests/mmkubernetes-basic.sh
  tests/testsuites/gethostname.conf
Labels: testbench

#2944 testbench: force sequence of execution for some tests
  tests/CI/get_all_check_logs.sh
  tests/Makefile.am
  tests/diag.sh
  tests/diskqueue-full.sh
  tests/imjournal-basic-vg.sh
  tests/imjournal-basic.sh
Labels: DO-NOT-MERGE_work-in-progress, testbench

#2774 [WIP] "fromhost" property's case is lowered when using UDP
  plugins/imtcp/imtcp.c
  plugins/imudp/imudp.c
  runtime/msg.c
  runtime/msg.h
  runtime/net.c
  runtime/tcpsrv.c
  runtime/tcpsrv.h
Labels: do_first

#2947 testbench: some more dynamic names
  tests/CI/gather_all_logs.sh
  tests/Makefile.am
  tests/daqueue-invld-qi.sh
  tests/daqueue-persist-drvr.sh
  tests/diag.sh
  tests/dynstats-json-vg.sh
  tests/dynstats-json.sh
  tests/dynstats-vg.sh
  tests/dynstats.sh
  tests/dynstats_ctr_reset.sh
  tests/dynstats_nometric.sh
  tests/dynstats_overflow-vg.sh
  tests/dynstats_overflow.sh
  tests/dynstats_prevent_premature_eviction-vg.sh
  tests/dynstats_prevent_premature_eviction.sh
  tests/dynstats_reset-vg.sh
  tests/dynstats_reset.sh
  tests/dynstats_reset_without_pstats_reset.sh
  tests/elasticsearch-error-format-check.py
  tests/es-basic-errfile-empty.sh
  tests/es-basic-errfile-popul.sh
  tests/es-basic-ha.sh
  tests/es-bulk-errfile-empty.sh
  tests/es-bulk-errfile-popul-def-format.sh
  tests/es-bulk-errfile-popul-def-interleaved.sh
  tests/es-bulk-errfile-popul-erronly-interleaved.sh
  tests/es-bulk-errfile-popul-erronly.sh
  tests/es-bulk-errfile-popul.sh
  tests/imptcp_uds_unlink.sh
  tests/invalid_nested_include.sh
  tests/no-dynstats-json.sh
  tests/no-dynstats.sh
  tests/omfile_both_files_set.sh
  tests/pipe_noreader.sh
  tests/queue-persist-drvr.sh
  tests/random.sh
  tests/sndrcv_failover.sh
  tests/stats-cee-vg.sh
  tests/stats-cee.sh
  tests/stats-json-es.sh
  tests/stats-json-vg.sh
  tests/stats-json.sh
Labels: DO-NOT-MERGE_work-in-progress, testbench

#2950 ommongodb: fix build issue if mongo-c-driver is not compiled with TLS
  configure.ac
  plugins/ommongodb/ommongodb.c
Labels: bug

#2952 Fixed parent name when processing symlinks
  plugins/imfile/imfile.c
Labels: bug

#2953 omfile: implement file-id, used in state file
  plugins/imfile/Makefile.am
  plugins/imfile/imfile.c
  plugins/imfile/siphash.c
  tests/Makefile.am
  tests/diag.sh
  tests/imfile-growing-file-id.sh
  tests/imfile-persist-state-1.sh
Labels: bug, enhancement

#2956 uxsockrcvr: add timeout
  tests/uxsock_simple.sh
  tests/uxsockrcvr.c
Labels: testbench

#2966 testbench: disable journal tests by default
  configure.ac
  tests/Makefile.am
Labels: testbench

#2964 imptcp: add parameter ListenPortFileName
  plugins/imdiag/imdiag.c
  plugins/imptcp/imptcp.c
  runtime/netstrm.c
  runtime/netstrm.h
  runtime/nsd.h
  runtime/nsd_gtls.c
  runtime/nsd_ossl.c
  runtime/nsd_ptcp.c
  runtime/strmsrv.c
  runtime/tcpsrv.c
  runtime/tcpsrv.h
Labels: doc missing

#2972 tcpflood: fix segfauls on some platforms (e.g. AIX)
  action.c
  grammar/lexer.l
  plugins/imuxsock/imuxsock.c
  plugins/mmexternal/mmexternal.c
  runtime/modules.c
  runtime/net.c
  runtime/nsd_ptcp.c
  runtime/rsyslog.h
  runtime/srutils.c
  runtime/tcpclt.c
  tests/tcpflood.c
  tools/omfile.c
  tools/omfwd.c
  tools/ompipe.c
  tools/omusrmsg.c
  tools/rsyslogd.c
Labels: bug, testbench
