Repository rsyslog/rsyslog, pull requests merged in 2019-10, with the labels that each got.

#3883 pmcisconames bugfix: potential misadressing
  contrib/pmcisconames/pmcisconames.c
Labels: bug

#3851 openssl tls: Changed logerror to logmsg for SSL_CONF_cmd warning
  runtime/nsd_ossl.c
Labels: bug

#3879 print also ratelimiter parameters
  runtime/ratelimit.c
Labels: enhancement

#3740 core bugfix: incorrect error message on duplicate module load
  contrib/imczmq/imczmq.c
  runtime/rsconf.c
  runtime/wti.c
Labels: bug

#3893 testbench: improve dynstats tests and make them more protable
  tests/diag.sh
  tests/dynstats-json-vg.sh
  tests/dynstats-vg.sh
  tests/dynstats.sh
  tests/dynstats_ctr_reset.sh
  tests/dynstats_nometric.sh
  tests/dynstats_overflow-vg.sh
  tests/dynstats_overflow.sh
  tests/dynstats_prevent_premature_eviction-vg.sh
  tests/dynstats_prevent_premature_eviction.sh
  tests/dynstats_reset-vg.sh
  tests/dynstats_reset.sh
  tests/dynstats_reset_without_pstats_reset.sh
Labels: testbench

#3888 testbench: add test for mmpstrucdata with RFC5424 escape sequences
  tests/Makefile.am
  tests/mmpstrucdata-escaping.sh
Labels: testbench

#3890 core bugfix: potential abort on very long action name
  runtime/queue.c
  runtime/wtp.c
Labels: bug

#3902 imjournal: fix regression
  plugins/imjournal/imjournal.c
Labels: bug

#3900 core queue bugfix: handle multi-queue-file delete correctly
  runtime/stream.c
  tests/diag.sh
Labels: bug

#3903 mmkubernetes bugfix: improper use of calloc()
  contrib/mmkubernetes/mmkubernetes.c
Labels: bug

#3905 build system bugfix: incorrect default in ./configure help text
  configure.ac
Labels: bug

#3908 imuxsock bugfix: improper use of calloc()
  plugins/imuxsock/imuxsock.c
Labels: bug

#3916 TLS driver bugfix: improper use of calloc()
  runtime/nsd_gtls.c
  runtime/nsd_ossl.c
Labels: bug

#3907 imfile bugfix: improper use of calloc()
  plugins/imfile/imfile.c
Labels: bug

#3928 testbench bugfix: make python scripts use print python 2/3 compatible
  tests/elasticsearch-error-format-check.py
  tests/es_response_get_msgnum.py
  tests/mmexternal-SegFault-vg.sh
  tests/testsuites/mmexternal-SegFault-mm-python.py
  tests/urlencode.py
Labels: bug, testbench

#3922 omfile bugfix: file handle leak
  runtime/stream.c
Labels: DO-NOT-MERGE_work-in-progress, bug

#3926 enhancement: multithread disk queue
  runtime/queue.c
  runtime/stream.c
  runtime/wti.c
  tests/Makefile.am
  tests/cee_diskqueue.sh
  tests/diag.sh
  tests/diskq-rfc5424.sh
  tests/diskqueue-multithread-es.sh
Labels: enhancement

#3937 mmdblookup: fix missing space in city name
  plugins/mmdblookup/mmdblookup.c
  tests/Makefile.am
  tests/mmdb-space.sh
  tests/with_space.mmdb
Labels: bug
