Repository rsyslog/rsyslog, pull requests merged in 2019-03, with the labels that each got.

#3510 testbench bugfix: long-running tests had too low runtime allowance
  tests/imfile-basic-2GB-file.sh
  tests/imfile-truncate-2GB-file.sh
Labels: bug, testbench

#3508 testbench improvements
  tests/da-mainmsg-q.sh
  tests/mmexternal-SegFault-vg.sh
Labels: testbench

#3430 tls support: Added support for certless communcation
  plugins/imdiag/imdiag.c
  runtime/glbl.c
  runtime/nsd_gtls.c
  runtime/nsd_gtls.h
  runtime/nsd_ossl.c
  runtime/nsdsel_ptcp.c
  tests/Makefile.am
  tests/diag.sh
  tests/imtcp-tls-ossl-basic-vg.sh
  tests/imtcp-tls-ossl-basic.sh
  tests/known_issues.supp
  tests/manytcp-too-few-tls-vg.sh
  tests/sndrcv_tls_certless_ossl_client.sh
  tests/sndrcv_tls_certless_serveronly.sh
  tests/sndrcv_tls_gtls_serveranon_gtls_clientanon.sh
  tests/sndrcv_tls_gtls_serveranon_ossl_clientanon.sh
  tests/sndrcv_tls_gtls_servercert_gtls_clientanon.sh
  tests/sndrcv_tls_gtls_servercert_gtls_clientanon_legacy.sh
  tests/sndrcv_tls_gtls_servercert_ossl_clientanon.sh
  tests/sndrcv_tls_ossl_serveranon_gtls_clientanon.sh
  tests/sndrcv_tls_ossl_serveranon_ossl_clientanon.sh
  tests/sndrcv_tls_ossl_servercert_gtls_clientanon.sh
  tests/sndrcv_tls_ossl_servercert_ossl_clientanon.sh
Labels: enhancement

#3519 Enlarged msg offset types for bigger structured messages
  runtime/msg.c
  runtime/msg.h
Labels: bug

#3339 Issue 3338: lmsig_ksils12: Add high avalability mode supported by libksi 3.18
  configure.ac
  runtime/lib_ksils12.c
  runtime/lib_ksils12.h
  runtime/lmsig_ksi-ls12.c
Labels: enhancement

#3522 Allow header values to have spaces
  contrib/omhttp/omhttp.c
Labels: bug

#3477 Add improg contribution
  .lgtm.yml
  ChangeLog
  Makefile.am
  configure.ac
  contrib/improg/Makefile.am
  contrib/improg/improg.c
  tests/Makefile.am
  tests/improg_errmsg_no_params-vg.sh
  tests/improg_errmsg_no_params.sh
  tests/travis/run-osx.sh
Labels: enhancement

#3527 improg: add new module
  .lgtm.yml
  ChangeLog
  Makefile.am
  configure.ac
  contrib/improg/Makefile.am
  contrib/improg/improg.c
  tests/Makefile.am
  tests/improg_errmsg_no_params-vg.sh
  tests/improg_errmsg_no_params.sh
  tests/travis/run-osx.sh
Labels: enhancement

#3521 imfile bugfix: file reader could get stuck
  plugins/imfile/imfile.c
  tests/Makefile.am
  tests/diag.sh
  tests/imfile-logrotate-multiple.sh
  tests/imfile-persist-state-1.sh
  tests/imfile-statefile-no-file_id-TO-file_id.sh
  tests/imfile-statefile-no-file_id.sh
Labels: bug

#3350 omkafka: add support for dynamic keys
  plugins/omkafka/omkafka.c
  tests/Makefile.am
  tests/omkafkadynakey.sh
Labels: enhancement

#3532 update contributor doc to current state; add some more background info
  CONTRIBUTING.md
Labels: doc

#3531 CI: improve error messages in PR validation
  tests/CI/PR_validation.sh
  tests/CI/check_commit_text.py
Labels: QA

#3540 Added missing reset of journal cursor
  plugins/imjournal/imjournal.c
Labels: bug

#3551 tcpflood bugfix: make soft connection limit work again
  tests/imrelp-manyconn.sh
  tests/manytcp.sh
  tests/tcpflood.c
Labels: bug

#3555 fix commented out-code
  runtime/msg.c
  runtime/obj-types.h
  runtime/obj.c
  runtime/stringbuf.c
Labels: cleanup

#3559 omkafka bugfix: build failure due to inconsistent type
  plugins/omkafka/omkafka.c
Labels: bug

#3560 omamqp: fix build errors
  contrib/omamqp1/omamqp1.c
Labels: bug

#3565 openssl: Added better error handling in osslRecordRecv
  runtime/nsd_ossl.c
  tests/tcpflood.c
Labels: bug

#3566 Fetching journal cursor only for valid journal
  plugins/imjournal/imjournal.c
Labels: bug

#3482 contrib_imtuxedoulog
  .lgtm.yml
  ChangeLog
  Makefile.am
  configure.ac
  contrib/imtuxedoulog/Makefile.am
  contrib/imtuxedoulog/README.md
  contrib/imtuxedoulog/imtuxedoulog.c
  tests/Makefile.am
  tests/imtuxedoulog_data.sh
  tests/imtuxedoulog_errmsg_no_params-vg.sh
  tests/imtuxedoulog_errmsg_no_params.sh
Labels: enhancement

#3575 testbench: bump kafka version
  tests/diag.sh
Labels: testbench
