Repository rsyslog/rsyslog, pull requests merged in 2019-04, with the labels that each got.

#3526 contrib_mmtaghostname
  .lgtm.yml
  Makefile.am
  configure.ac
  contrib/mmtaghostname/Makefile.am
  contrib/mmtaghostname/mmtaghostname.c
  tests/Makefile.am
  tests/mmtaghostname_server.sh
  tests/mmtaghostname_tag.sh
Labels: enhancement

#3514 contrib imbatchreport
  .lgtm.yml
  Makefile.am
  configure.ac
  contrib/imbatchreport/Makefile.am
  contrib/imbatchreport/imbatchreport.c
  tests/Makefile.am
  tests/imbatchreport_delete_structdata.sh
  tests/imbatchreport_delete_success.sh
  tests/imbatchreport_delete_toolarge.sh
  tests/imbatchreport_errmsg_delete_params.sh
  tests/imbatchreport_errmsg_glob_dir_fake.sh
  tests/imbatchreport_errmsg_glob_dir_not_dir.sh
  tests/imbatchreport_errmsg_glob_not_regular.sh
  tests/imbatchreport_errmsg_no_params-vg.sh
  tests/imbatchreport_errmsg_no_params.sh
  tests/imbatchreport_errmsg_not_supported1.sh
  tests/imbatchreport_errmsg_not_supported2.sh
  tests/imbatchreport_errmsg_not_supported3.sh
  tests/imbatchreport_errmsg_regex.match.reject.sh
  tests/imbatchreport_errmsg_regex.match.rename.sh
  tests/imbatchreport_errmsg_regex.nomatch.sh
  tests/imbatchreport_errmsg_rename_params.sh
  tests/imbatchreport_rename_success.sh
  tests/imbatchreport_rename_toolarge.sh
  tests/travis/run-osx.sh
Labels: enhancement

#3558 add support for skipverifyhost
  contrib/mmkubernetes/mmkubernetes.c
  contrib/omhttp/omhttp.c
  plugins/omclickhouse/omclickhouse.c
  plugins/omelasticsearch/omelasticsearch.c
Labels: enhancement

#3557 omelasticsearch: add support for rebindinterval
  plugins/omelasticsearch/omelasticsearch.c
  tests/es-basic.sh
Labels: enhancement

#3579 CI: lgtm.com was not enabled for mmtaghostname due to a typo
  .lgtm.yml
Labels: QA, bug

#3581 lgtm: reduce change of merge conflic on .lgtm.yml
  .lgtm.yml
Labels: cleanup

#3330 imdocker: input plugin enabling pulling container logs from docker
  .lgtm.yml
  .travis.yml
  Makefile.am
  configure.ac
  contrib/imdocker/Makefile.am
  contrib/imdocker/imdocker.c
  contrib/imdocker/imdocker_unit_tests.h
  tests/Makefile.am
  tests/imdocker-basic-vg.sh
  tests/imdocker-basic.sh
  tests/imdocker-long-logline-vg.sh
  tests/imdocker-long-logline.sh
  tests/imdocker-multi-line-vg.sh
  tests/imdocker-multi-line.sh
  tests/imdocker-new-logs-from-start-vg.sh
  tests/imdocker-new-logs-from-start.sh
  tests/imdocker-unittests.sh
  tests/travis/install.sh
  tests/travis/run-cron.sh
  tests/travis/run-osx.sh
  tests/travis/run.sh
Labels: enhancement

#3539 mmkubernetes - support for metadata cache expiration
  contrib/mmkubernetes/mmkubernetes.c
  runtime/atomic.h
  runtime/statsobj.h
  tests/Makefile.am
  tests/mmkubernetes-basic-vg.sh
  tests/mmkubernetes-basic.sh
  tests/mmkubernetes-cache-expire-vg.sh
  tests/mmkubernetes-cache-expire.out.expected
  tests/mmkubernetes-cache-expire.sh
Labels: enhancement

#3583 testbench: bump zookeeper version
  tests/diag.sh
Labels: testbench

#3589 Revert "WiP: rsyslog doesn't respond to TLS close_notify "
  runtime/nsd_ptcp.c
Labels: bug

#3590 openssl nsd driver: Enhanced error output for SSL_ERROR_SYSCALL
  runtime/nsd_ossl.c
  runtime/nsd_ptcp.c
Labels: enhancement

#3597 testbench: disable imdocker-unittests because it does not work
  tests/Makefile.am
  tests/imdocker-unittests.sh
Labels: bug, testbench

#3593 testbench: better instrumenation for imfile-symlink test
  tests/imfile-symlink.sh
Labels: testbench

#3479 Contrib_pmdb2diag
  .lgtm.yml
  ChangeLog
  Makefile.am
  configure.ac
  contrib/pmdb2diag/Makefile.am
  contrib/pmdb2diag/pmdb2diag.c
  tests/Makefile.am
  tests/pmdb2diag_parse.sh
Labels: enhancement

#3595 testbench: better info if core file is found during test
  tests/diag.sh
Labels: testbench

#3577 omelasticsearch - retry: set rawmsg to data from original request
  plugins/omelasticsearch/omelasticsearch.c
  tests/es-bulk-retry.sh
Labels: DO-NOT-MERGE_work-in-progress

#3598 testbench: Add missing omhttp tests to EXTRA_DIST
  tests/Makefile.am
Labels: bug, testbench

#3604 build system bugfix: omhttp was ignored during "make distcheck"
  Makefile.am
Labels: QA, bug

#3591 improg : tests and memory leak patch
  Makefile.am
  contrib/improg/improg.c
  tests/Makefile.am
  tests/improg-simul.sh
  tests/improg_prog_confirm.sh
  tests/improg_prog_confirm_killonclose.sh
  tests/improg_prog_killonclose.sh
  tests/improg_prog_simple-vg.sh
  tests/improg_prog_simple.sh
Labels: bug

#3603 remove redundant compiled imdocker-unit-tests
  configure.ac
  contrib/imdocker/imdocker.c
  contrib/imdocker/imdocker_unit_tests.h
  tests/Makefile.am
  tests/imdocker-unittests.sh
  tests/travis/run-osx.sh
Labels: QA, bug, testbench

#3476 Featuring omrabbitmq
  .lgtm.yml
  ChangeLog
  Makefile.am
  contrib/omrabbitmq/Makefile.am
  contrib/omrabbitmq/README.md
  contrib/omrabbitmq/omrabbitmq.c
  runtime/rsyslog.h
  tests/Makefile.am
  tests/miniamqpsrvr.c
  tests/omrabbitmq_data_1server-vg.sh
  tests/omrabbitmq_data_1server.sh
  tests/omrabbitmq_data_2servers.sh
  tests/omrabbitmq_error_server0.sh
  tests/omrabbitmq_error_server1.sh
  tests/omrabbitmq_error_server2.sh
  tests/omrabbitmq_error_server3.sh
  tests/omrabbitmq_json.sh
  tests/omrabbitmq_no_params.sh
  tests/omrabbitmq_params_invalid0.sh
  tests/omrabbitmq_params_invalid1.sh
  tests/omrabbitmq_params_invalid2.sh
  tests/omrabbitmq_params_invalid3.sh
  tests/omrabbitmq_params_missing0.sh
  tests/omrabbitmq_params_missing1.sh
  tests/omrabbitmq_params_missing2.sh
  tests/omrabbitmq_raw.sh
Labels: enhancement

#3608 CodeCov: split off contrib modules from main project
  .codecov.yml
Labels: QA, cleanup

#2557 imfile: emit error on startup if no working directory is set
  plugins/imfile/imfile.c
  runtime/rsyslog.h
  tests/imfile-basic.sh
Labels: enhancement

#3613 testbench plumbing: remove left-over debug output
  tests/diag.sh
Labels: cleanup

#3612 mmnormalize: add test for proper $parsesuccess support
  tests/Makefile.am
  tests/mmnormalize_parsesuccess-vg.sh
  tests/mmnormalize_parsesuccess.sh
Labels: testbench

#3615 openssl driver: clean up a bit
  runtime/nsd_ossl.c
  tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
Labels: cleanup

#3619 testbench: add even more debug info to imfile-symlink test
  tests/imfile-symlink.sh
Labels: testbench

#3617 tcpflood: Added support setting OpenSSL command parameters
  tests/Makefile.am
  tests/diag.sh
  tests/imtcp-tls-ossl-basic-tlscommands.sh
  tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
  tests/tcpflood.c
Labels: bug, enhancement, testbench

#3616 dnscache: add global parameter dnscache.default.ttl
  runtime/dnscache.c
  runtime/dnscache.h
  runtime/glbl.c
  tests/Makefile.am
  tests/dnscache-TTL-0-vg.sh
  tests/dnscache-TTL-0.sh
Labels: enhancement

#3600 tests: omhttp: add Python 3 compatibility
  tests/diag.sh
  tests/omhttp_server.py
Labels: testbench

#3621 testbench: add test for smtradfile string generator
  tests/Makefile.am
  tests/smtradfile-vg.sh
  tests/smtradfile.sh
Labels: testbench

#3620 testbench: add base test for omudpspoof
  .codecov.yml
  tests/Makefile.am
  tests/omudpspoof_errmsg_no_params.sh
Labels: testbench

#3624 dnscache: fix looking issue detected by Coverity Scan
  runtime/dnscache.c
  runtime/dnscache.h
  runtime/glbl.c
  tests/diag.sh
  tests/dnscache-TTL-0.sh
  tests/imtcp-tls-ossl-basic-tlscommands.sh
Labels: bug

#3629 command line interface: finally remove old -s, -l options
  runtime/dnscache.c
  tools/rsyslogd.c
  tools/syslogd.c
Labels: cleanup

#3630 core: emit a warning message for ultra-large queue size definitions
  runtime/queue.c
  tests/Makefile.am
  tests/queue_errmsg-oversize.sh
Labels: enhancement

#3632 imfile: new module parameter "statefile.directory"
  plugins/imfile/imfile.c
  tests/Makefile.am
  tests/imfile-basic.sh
  tests/imfile-statefile-directory.sh
Labels: enhancement

#3635 add capability to write full config file w/ includes (-o cmdline option)
  grammar/lexer.l
  grammar/parserif.h
  grammar/rainerscript.h
  tests/Makefile.am
  tests/config_output-o-option.sh
  tests/include-obj-in-if-vg.sh
  tools/rsyslogd.8
  tools/rsyslogd.c
Labels: enhancement

#3637 omfile bugfix: FlushOnTXEnd does not work reliably with dynafiles
  runtime/stream.c
  tools/omfile.c
Labels: bug

#3636 mmkubernetes - fix cache test python indentation
  tests/mmkubernetes-cache-expire.sh
Labels: bug, testbench

#3638 imtcp bugfix: oversize message truncation causes log to be garbled
  runtime/tcps_sess.c
  tests/imtcp-discard-truncated-msg.sh
Labels: bug
