Repository rsyslog/rsyslog, pull requests merged in 2019-06, with the labels that each got.

#3675 Advance cursor after reloading journal
  plugins/imjournal/imjournal.c
Labels: bug

#3688 core bugfix: segfault on startup depending on queue file names
  runtime/rsconf.c
  tests/Makefile.am
  tests/mainq_actq_DA.sh
Labels: bug

#3689 testbench: remove debug settings from kubernetes test
  tests/mmkubernetes-cache-expire.sh
Labels: bug, testbench

#3690 testbench: some modules were excluded in "make distcheck"
  Makefile.am
  tests/Makefile.am
Labels: bug, testbench

#3695 queue subsystem bugfix: oversize queue warning message shown as error
  runtime/queue.c
  tests/Makefile.am
  tests/queue_warnmsg-oversize.sh
Labels: bug

#3693 Fix for: CONTRIBUTING.md broken link #3673
  CONTRIBUTING.md
Labels: bug

#3696 testbench: update a test to current testbench best practice
  tests/pmrfc3164-AtSignsInHostname.sh
Labels: cleanup, testbench

#3701 imfile: remove no longe needed debug info
  runtime/stream.c
Labels: cleanup

#3700 testbench: check that valgrind runs start up correctly
  tests/omamqp1-basic.sh
Labels: DO-NOT-MERGE_work-in-progress

#3702 testbench bugfix: potentially invalid grep call at least on some plat…
  tests/diag.sh
Labels: bug, testbench

#3357 platform bugfix: HUP did not work reliably on some platforms
  tests/array_lookup_table.sh
  tests/array_lookup_table_misuse-vg.sh
  tests/diag.sh
  tests/dynstats_nometric.sh
  tests/dynstats_overflow-vg.sh
  tests/dynstats_overflow.sh
  tests/lookup_table.sh
  tests/lookup_table_bad_configs.sh
  tests/lookup_table_no_hup_reload.sh
  tests/multiple_lookup_tables.sh
  tests/sparse_array_lookup_table.sh
  tools/rsyslogd.c
Labels: bug

#3708 testbench: fix tests affected by commit 8791323c92039
  tests/omrabbitmq_error_server0.sh
  tests/omrabbitmq_error_server1.sh
  tests/omrabbitmq_error_server2.sh
  tests/omrabbitmq_error_server3.sh
  tests/omrabbitmq_raw.sh
Labels: bug, testbench

#3715 omfile: fix potential hang/segfault on HUP of dynafile action
  tools/omfile.c
Labels: bug

#3714 testbench: add omfile tests based on real-world issue
  tests/Makefile.am
  tests/diag.sh
  tests/gzipwr_hup-vg.sh
  tests/gzipwr_hup.sh
  tests/omfile_hup-vg.sh
  tests/omfile_hup.sh
Labels: DO-NOT-MERGE_work-in-progress

#3720 doc fix: outdated link in README
  README.md
Labels: bug, doc missing

#3721 testbench framework: use ip tool instead of outdated ifconfig
  tests/diag.sh
Labels: testbench

#3723 core bugfix: message duplication copied incorrect timestamp
  runtime/msg.c
Labels: bug

#3722 testbench: check MsgDup() properly duplicates all properties
  tests/Makefile.am
  tests/msgdup_props.sh
Labels: bug

#3729 testbench: fix clickhouse test
  tests/clickhouse-errorfile.sh
Labels: bug, testbench
