Repository rsyslog/rsyslog, pull requests merged in 2019-05, with the labels that each got.

#3642 queue subsystem: permit to disable "light delay mark"
  runtime/queue.c
Labels: enhancement

#3644 config processing: check disk queue file is unique
  runtime/queue.c
  runtime/queue.h
  runtime/rsconf.c
  runtime/rsyslog.h
  tests/Makefile.am
  tests/diskqueue-non-unique-prefix.sh
Labels: bug, enhancement

#3641 imfile: fix file handle leak under OOM condition
  plugins/imfile/imfile.c
Labels: bug

#3648 Fixing build of lmcry_gcry.so.
  runtime/Makefile.am
Labels: bug

#3649 testbench bugfix: imfile-symlink failed w/ parallel test run
  tests/diag.sh
  tests/imfile-symlink.sh
Labels: bug, testbench

#3650 new global config parameter "internalmsg.severity"
  runtime/glbl.c
  runtime/glbl.h
  tools/rsyslogd.c
Labels: enhancement

#3651 emit info-level success message on lookup table load (startup)
  runtime/lookup.c
  tests/Makefile.am
  tests/glbl-internalmsg_severity-info-shown.sh
Labels: enhancement

#3655 core: harden shutdown processing on FreeBSD
  tests/glbl-internalmsg_severity-info-shown.sh
  tools/rsyslogd.c
Labels: bug

#3654 change default of internalmsg.severity global parameter, add tests
  runtime/glbl.c
  tests/Makefile.am
  tests/glbl-internalmsg_severity-debug-not_shown.sh
  tests/glbl-internalmsg_severity-debug-shown.sh
  tools/rsyslogd.c
Labels: enhancement

#3653 queue subsystem: provide better user status messages
  runtime/queue.c
  tests/Makefile.am
  tests/da-queue-persist.sh
Labels: enhancement

#3657 global config: new parameters for ruleset queue defaults
  runtime/glbl.c
  runtime/queue.c
  runtime/queue.h
  tests/Makefile.am
  tests/glbl-ruleset-queue-defaults.sh
Labels: doc missing, enhancement

#3659 testbench: renable test hostname-getaddrinfo-fail.sh
  tests/hostname-getaddrinfo-fail.sh
Labels: testbench

#3660 testsuite: Fixed wrong parameter check in diag.sh (tcpflood())
  tests/diag.sh
  tests/imtcp-tls-ossl-basic-tlscommands.sh
Labels: bug

#3658 bugfix: error messages if config.enabled="off" is used
  grammar/rainerscript.c
  tests/Makefile.am
  tests/config_enabled-off.sh
Labels: bug

#3663 template: add datatype template option for JSON generation
  runtime/msg.c
  template.c
  template.h
  tests/Makefile.am
  tests/json-nonstring.sh
Labels: enhancement

#3671 Fixes #3667 - Leading space is lost on message when using RFC5424, SD is set and message starts with space
  tools/pmrfc5424.c
Labels: bug
