Repository rsyslog/rsyslog, pull requests merged in 2019-08, with the labels that each got.

#3775 testbench: add test for imrelp HUP handling
  tests/Makefile.am
  tests/diag.sh
  tests/imptcp-basic-hup.sh
  tests/imrelp-basic-hup.sh
  tests/imtcp-basic-hup.sh
Labels: testbench

#3774 testbench: modernize test
  tests/imrelp-basic.sh
Labels: cleanup, testbench

#3781 omfile bugfix: race file when async writing is enabled
  runtime/stream.c
Labels: bug

#3783 core/janitor bugfix: properly maintain dynafile cache
  tools/omfile.c
Labels: bug

#3786 testbench: add test for outchannel functionality
  tests/Makefile.am
  tests/omfile-outchannel.sh
Labels: testbench

#3785 testbench: add test for omfile module parameters
  tests/Makefile.am
  tests/omfile-module-params.sh
Labels: enhancement, testbench

#3791 iminternal bugfix: race on termination
  runtime/atomic.h
  runtime/rsconf.c
  tools/iminternal.c
  tools/rsyslogd.c
Labels: bug

#3789 testbench bugfix: some tests were executed when req module was missing
  tests/Makefile.am
Labels: bug, testbench

#3773 Enable checkpath option in omhttp
  contrib/omhttp/omhttp.c
  tests/omhttp-retry.sh
Labels: enhancement

#3790 testbench: add thread analyzer blacklist
  runtime/nsd_ossl.c
  tests/tsan.supp
Labels: testbench

#3793 testbench: add basic tests for omusrmsg
  tests/Makefile.am
  tests/omusrmsg-errmsg-no-params.sh
  tests/omusrmsg-noabort-legacy.sh
  tests/omusrmsg-noabort.sh
Labels: enhancement, testbench

#3797 imptcp bugfix: received bytes counter improperly maintained
  plugins/imptcp/imptcp.c
  tests/tsan.supp
Labels: bug

#3782 testbench: add multithreading tests with omfile async io/zip writing
  tests/Makefile.am
  tests/diag.sh
  tests/gzipwr_hup_multi_file.sh
  tests/gzipwr_hup_single_file.sh
Labels: testbench

#3804 Fix state-file closing with fsync option
  plugins/imjournal/imjournal.c
Labels: bug

#3801 omelasticsearch - rebindinterval
  plugins/omelasticsearch/omelasticsearch.c
Labels: bug

#3807 imptcp: simplify error message code
  plugins/imptcp/imptcp.c
Labels: cleanup

#3810 imptcp: cleanup error message generation
  plugins/imptcp/imptcp.c
Labels: cleanup

#3811 imptcp bugfix: port="0" parameter did not work as expected
  plugins/imptcp/imptcp.c
  tests/imptcp-basic-hup.sh
Labels: bug

#3816 testbench: increase runtime for know-problematic test
  tests/manytcp-too-few-tls-vg.sh
Labels: testbench

#3808 omelasticsearch bugfix: segfault on unknown retryRuleset
  plugins/omelasticsearch/omelasticsearch.c
Labels: bug

#3815 testbench: update sndrcv test to newest standard
  tests/diag.sh
  tests/sndrcv.sh
Labels: testbench

#3814 testbench: remove debug output; lessen kafaka tests output
  tests/diag.sh
Labels: testbench

#3813 testbench imptcp: make port use more reliable
  tests/imptcp-buffer-overflow.sh
  tests/imptcp-connection-msg-disabled.sh
  tests/imptcp-connection-msg-received.sh
  tests/imptcp-custom-delimiter.sh
  tests/imptcp-discard-truncated-msg.sh
  tests/imptcp_framing_regex-oversize.sh
  tests/imptcp_framing_regex.sh
  tests/imptcp_large.sh
Labels: testbench

#3821 testbench: make gzipwr_large test more reliable and improve plumbing
  tests/diag.sh
  tests/gzipwr_large.sh
Labels: testbench

#3819 testbench: add test for imuxsock legacy format
  tests/Makefile.am
  tests/imuxsock_legacy.sh
Labels: testbench

#3809 testbench: add tests for omelasticsearch error configs
  tests/Makefile.am
  tests/es-duplicated-ruleset-vg.sh
  tests/es-duplicated-ruleset.sh
Labels: testbench

#3818 testbench: modernize mmpstrucdata-case test
  tests/mmpstrucdata-case.sh
Labels: testbench

#3824 testbench: modernize tests and make them more reliable
  tests/asynwr_simple.sh
  tests/asynwr_simple_2.sh
  tests/diag.sh
Labels: testbench

#3822 imtcp bugfix: multiple listnerPortFile parameter did not work
  plugins/imdiag/imdiag.c
  plugins/imgssapi/imgssapi.c
  plugins/imtcp/imtcp.c
  runtime/tcpsrv.c
  runtime/tcpsrv.h
  tests/Makefile.am
  tests/diag.sh
  tests/imtcp-listen-port-file-2.sh
  tests/sndrcv.sh
  tests/suspend-omfwd-via-file.sh
Labels: bug

#3828 testbench: experimentally increase queue empty check period
  tests/asynwr_deadlock4.sh
Labels: DO-NOT-MERGE_work-in-progress

#3830 testbench: modernize and stabilize some tests
  configure.ac
  tests/Makefile.am
  tests/asynwr_deadlock.sh
  tests/asynwr_deadlock2.sh
  tests/asynwr_deadlock_2.sh
  tests/asynwr_small.sh
  tests/asynwr_timeout.sh
  tests/asynwr_timeout_2.sh
  tests/asynwr_tinybuf.sh
  tests/diag.sh
  tests/es-bulk-errfile-popul-def-format.sh
  tests/es-bulk-errfile-popul-def-interleaved.sh
  tests/es-bulk-errfile-popul-erronly-interleaved.sh
  tests/es-bulk-errfile-popul-erronly.sh
  tests/exec_tpl-concurrency.sh
  tests/gzipwr_flushInterval.sh
  tests/gzipwr_hup_multi_file.sh
  tests/queue-minbatch.sh
Labels: testbench

#3829 core/tcpsrv: potential race on startup/shutdown
  runtime/tcpsrv.c
  threads.c
Labels: bug

#3834 core: do not unnecessarily set hostname on each HUP
  runtime/glbl.c
Labels: bug

#3747 build system: support cross-platform build for mysql/mariadb
  configure.ac
Labels: help wanted

#3832 testbench: add basic test for immark
  tests/Makefile.am
  tests/immark.sh
Labels: testbench
