Repository rsyslog/rsyslog, pull requests merged in 2019-02, with the labels that each got.

#3449 testbench: mmdb valgrind tests failed is srcdir env was not set
  tests/mmdb-multilevel-vg.sh
  tests/mmdb-vg.sh
Labels: bug, testbench

#3463 fix legacy shell expression
  tests/imfile-error-not-repeated.sh
Labels: cleanup

#3423 omhttp: updates and improvements
  contrib/omhttp/omhttp.c
  tests/Makefile.am
  tests/diag.sh
  tests/omhttp-auth-vg.sh
  tests/omhttp-auth.sh
  tests/omhttp-basic-vg.sh
  tests/omhttp-basic.sh
  tests/omhttp-batch-fail-with-400.sh
  tests/omhttp-batch-jsonarray-compress-vg.sh
  tests/omhttp-batch-jsonarray-compress.sh
  tests/omhttp-batch-jsonarray-retry-vg.sh
  tests/omhttp-batch-jsonarray-retry.sh
  tests/omhttp-batch-jsonarray-vg.sh
  tests/omhttp-batch-jsonarray.sh
  tests/omhttp-batch-kafkarest-retry-vg.sh
  tests/omhttp-batch-kafkarest-retry.sh
  tests/omhttp-batch-kafkarest.sh
  tests/omhttp-batch-newline.sh
  tests/omhttp-retry-vg.sh
  tests/omhttp-retry.sh
  tests/omhttp_server.py
Labels: bug, enhancement

#3466 omrelp: add capability to specify tlslib for librelp
  configure.ac
  plugins/imrelp/imrelp.c
  plugins/omrelp/omrelp.c
  tests/Makefile.am
  tests/diag.sh
  tests/have_relpEngineSetTLSLibByName.c
  tests/imrelp-basic-vg.sh
  tests/imrelp-basic.sh
  tests/imrelp-invld-tlslib.sh
  tests/omrelp-invld-tlslib.sh
  tests/omrelp_wrong_authmode.sh
Labels: enhancement

#3475 fix legacy format
  tests/omfile-read-only.sh
Labels: cleanup

#3453 tcpflood: add new transport option relp-tls
  tests/Makefile.am
  tests/imrelp-tls.sh
  tests/tcpflood.c
Labels: enhancement, testbench

#3483 omclickhouse: work-around failed error detection
  plugins/omclickhouse/omclickhouse.c
Labels: testbench

#3481 testbench: increase timeout for test + better to exp reporting
  plugins/imdiag/imdiag.c
  tests/queue-encryption-disk_keyfile-vg.sh
Labels: testbench

#3461 clickhouse default template fix
  runtime/rsconf.c
Labels: bug

#3486 testbench: add test for omclickhouse with default template
  tests/Makefile.am
  tests/clickhouse-dflt-tpl.sh
Labels: testbench

#3490 testbench: increase explicit enqueue timeout for slow CI systems
  tests/complex1.sh
  tests/libdbi-asyn.sh
  tests/mysql-asyn-vg.sh
  tests/mysql-asyn.sh
  tests/threadingmqaq.sh
Labels: testbench

#3491 testbench: modernize test and hopefully make more robust on slow CI
  tests/timestamp-3339-udp.sh
Labels: testbench

#3492 cleanup: use less verbose C11 method to use pragmas
  action.c
  grammar/lexer.l
  grammar/rainerscript.c
  plugins/imfile/imfile.c
  plugins/imptcp/imptcp.c
  plugins/imrelp/imrelp.c
  plugins/imuxsock/imuxsock.c
  plugins/ommongodb/ommongodb.c
  plugins/omrelp/omrelp.c
  runtime/lookup.c
  runtime/net.c
  runtime/nsd_ptcp.c
  runtime/rsyslog.h
  runtime/srutils.c
  runtime/tcpsrv.c
  runtime/wti.c
  runtime/wtp.c
  template.c
Labels: cleanup

#3495 testbench: refactor imfile-symlink test for robustness and simplicity
  tests/imfile-symlink.sh
Labels: testbench

#3494 testbench tool minitcpsrvr: inform of regular shutdown
  tests/minitcpsrvr.c
Labels: testbench

#3497 lexer.l: change to PRAGMA macros
  grammar/lexer.l
Labels: cleanup

#3499 cleanup: remove no longer needed include
  action.c
Labels: cleanup

#3500 testbench: bind startup timeout to general runtime timeout
  tests/diag.sh
Labels: testbench

#3502 testbench: fix daqueue-dirty-shutdown test
  tests/daqueue-dirty-shutdown.sh
Labels: bug, testbench

#3505 testbench: harden long-running tests against slow CI environment
  tests/imptcp_conndrop-vg.sh
  tests/imptcp_conndrop.sh
Labels: testbench

#3501 testbench: increase TB_TEST_MAX_RUNTIME
  tests/diag.sh
Labels: testbench

#3509 testbench: make shutdown more reliable
  tests/diag.sh
  tests/imrelp-manyconn.sh
  tests/queue-encryption-disk_keyfile.sh
  tests/queue-minbatch-queuefull.sh
Labels: DO-NOT-MERGE_work-in-progress, testbench

#3518 testbench: queue_minbatch does not work on solaris
  tests/queue-minbatch.sh
Labels: testbench
