Repository rsyslog/rsyslog, pull requests merged in 2019-11, with the labels that each got.

#3906 mmkubernetes bugfix: improper use of calloc()
  contrib/omhttp/omhttp.c
Labels: bug

#3932 MMDARWIN:: Optimisations, new parameters, update to protocol header
  contrib/mmdarwin/mmdarwin.c
  contrib/mmdarwin/protocol.h
Labels: enhancement

#3944 ossl driver: fix wrong OpenSSL Version check (OPENSSL_VERSION_NUMBER)
  runtime/nsd_ossl.c
  tests/imtcp-tls-ossl-basic-tlscommands.sh
  tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
  tests/tcpflood.c
Labels: bug

#3954 imrelp: remove unsafe debug instrumentation
  plugins/imrelp/imrelp.c
Labels: bug

#3956 queue cleanup: remove no longer needed debug output
  runtime/queue.c
Labels: bug, cleanup

#3943 permit finer-grained control over imrelp/queue processing flow
  plugins/imrelp/imrelp.c
  runtime/queue.c
  runtime/queue.h
  runtime/rsyslog.h
Labels: enhancement, sponsored

#3964 imfile: add new input parameter escapeLF.replacement
  contrib/imtuxedoulog/imtuxedoulog.c
  plugins/imfile/imfile.c
  plugins/omkafka/omkafka.c
  runtime/stream.c
  runtime/stream.h
  tests/Makefile.am
  tests/imfile-escapelf.replacement-empty.sh
  tests/imfile-escapelf.replacement.sh
Labels: doc missing, enhancement

#3970 imjournal bugfix: do not wait too long on recovery try
  plugins/imjournal/imjournal.c
Labels: bug

#3966 core queue: emit warning if parameters are set for direct queue
  runtime/queue.c
  tests/Makefile.am
  tests/queue-direct-with-no-params.sh
  tests/queue-direct-with-params-given.sh
Labels: enhancement

#3965 travis: remove no longer needed Trusty install scripts
  .travis.yml
  tests/travis/install.sh
Labels: QA

#3978 build system: remove ./tests/*.log during "make clean"
  tests/Makefile.am
Labels: testbench

#3983 testbench: add some debugging instrumentation
  tests/diag.sh
  tests/mysql-basic.sh
  tests/mysqld-start.sh
Labels: testbench

#3977 omprog: detect violation of interface protocol
  plugins/omprog/omprog.c
  tests/Makefile.am
  tests/omprog-if-error.sh
Labels: enhancement

#3984 testbench: obtain python binary path via AM_PATH_PYTHON
  configure.ac
  tests/Makefile.am
  tests/diag.sh
  tests/es-basic.sh
  tests/es-bulk-errfile-popul-def-format.sh
  tests/es-bulk-errfile-popul-def-interleaved.sh
  tests/es-bulk-errfile-popul-erronly-interleaved.sh
  tests/es-bulk-errfile-popul-erronly.sh
  tests/es-bulk-retry.sh
  tests/es-writeoperation.sh
  tests/mmkubernetes-basic-vg.sh
  tests/mmkubernetes-basic.sh
  tests/mmkubernetes-cache-expire.sh
  tests/omamqp1-basic.sh
  tests/rscript_parse_time.sh
  tests/set-envvars.in
Labels: testbench

#3982 omhttp: add basic support for Loki Rest
  contrib/omhttp/omhttp.c
  tests/Makefile.am
  tests/diag.sh
  tests/omhttp-batch-lokirest-retry-vg.sh
  tests/omhttp-batch-lokirest-retry.sh
  tests/omhttp-batch-lokirest.sh
Labels: enhancement

#3971 testbench: improve mysql test framework plumbing
  devtools/prep-mysql-db.sh
  tests/Makefile.am
  tests/action-tx-errfile.sh
  tests/action-tx-single-processing.sh
  tests/clickhouse-stop.sh
  tests/diag.sh
  tests/libdbi-asyn.sh
  tests/libdbi-basic-vg.sh
  tests/libdbi-basic.sh
  tests/mysql-actq-mt-withpause-extended.sh
  tests/mysql-actq-mt-withpause-vg.sh
  tests/mysql-actq-mt-withpause.sh
  tests/mysql-actq-mt.sh
  tests/mysql-asyn-vg.sh
  tests/mysql-asyn.sh
  tests/mysql-basic-cnf6.sh
  tests/mysql-basic-vg.sh
  tests/mysql-basic.sh
Labels: enhancement, testbench

#3869 fix transactional on remove HardErrors
  action.c
Labels: bug

#3995 testbench: make some tls/ossl tests more robust
  tests/sndrcv_tls_anon_rebind.sh
  tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
Labels: testbench

#3968 openssl: Fixed Error output (logmsg).
  runtime/nsd_ossl.c
Labels: enhancement

#3998 testbench: fix some python env-induced issues
  tests/improg_simple_multi.sh
  tests/mmexternal-SegFault-vg.sh
  tests/omprog-output-capture-mt.sh
Labels: bug, testbench

#3999 testbench: fix some issue finding correct python interpreter
  tests/diag.sh
Labels: testbench
