Repository rsyslog/rsyslog, pull requests merged in 2019-01, with the labels that each got.

#3391 changed input source for clickhouse tests
  tests/clickhouse-basic.sh
  tests/clickhouse-bulk-load.sh
  tests/clickhouse-bulk.sh
  tests/clickhouse-limited-batch.sh
  tests/clickhouse-load.sh
  tests/clickhouse-retry-error.sh
  tests/clickhouse-select.sh
  tests/clickhouse-wrong-insert-syntax.sh
  tests/clickhouse-wrong-template-option.sh
Labels: testbench

#3392 testbench: fix minor nits in bash scripting
  tests/imfile-wildcards-dirs-multi.sh
  tests/imfile-wildcards-dirs-multi2.sh
  tests/imfile-wildcards-dirs-multi3.sh
  tests/imfile-wildcards-dirs-multi5.sh
  tests/imfile-wildcards-dirs2.sh
  tests/omfile-read-only.sh
Labels: testbench

#3398 testbench nitfixes: modernize arithmetic expressions
  tests/imfile-logrotate.sh
  tests/imfile-wildcards-dirs-multi.sh
  tests/imfile-wildcards-dirs-multi2.sh
  tests/imfile-wildcards-dirs-multi3.sh
  tests/imfile-wildcards-dirs-multi4.sh
  tests/imfile-wildcards-dirs-multi5-polling.sh
  tests/imfile-wildcards-dirs-multi5.sh
  tests/imfile-wildcards-dirs2.sh
  tests/loop.sh
  tests/mysql-actq-mt-withpause-extended.sh
  tests/omprog-output-capture-mt.sh
  tests/omprog-single-instance-outfile.sh
  tests/omprog-single-instance.sh
  tests/omprog-transactions-failed-commits.sh
  tests/omprog-transactions-failed-messages.sh
  tests/omprog-transactions.sh
Labels: testbench

#3408 imzmq3/omzmq3: remove modules
  Makefile.am
  configure.ac
  contrib/imzmq3/Makefile.am
  contrib/imzmq3/README
  contrib/imzmq3/imzmq3.c
  contrib/omzmq3/Makefile.am
  contrib/omzmq3/README
  contrib/omzmq3/omzmq3.c
Labels: cleanup

#3403 action: add "action.resumeIntervalMax" parameter
  action.c
  action.h
Labels: enhancement

#3412 testbench: Added new omkafka tests for more coverage.
  plugins/omkafka/omkafka.c
  tests/omkafka-dynatopic.sh
  tests/omkafka-statistics.sh
Labels: bug

#3416 cleanup: remove commented-out code
  action.c
  runtime/modules.c
  runtime/tcpsrv.c
  template.c
Labels: cleanup

#3400 omkafka: Add ability to dump librdkafka statistics to a file
  plugins/omkafka/omkafka.c
Labels: enhancement

#3424 tcpflood bugfix: tool did not terminate on certificate error
  tests/imtcp-tls-basic.sh
  tests/imtcp_conndrop_tls-vg.sh
  tests/imtcp_conndrop_tls.sh
  tests/tcpflood.c
Labels: bug, testbench

#3429 clarify that commented-out code is intentional (as an example)
  grammar/rainerscript.h
Labels: cleanup

#3411 queue: add support for minimum batch sizes
  runtime/queue.c
  runtime/queue.h
  runtime/wti.c
  runtime/wti.h
  tests/Makefile.am
  tests/diag.sh
  tests/queue-minbatch-queuefull.sh
  tests/queue-minbatch.sh
Labels: doc missing, enhancement

#3440 omhttp: "fix" LGTM false positive regarding commented out code
  contrib/omhttp/omhttp.c
Labels: cleanup

#3436 testbench: fix imjournal tests; add imjournal valgrind test
  tests/Makefile.am
  tests/diag.sh
  tests/imjournal-statefile-vg.sh
  tests/imjournal-statefile.sh
  tests/imrelp-manyconn-vg.sh
Labels: bug, testbench

#3435 Added missing free of received journal cursor
  plugins/imjournal/imjournal.c
Labels: bug

#3446 configure: remove orphaned enable_libcurl status from overview
  configure.ac
Labels: cleanup
