Repository rsyslog/rsyslog, pull requests merged in 2019-07, with the labels that each got.

#3725 omclickhouse: fix segfault on omclickhouse batchmode
  plugins/omclickhouse/omclickhouse.c
Labels: bug

#3672 testbench: test for leading space issue in RFC 5424 parser
  tests/Makefile.am
  tests/diag.sh
  tests/omrabbitmq_error_server0.sh
  tests/omrabbitmq_error_server1.sh
  tests/omrabbitmq_error_server2.sh
  tests/omrabbitmq_error_server3.sh
  tests/omrabbitmq_raw.sh
  tests/rfc5424parser-sp_at_msg_start.sh
Labels: testbench

#3735 cleanup any libee mentions and clarify state in ChangeLog
  ChangeLog
  plugins/mmaudit/mmaudit.c
  runtime/msg.c
  runtime/rsyslog.h
Labels: cleanup

#3737 function bugfix: "ipv42num" misspelled as "ip42mum" (without "v")
  grammar/rainerscript.c
  tests/rscript_ipv42num.sh
Labels: bug

#3733 imuxsock: support FreeBSD 12 out of the box
  plugins/imuxsock/imuxsock.c
Labels: bug

#3750 core/action: no error file written if act suspended on TX commit
  action.c
  tests/suspend-omfwd-via-file.sh
Labels: bug

#3754 imtcp: enable listenPortFileName parameter
  plugins/imtcp/imtcp.c
  runtime/tcpsrv.c
  tests/diag.sh
  tests/imtcp-basic.sh
Labels: enhancement, testbench

#3755 core/action: special handling for suspending action via ext file
  action.c
  tests/Makefile.am
  tests/suspend-omfwd-via-file.sh
  tests/suspend-via-file.sh
Labels: enhancement

#3762 Add "fsync" option for imjournal
  plugins/imjournal/imjournal.c
Labels: enhancement

#3556 Add mmdarwin module
  .lgtm.yml
  Makefile.am
  configure.ac
  contrib/mmdarwin/Makefile.am
  contrib/mmdarwin/mmdarwin.c
  contrib/mmdarwin/protocol.h
  tests/Makefile.am
  tests/mmdarwin_empty_fields-vg.sh
  tests/mmdarwin_empty_fields.sh
  tests/mmdarwin_empty_key-vg.sh
  tests/mmdarwin_empty_key.sh
  tests/mmdarwin_errmsg_no_params.sh
  tests/mmdarwin_errmsg_no_sock-vg.sh
  tests/mmdarwin_errmsg_no_sock.sh
  tests/mmdarwin_invalid_fields-vg.sh
  tests/mmdarwin_invalid_fields.sh
  tests/mmdarwin_non_existing_fields-vg.sh
  tests/mmdarwin_non_existing_fields.sh
  tests/mmdarwin_successful_call-vg.sh
  tests/mmdarwin_successful_call.sh
Labels: doc missing, enhancement

#3780 imrelp bugfix: hang after HUP
  plugins/imrelp/imrelp.c
  runtime/glbl.c
  runtime/glbl.h
Labels: bug
