Repository rsyslog/rsyslog, pull requests merged in 2019-12, with the labels that each got.

#4000 Handle journal invalidate
  plugins/imjournal/imjournal.c
Labels: bug

#3990 Thorougher state-file renaming and cleaning
  plugins/imfile/imfile.c
Labels: bug

#4004 core/config: "fix" valgrind false positive
  plugins/imdiag/imdiag.c
  template.c
Labels: DO-NOT-MERGE_work-in-progress

#3986 omsnmp: Fix "traptype" variable checking.
  plugins/omsnmp/omsnmp.c
Labels: bug, sponsored

#3994 omsnmp: Add support for new option "snmpv1dynsource"
  Makefile.am
  configure.ac
  plugins/omsnmp/omsnmp.c
  tests/Makefile.am
  tests/diag.sh
  tests/sndrcv_omsnmpv1_udp.sh
  tests/sndrcv_omsnmpv1_udp_dynsource.sh
  tests/sndrcv_omsnmpv1_udp_invalidoid.sh
  tests/snmptrapreceiver.py
Labels: enhancement, sponsored

#4044 fix indention
  runtime/dnscache.c
Labels: cleanup

#4045 fix misleading/invalid indention
  template.c
Labels: cleanup

#4025 bugfixes: small issues detected by clang static analyzer 9
  contrib/imdocker/imdocker.c
  contrib/mmkubernetes/mmkubernetes.c
  contrib/omrabbitmq/omrabbitmq.c
  grammar/rainerscript.c
  plugins/imgssapi/imgssapi.c
  plugins/imkafka/imkafka.c
  plugins/omgssapi/omgssapi.c
  plugins/omkafka/omkafka.c
  plugins/omlibdbi/omlibdbi.c
  plugins/omudpspoof/omudpspoof.c
  plugins/pmnormalize/pmnormalize.c
  runtime/modules.c
  runtime/queue.c
  tools/rscryutil.c
Labels: DO-NOT-MERGE_work-in-progress

#4023 testbench: cleanup no longer needed debug instrumentation
  tests/diag.sh
Labels: cleanup, testbench

#4046 bugfix core: potential segfault in template engine
  action.c
Labels: bug

#3962 relp: Add support setting openssl configuration commands.
  configure.ac
  plugins/imrelp/imrelp.c
  plugins/omrelp/omrelp.c
  tests/Makefile.am
  tests/diag.sh
  tests/have_relpSrvSetTlsConfigCmd.c
  tests/imrelp-tls-cfgcmd.sh
  tests/sndrcv_relp_tls-cfgcmd.sh
  tests/tcpflood.c
Labels: enhancement

#4048 testbench: test imtcp "addtlFrameDelimiter" module param
  tests/imtcp-basic.sh
  tests/imtcp_addtlframedelim.sh
Labels: enhancement, testbench

#4049 omhiredis: fix potential NULL pointer use (very unlikely)
  contrib/omhiredis/omhiredis.c
Labels: bug

#4052 testbench: modernize test and make more robust in regard to timing
  tests/timegenerated-utc-legacy.sh
Labels: testbench

#4051 OMHIREDIS:: ADD 'SET' MODE
  contrib/omhiredis/omhiredis.c
Labels: bug, enhancement

#4057 omclickhouse: set maximum time for sending data to ClickHouse
  plugins/omclickhouse/omclickhouse.c
Labels: enhancement

#4047 new default development container and update Travis to new compilers
  contrib/imdocker/imdocker.c
  devtools/default_dev_container
  devtools/run-static-analyzer.sh
  tests/travis/travis-run-compile-tests.sh
Labels: QA

#4059 testbench: harden tests against port-assignment races
  tests/imtcp-tls-gtls-x509fingerprint.sh
  tests/imtcp-tls-gtls-x509name.sh
  tests/imtcp-tls-ossl-basic.sh
  tests/imtcp-tls-ossl-x509fingerprint.sh
  tests/imtcp-tls-ossl-x509name.sh
  tests/imtcp-tls-ossl-x509valid.sh
Labels: testbench

#4066 fix spelling errors in text files
  ChangeLog
  IMFILE
  KNOWN_ISSUES
  NEWS
  README.AIX
  README.AIX.IBM
  contrib/README
  contrib/imtuxedoulog/README.md
  contrib/mmgrok/README
  contrib/omamqp1/README.md
  contrib/omhttpfs/README.md
  plugins/external/INTERFACE.md
  plugins/external/README.md
  plugins/mmdblookup/README.md
  solaris/README
  tests/CI/README
  tests/README
Labels: cleanup

#4067 core bugfix: APP-NAME fields could become empty
  runtime/msg.c
  tests/Makefile.am
  tests/empty-app-name.sh
Labels: bug

#4072 fix some alignment issues
  action.c
  plugins/imfile/imfile.c
  plugins/imptcp/imptcp.c
  runtime/nsd_ptcp.c
  runtime/rsyslog.h
Labels: cleanup

#4074 core bugfix: rsyslog aborts when config parse error is detected
  runtime/rsconf.c
Labels: bug

#4073 omelasticsearch: improve curl reply buffer handling
  plugins/omelasticsearch/omelasticsearch.c
Labels: enhancement
