Repository rsyslog/rsyslog, pull requests merged in 2020-06, with the labels that each got.

#4316 operatingstatefile bugfix: month was given too low
  runtime/operatingstate.c
Labels: bug

#4031 imfile: add new parameter "persistStateAfterSubmission"
  plugins/imfile/imfile.c
Labels: enhancement

#4318 ksi bugfix: Optimized code in KSI module initialization fixed.
  runtime/lib_ksils12.c
Labels: bug

#3988 NEW INPUT MODULE:: impcap, network packets input module
  Makefile.am
  configure.ac
  contrib/impcap/Makefile.am
  contrib/impcap/arp_parser.c
  contrib/impcap/dns_parser.c
  contrib/impcap/eth_parser.c
  contrib/impcap/ftp_parser.c
  contrib/impcap/http_parser.c
  contrib/impcap/icmp_parser.c
  contrib/impcap/impcap.c
  contrib/impcap/ipv4_parser.c
  contrib/impcap/ipv6_parser.c
  contrib/impcap/ipx_parser.c
  contrib/impcap/llc_parser.c
  contrib/impcap/parsers.h
  contrib/impcap/smb_parser.c
  contrib/impcap/tcp_parser.c
  contrib/impcap/udp_parser.c
  tests/dns.pcap
  tests/http.cap
  tests/impcap_basic_dns.sh
  tests/impcap_basic_dns_vg.sh
  tests/impcap_basic_http.sh
  tests/impcap_basic_http_vg.sh
  tests/impcap_errmsg_device_doesnt_exist.sh
  tests/impcap_errmsg_file_doesnt_exist.sh
  tests/impcap_errmsg_no_params.sh
  tests/impcap_errmsg_too_much_params.sh
Labels: enhancement

#4321 openssl: Fixed memory leak when tls handshake failed.
  runtime/nsd_ossl.c
  tests/Makefile.am
  tests/imtcp-tls-ossl-basic-brokenhandshake-vg.sh
Labels: bug

#4322 Fixing imfile segfaulting on selinux denial
  plugins/imfile/imfile.c
Labels: bug

#4069 queue: permit ability to double size at shutdown
  runtime/glbl.c
  runtime/glbl.h
  runtime/queue.c
Labels: doc missing, enhancement
