Repository rsyslog/rsyslog, pull requests merged in 2020-02, with the labels that each got.

#4163 imfile bugfix: timeout did not work on very busy system
  plugins/imfile/imfile.c
Labels: bug

#4159 testbench: create random test_id
  tests/diag.sh
  tests/imfile-endregex-timeout-with-shutdown.sh
Labels: testbench

#4167 Fixed processing of 'cofig.enabled' directive
  grammar/rainerscript.c
  grammar/rainerscript.h
  runtime/rsconf.c
Labels: bug

#4177 testbench: Fixed two minor issues in omkafkadynakey.sh test.
  tests/omkafkadynakey.sh
Labels: bug, testbench

#4188 core bugfix: too early parsing of incoming messages
  runtime/ratelimit.c
Labels: bug

#4182 openssl nsd driver: Switch to SSL_CTX_use_certificate_chain_file API
  runtime/nsd_ossl.c
  tests/tcpflood.c
Labels: bug

#4174 testbench: modify es_response_get_msgnum.py for python3
  tests/es_response_get_msgnum.py
Labels: bug, testbench

#4160 Add per minute rate limiting to imfile plugin
  plugins/imfile/imfile.c
Labels: enhancement
