Repository rsyslog/rsyslog, pull requests merged in 2020-09, with the labels that each got.

#4402 testbench: simplify test ID generation a bit
  tests/diag.sh
Labels: testbench

#4379 CI: run testbench on ubuntu 20 with github action
  .github/workflows/run_ubuntu_20.yml
  tests/CI/ubuntu20.04.supp
  tests/Makefile.am
Labels: QA

#4413 CI: add gcc-10 compile check
  .github/workflows/ci_compile.yml
  contrib/imdocker/imdocker.c
Labels: QA

#4416 MMDARWIN:: FIX POTENTIAL ZERO UUID WHEN REUSING EXISTING ONE
  contrib/mmdarwin/mmdarwin.c
Labels: bug

#4301 http input module
  .travis.yml
  Makefile.am
  configure.ac
  contrib/imhttp/Makefile.am
  contrib/imhttp/imhttp.c
  tests/Makefile.am
  tests/imhttp-getrequest-file-vg.sh
  tests/imhttp-getrequest-file.sh
  tests/imhttp-post-payload-compress-vg.sh
  tests/imhttp-post-payload-compress.sh
  tests/imhttp-post-payload-headers-vg.sh
  tests/imhttp-post-payload-headers.sh
  tests/imhttp-post-payload-large-vg.sh
  tests/imhttp-post-payload-large.sh
  tests/imhttp-post-payload-multi-lf-vg.sh
  tests/imhttp-post-payload-multi-lf.sh
  tests/imhttp-post-payload-multi-vg.sh
  tests/imhttp-post-payload-multi.sh
  tests/imhttp-post-payload-vg.sh
  tests/imhttp-post-payload.sh
  tests/testsuites/docroot/file.txt
  tests/testsuites/imhttp-large-data.txt
  tests/travis/install.sh
  tests/travis/run.sh
Labels: doc missing, enhancement

#4419 CI: increase CentOS 6 github check max runtime
  .github/workflows/run_centos_6.yml
Labels: QA

#4417 imtcp bugfix: broken connection not necessariy detected
  runtime/nsd_ptcp.c
Labels: bug

#4418 core bugfix: potential segfault on querey of PROGRAMNAME property
  runtime/msg.c
Labels: bug

#4426 core/network: obey net.enableDNS=off when querying local hostname
  runtime/net.c
Labels: bug

#4424 Replace GNUTLS_SHUT_RDWR by GNUTLS_SHUT_WR when ending TLS connections
  runtime/nsd_gtls.c
Labels: bug
