Repository rsyslog/rsyslog, pull requests merged in 2020-01, with the labels that each got.

#4080 testbench: rough fix for clickhouse 2019 test data problem
  tests/clickhouse-dflt-tpl.sh
Labels: bug

#4077 testbench: improve speed of elasticsearch tests
  tests/Makefile.am
  tests/diag.sh
  tests/diskqueue-multithread-es.sh
  tests/elasticsearch-stop.sh
  tests/es-basic-abort.sh
  tests/es-basic-bulk.sh
  tests/es-basic-errfile-empty.sh
  tests/es-basic-errfile-popul.sh
  tests/es-basic-es6.0.sh
  tests/es-basic-ha-vg.sh
  tests/es-basic-ha.sh
  tests/es-basic-server.sh
  tests/es-basic-vgthread.sh
  tests/es-basic.sh
  tests/es-bulk-errfile-empty.sh
  tests/es-bulk-errfile-popul-def-format.sh
  tests/es-bulk-errfile-popul-def-interleaved.sh
  tests/es-bulk-errfile-popul-erronly-interleaved.sh
  tests/es-bulk-errfile-popul-erronly.sh
  tests/es-bulk-errfile-popul.sh
  tests/es-bulk-retry.sh
  tests/es-execOnlyWhenPreviousSuspended.sh
  tests/es-maxbytes-bulk.sh
  tests/es-writeoperation.sh
Labels: enhancement, testbench

#4084 testbench cleanup: remove debug info
  tests/mysqld-start.sh
Labels: cleanup

#4088 testbench: modernize some tests and make more robust
  tests/action-tx-errfile.sh
  tests/action-tx-single-processing.sh
Labels: testbench

#4089 testbench: make imdocker tests more robust in regard to timing
  tests/imdocker-basic.sh
  tests/imdocker-multi-line.sh
Labels: testbench

#4096 testbench: use local kafka download cache if present
  tests/diag.sh
Labels: DO-NOT-MERGE_work-in-progress

#4100 omprog bugfix: unclean data type conversions
  plugins/omprog/omprog.c
Labels: bug

#4095 Solaris
  compat/strndup.c
  plugins/mmexternal/mmexternal.c
  runtime/glbl.c
  runtime/net.c
  runtime/rsconf.c
  runtime/rsyslog.h
  tools/omusrmsg.c
Labels: bug

#4094 testbench: do not create hanging tool instances
  tests/diag.sh
Labels: testbench

#4090 testbench: harden two tests against slow testbench machines
  tests/imtcp_conndrop_tls-vg.sh
  tests/imtcp_conndrop_tls.sh
Labels: testbench

#4102 testbench: modernize tests
  tests/imtcp-tls-basic.sh
  tests/imtcp-tls-ossl-basic-tlscommands.sh
  tests/sndrcv_tls_gtls_servercert_gtls_clientanon.sh
Labels: testbench

#4103 imtcp: add legacy directive $inputtcpserverlistenportfile
  plugins/imtcp/imtcp.c
  tests/asynwr_deadlock2.sh
  tests/diag.sh
Labels: enhancement, testbench

#4093 testbench: increase main msg queue default shutdown timeout
  tests/diag.sh
Labels: DO-NOT-MERGE_work-in-progress

#4104 testbench: fix races in old-style tests
  tests/imtcp-tls-basic-verifydepth.sh
  tests/imtcp-tls-ossl-basic-verifydepth.sh
  tests/imtcp-tls-ossl-invalid-verifydepth.sh
Labels: testbench

#4106 CI: add script to do a full CI run
  devtools/devcontainer.sh
  devtools/run-ci.sh
  devtools/run-configure.sh
  tests/clickhouse-start.sh
Labels: DO-NOT-MERGE_work-in-progress

#4110 testbench: modernize some tests
  tests/sndrcv_gzip.sh
Labels: testbench

#4109 Dynafile + async KSI module bugfix
  runtime/lib_ksils12.c
  runtime/lib_ksils12.h
Labels: bug

#4105 testbench: modernize some tests
  tests/abort-uncleancfg-goodcfg.sh
  tests/asynwr_deadlock.sh
  tests/asynwr_deadlock2.sh
  tests/asynwr_deadlock4.sh
  tests/asynwr_small.sh
  tests/asynwr_timeout.sh
  tests/asynwr_timeout_2.sh
  tests/asynwr_tinybuf.sh
  tests/badqi.sh
  tests/da-mainmsg-q.sh
  tests/daqueue-invld-qi.sh
  tests/daqueue-persist-drvr.sh
  tests/diag.sh
  tests/discard-allmark-vg.sh
  tests/discard-allmark.sh
Labels: testbench

#4114 core/network: fix cosmetic race during socket initialization
  runtime/net.c
Labels: cleanup

#4108 satisfy-gcc-flag-fno-common
  tools/omfile.h
Labels: bug

#4107 omfwd: parameter streamdriver.permitexpiredcerts did not work
  tests/Makefile.am
  tests/omfwd-tls-invalid-permitExpiredCerts.sh
  tools/omfwd.c
Labels: bug

#4042 Fix race condition related to libfastjson when using DA queue
  runtime/msg.c
Labels: bug

#4113 testbench: modernize tests and make more robust in regard to timing
  tests/rcvr_fail_restore.sh
  tests/sndrcv_gzip.sh
  tests/sndrcv_tls_ossl_anon_rebind.sh
  tests/timereported-utc-vg.sh
  tests/timereported-utc.sh
Labels: testbench

#4112 testbench: make tests more robust against slow machines
  tests/diag.sh
  tests/rscript_set_memleak-vg.sh
Labels: testbench

#4117 CI: emit failed test info to file failed-tests.log
  devtools/run-ci.sh
Labels: QA

#3924 Various bug fixes relating to shutdown handling
  runtime/tcpsrv.c
  tools/rsyslogd.c
Labels: bug

#4129 tcpsrv bugfix: build problem regression
  runtime/tcpsrv.c
Labels: bug

#4135 core bugfix: misadressing in pselect()
  tools/rsyslogd.c
Labels: bug

#4144 imfile bugfix: misadressing and potential segfault
  plugins/imfile/imfile.c
Labels: bug

#4141 Fixed saving of old file_id for statefiles
  plugins/imfile/imfile.c
Labels: bug

#4133 testbench: improvements
  tests/diag.sh
  tests/es-writeoperation.sh
  tests/imdocker-long-logline.sh
  tests/imtcp-basic.sh
  tests/mmjsonparse-w-o-cookie-multi-spaces.sh
  tests/mmjsonparse_cim.sh
  tests/mmjsonparse_cim2.sh
  tests/mmjsonparse_localvar.sh
  tests/mmjsonparse_simple.sh
  tests/omfile-read-only.sh
  tests/omfile_hup-vg.sh
  tests/omkafkadynakey.sh
  tests/omprog-restart-terminated-vg.sh
  tests/rcvr_fail_restore.sh
  tests/rulesetmultiqueue-v6.sh
  tests/rulesetmultiqueue.sh
Labels: DO-NOT-MERGE_work-in-progress, testbench

#4139 imdiag: reduce verbosenes in shutdown queue size reporting
  plugins/imdiag/imdiag.c
Labels: testbench

#4147 testbench: further improvements
  tests/asynwr_deadlock4.sh
  tests/diag.sh
  tests/inputname-imtcp.sh
  tests/omrelp_wrong_authmode.sh
  tests/sndrcv_tls_gtls_serveranon_gtls_clientanon.sh
Labels: testbench

#4145 oversize message log bugfix: do not close fd -1
  runtime/errmsg.c
Labels: bug

#4148 testbench: fix final issues for python 3 transition
  tests/Makefile.am
  tests/improg-multiline-test.py
  tests/mmexternal-SegFault-empty-jroot-vg.sh
  tests/mmexternal-SegFault.sh
  tests/omhttp_server.py
  tests/rscript_parse_time_get-ts.py
  tests/snmptrapreceiver.py
  tests/urlencode.py
Labels: testbench

#4151 testbench: add script for improved "failed test" log output
  devtools/gather-check-logs.sh
  devtools/run-ci.sh
Labels: QA, testbench

#4149 testbench: modernize
  plugins/imdiag/imdiag.c
  tests/Makefile.am
  tests/diag.sh
  tests/dynstats-json-vg.sh
  tests/dynstats-json.sh
  tests/dynstats-vg.sh
  tests/dynstats.sh
  tests/dynstats_ctr_reset.sh
  tests/dynstats_nometric.sh
  tests/dynstats_overflow-vg.sh
  tests/dynstats_overflow.sh
  tests/dynstats_prevent_premature_eviction-vg.sh
  tests/dynstats_prevent_premature_eviction.sh
  tests/dynstats_reset-vg.sh
  tests/dynstats_reset.sh
  tests/dynstats_reset_without_pstats_reset.sh
  tests/es-basic-ha.sh
  tests/es-bulk-retry.sh
  tests/mmexternal-SegFault.sh
  tests/mmpstrucdata-escaping.sh
  tests/no-dynstats-json.sh
  tests/no-dynstats.sh
  tests/omrabbitmq_data_1server.sh
  tests/omrabbitmq_data_2servers.sh
  tests/omrabbitmq_error_server0.sh
  tests/omrabbitmq_error_server1.sh
  tests/omrabbitmq_error_server2.sh
  tests/omrabbitmq_error_server3.sh
  tests/omrabbitmq_json.sh
  tests/omrabbitmq_raw.sh
  tests/omtcl.sh
  tests/rfc5424parser-sp_at_msg_start.sh
  tests/stats-cee-vg.sh
  tests/stats-cee.sh
  tests/stats-json-es.sh
  tests/stats-json-vg.sh
  tests/stats-json.sh
  tests/timereported-utc-legacy.sh
  tests/timereported-utc.sh
  tests/timestamp-3164-udp.sh
  tests/timestamp-3164.sh
  tests/timestamp-3339-udp.sh
  tests/timestamp-3339.sh
  tests/timestamp-mysql-udp.sh
  tests/timestamp-mysql.sh
  tests/timestamp-pgsql-udp.sh
  tests/timestamp-pgsql.sh
  tests/timestamp-subseconds-udp.sh
  tests/timestamp-subseconds.sh
Labels: testbench

#4154 devtools: limit output codecov can generate
  devtools/run-ci.sh
Labels: QA

#4152 devel tools: show stalled tests from "make check"
  devtools/gather-check-logs.sh
  tests/Makefile.am
  tests/imuxsock_ccmiddle.sh
  tests/imuxsock_ccmiddle_root.sh
  tests/imuxsock_ccmiddle_syssock.sh
  tests/imuxsock_hostname.sh
  tests/imuxsock_logger.sh
  tests/imuxsock_logger_parserchain.sh
  tests/imuxsock_logger_syssock.sh
  tests/imuxsock_traillf.sh
  tests/imuxsock_traillf_syssock.sh
  tests/ksi-verify-long.sh
  tests/ksi-verify-short.sh
  tests/resultdata/imuxsock_ccmiddle.log
  tests/resultdata/imuxsock_hostname.log
  tests/resultdata/imuxsock_logger.log
  tests/resultdata/imuxsock_traillf.log
  tests/testsuites/ksi-sample.log
Labels: QA

#4087 testbench: new test for loadbalancing via global variables
  tests/Makefile.am
  tests/action-tx-errfile.sh
  tests/action-tx-single-processing.sh
  tests/chkseq.c
  tests/loadbalance.sh
Labels: enhancement, testbench

#4157 testbench: add suppression for pselect() valgrind false positive
  tests/known_issues.supp
Labels: testbench

#4123 build system: change --enable-imfile-tests default to "yes"
  Makefile.am
  configure.ac
  devtools/gather-check-logs.sh
  tests/Makefile.am
  tests/imfile-basic-vgthread.sh
Labels: bug
