Repository rsyslog/rsyslog, pull requests merged in 2020-04, with the labels that each got.

#4213 openssl: add check for LIBRESSL
  runtime/nsd_ossl.c
  tests/imtcp-tls-ossl-basic-tlscommands.sh
  tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
  tests/tcpflood.c
Labels: enhancement

#4258 Travis: something is wrong with Travis, this just makes it non-fail
  .travis.yml
Labels: testbench

#4228 stream: Fix for segfault on imfile read
  runtime/stream.c
Labels: bug

#4218 ksi bugfix: Signer thread initialization is verified before usage.
  runtime/lib_ksils12.c
  runtime/lib_ksils12.h
Labels: bug

#4261 omprog: fix assert failed on HUP with output flag
  plugins/omprog/omprog.c
  tests/omprog-output-capture-mt.sh
Labels: bug

#4240 testbench: Add test for imrelp to check broken session handling.
  tests/Makefile.am
  tests/imrelp-sessionbreak-vg.sh
Labels: testbench

#4256 omprog: adapt test to testbench improvements
  .gitignore
  tests/omprog-single-instance-outfile.sh
  tests/omprog-single-instance.sh
Labels: testbench
