Repository rsyslog/rsyslog, pull requests merged in 2020-05, with the labels that each got.

#4219 omhttp: Adding multiple http headers capability
  contrib/omhttp/omhttp.c
  tests/Makefile.am
  tests/omhttp-httpheaderkey.sh
  tests/omhttp-multiplehttpheaders.sh
Labels: doc ready, enhancement

#4277 CI: fix problems with ElasticSearch download
  tests/diag.sh
Labels: testbench

#4136 ompipe: add action parameter tryResumeReopen
  tools/ompipe.c
Labels: enhancement

#4279 ompipe bugfix: race during HUP
  tools/ompipe.c
Labels: bug

#4283 imtcp: fix octet framing / stuffing problem with discardTruncatedMsg on
  runtime/tcps_sess.c
  tests/Makefile.am
  tests/imtcp-bigmessage-octetcounting.sh
  tests/imtcp-bigmessage-octetstuffing.sh
Labels: bug

#4294 config system bugfix: backticks cat segfault if file cannot be opened
  grammar/lexer.l
  tests/Makefile.am
  tests/include-obj-text-from-file-noexist.sh
Labels: bug
