Repository rsyslog/rsyslog, pull requests merged in 2020-08, with the labels that each got.

#4369 gnutls: Propagate CheckExtendedKeyPurpose when accepting connection
  runtime/nsd_gtls.c
Labels: bug

#4361 CI: use github actions for compile checks
  .github/workflows/ci_compile.yml
  devtools/devcontainer.sh
Labels: QA

#4334 remove rsyslog.service[.in] sample file
  Makefile.am
  platform/README
  platform/debian/rsyslog.service.10
  platform/debian/rsyslog.service.8
  platform/debian/rsyslog.service.9
  platform/redhat/centos/rsyslog.conf
  platform/redhat/centos/rsyslog.service
Labels: packaging

#4372 CI: do CodeCov checks via github action
  .github/workflows/run_kafka_codecov.yml
  .github/workflows/run_ubuntu_18_codecov.yml
Labels: QA

#4329 FIX::IMUDP: add missing free during freeCnf()
  plugins/imudp/imudp.c
Labels: bug

#4377 Ci imfile test debug
  tests/diag.sh
  tests/imfile-endregex-timeout-with-shutdown.sh
Labels: QA

#4380 Increase timeouts in imfile-basic-2GB-file and imfile-truncate-2GB-file
  tests/imfile-basic-2GB-file.sh
  tests/imfile-truncate-2GB-file.sh
Labels: QA, bug, testbench

#4382 imdocker bugfix: error reporting not always correct
  contrib/imdocker/imdocker.c
Labels: bug

#4370 Add max sessions for imptcp.c similar to imtcp.c to prevent OOM
  plugins/imptcp/imptcp.c
  tests/Makefile.am
  tests/imptcp_maxsessions.sh
Labels: enhancement

#4391 config bugfix: intended warning emitted as error
  grammar/rainerscript.c
Labels: bug

#4392 cosmetic: fix dummy module name in debug output
  plugins/imjournal/dummy.c
  plugins/imkafka/dummy.c
  plugins/omkafka/dummy.c
  plugins/omlibdbi/dummy.c
Labels: bug

#4390 testbench: add tests for relp chained certificates
  configure.ac
  tests/Makefile.am
  tests/check_relpEngineVersion.c
  tests/diag.sh
  tests/imrelp-tls-chainedcert.sh
  tests/sndrcv_relp_tls_chainedcert.sh
  tests/tcpflood.c
  tests/tls-certs/certchained.pem
Labels: QA
