Repository rsyslog/rsyslog, pull requests merged in 2021-11, with the labels that each got.

#4729 Avoid use of inet_addr() in favor of inet_aton()
  plugins/omsnmp/omsnmp.c
Labels: bug

#4731 ruleset bugfix: ruleset queue was incorrectly named
  runtime/ruleset.c
Labels: bug

#4732 CI: add Fedora 34 check run
  .github/workflows/run_fedora_34.yml
Labels: QA

#4736 testbench: modernize some tests
  tests/mmanon_both_modes_compatible.sh
  tests/mmanon_recognize_ipembedded.sh
  tests/mmanon_recognize_ipv4.sh
  tests/mmanon_recognize_ipv6.sh
  tests/mmanon_simple_33_ipv4.sh
  tests/mmanon_simple_8_ipv4.sh
  tests/mmanon_with_debug.sh
  tests/mmanon_zero_128_ipv6.sh
  tests/mmanon_zero_12_ipv4.sh
  tests/mmanon_zero_33_ipv4.sh
  tests/mmanon_zero_50_ipv6.sh
  tests/mmanon_zero_64_ipv6.sh
  tests/mmanon_zero_8_ipv4.sh
Labels: testbench

#4728 NEW CONTRIB::FFAUP:: URL parser module function using libfaup
  Makefile.am
  configure.ac
  contrib/ffaup/Makefile.am
  contrib/ffaup/ffaup.c
  runtime/rsyslog.h
  tests/Makefile.am
  tests/rscript_faup_all.sh
  tests/rscript_faup_all_2.sh
  tests/rscript_faup_all_2_vg.sh
  tests/rscript_faup_all_empty.sh
  tests/rscript_faup_all_empty_vg.sh
  tests/rscript_faup_all_vg.sh
  tests/rscript_faup_credential.sh
  tests/rscript_faup_credential_vg.sh
  tests/rscript_faup_domain.sh
  tests/rscript_faup_domain_vg.sh
  tests/rscript_faup_domain_without_tld.sh
  tests/rscript_faup_domain_without_tld_vg.sh
  tests/rscript_faup_fragment.sh
  tests/rscript_faup_fragment_vg.sh
  tests/rscript_faup_host.sh
  tests/rscript_faup_host_vg.sh
  tests/rscript_faup_mozilla_tld.sh
  tests/rscript_faup_mozilla_tld_vg.sh
  tests/rscript_faup_port.sh
  tests/rscript_faup_port_vg.sh
  tests/rscript_faup_query_string.sh
  tests/rscript_faup_query_string_vg.sh
  tests/rscript_faup_resource_path.sh
  tests/rscript_faup_resource_path_vg.sh
  tests/rscript_faup_scheme.sh
  tests/rscript_faup_scheme_vg.sh
  tests/rscript_faup_subdomain.sh
  tests/rscript_faup_subdomain_vg.sh
  tests/rscript_faup_tld.sh
  tests/rscript_faup_tld_vg.sh
  tests/rscript_faup_various.sh
Labels: enhancement

#4739 testbench: Add --keep-debuginfo=yes to default valgrind parameters.
  tests/diag.sh
Labels: testbench
