Repository rsyslog/rsyslog, pull requests merged in 2021-08, with the labels that each got.

#4650 imptcp bugfix: keep alive interval was incorrectly set
  plugins/imptcp/imptcp.c
Labels: bug

#4651 debug support: add indication of "being HUPed" to debug log
  tools/rsyslogd.c
Labels: enhancement

#4623 imtcp: permit to use different certificate files per input/action [alternative approach]
  plugins/imtcp/imtcp.c
  runtime/netstrms.c
  runtime/netstrms.h
  runtime/nsd.h
  runtime/nsd_gtls.c
  runtime/nsd_gtls.h
  runtime/nsd_ossl.c
  runtime/nsd_ossl.h
  runtime/nsd_ptcp.c
  runtime/tcpsrv.c
  runtime/tcpsrv.h
  tests/Makefile.am
  tests/imtcp-tls-input-2certs.sh
  tests/imtcp-tls-input-basic.sh
  tests/imtcp-tls-ossl-basic-tlscommands.sh
  tests/imtcp-tls-ossl-error-ca.sh
  tests/imtcp-tls-ossl-error-cert.sh
  tests/imtcp-tls-ossl-error-key.sh
  tests/imtcp-tls-ossl-error-key2.sh
  tests/imtcp-tls-ossl-input-2certs.sh
  tests/imtcp-tls-ossl-input-basic.sh
  tests/sndrcv_tls_anon_ipv6.sh
Labels: doc missing, enhancement

#4640 Close file descriptor when freshStartTail is turned on
  plugins/imfile/imfile.c
Labels: bug

#4653 omfwd: add capability for action-specific TLS certificate settings
  runtime/netstrm.c
  runtime/netstrm.h
  runtime/nsd_gtls.c
  tests/Makefile.am
  tests/diag.sh
  tests/sndrcv_tls_certvalid_action_level.sh
  tests/sndrcv_tls_ossl_certvalid_action_level.sh
  tools/omfwd.c
Labels: enhancement

#4628 CI: add test for imtcp not correctly starting up
  runtime/nsd_ptcp.c
  runtime/tcpsrv.c
  tests/Makefile.am
  tests/imtcp-tls-no-lstn-startup.sh
Labels: testbench

#4655 imudp: add socket type (IPv4 vs. 6) to input name
  plugins/imudp/imudp.c
Labels: enhancement

#4639 [omelasticsearch] Improve errorFile mutex handling
  plugins/omelasticsearch/omelasticsearch.c
Labels: bug

#4656 testbench: guard tests against unexpected warning messages
  tests/imuxsock_legacy.sh
  tests/imuxsock_logger.sh
  tests/imuxsock_logger_err.sh
  tests/imuxsock_logger_parserchain.sh
  tests/imuxsock_logger_root.sh
  tests/imuxsock_logger_syssock.sh
  tests/msgdup.sh
  tests/omfwd-keepalive.sh
Labels: testbench

#4657 imfile bugfix: hash char invalidly added in readmode != 0
  runtime/stream.c
Labels: bug

#4658 omelasticsearch: fix incorrect mutex error handling from commit 73277…
  plugins/omelasticsearch/omelasticsearch.c
Labels: bug

#4633 Fixing the deleteStateOnFileDelete option
  plugins/imfile/imfile.c
  tests/Makefile.am
  tests/imfile-statefile-delete.sh
  tests/imfile-statefile-no-delete.sh
Labels: bug

#4659 imklog: fix invalid memory adressing, could cause abort
  plugins/imklog/imklog.c
Labels: bug

#4626 imfile add `ignoreolderthanoption`
  plugins/imfile/imfile.c
  tests/Makefile.am
  tests/imfile-ignore-old-file-1.sh
  tests/imfile-ignore-old-file-2.sh
  tests/imfile-ignore-old-file-3.sh
  tests/imfile-ignore-old-file-4.sh
  tests/imfile-ignore-old-file-5.sh
  tests/imfile-ignore-old-file-6.sh
  tests/imfile-ignore-old-file-7.sh
Labels: enhancement

#4612 Percentile module to track percentile metrics via impstats
  grammar/lexer.l
  grammar/rainerscript.c
  grammar/rainerscript.h
  runtime/Makefile.am
  runtime/perctile_ringbuf.c
  runtime/perctile_ringbuf.h
  runtime/perctile_stats.c
  runtime/perctile_stats.h
  runtime/rsconf.c
  runtime/rsconf.h
  runtime/rsyslog.c
  runtime/typedefs.h
  tests/Makefile.am
  tests/perctile-simple-vg.sh
  tests/perctile-simple.sh
Labels: enhancement

#4661 openssl tls: Improved error message output on tls failures.
  runtime/nsd_ossl.c
Labels: enhancement

#4663 config: implement script-equavalent for $PrivDrop* statements
  grammar/rainerscript.c
  runtime/cfsysline.c
  runtime/glbl.c
  runtime/rsconf.c
  tests/Makefile.am
  tests/rscript_privdropgroup.sh
  tests/rscript_privdropgroupid.sh
  tests/rscript_privdropuser.sh
  tests/rscript_privdropuserid.sh
Labels: enhancement
