Repository rsyslog/rsyslog, pull requests merged in 2021-02, with the labels that each got.

#4506 CI: switch some tests from Ubuntu 18 to 20
  .github/workflows/run_ubuntu_20_san.yml
  .github/workflows/run_ubuntu_20_tsan.yml
  tests/asan.supp
  tests/tsan-rt.supp
  tests/tsan.supp
Labels: QA

#4515 CI add more fedora tests
  .github/workflows/run_fedora_31.yml
  .github/workflows/run_fedora_33.yml
Labels: QA

#4516 CI: remove CentOS 6 from CI
  .github/workflows/run_centos_6.yml
Labels: QA

#4517 CI bugfix: journal test installed wrong dependencies
  .github/workflows/run_journal.yml
Labels: QA

#4520 CI bugfix: journal testing setup was invalid
  .github/workflows/run_journal.yml
Labels: QA, bug

#4531 omfwd bugfix: segfault or error if port not given
  tools/omfwd.c
Labels: bug

#4518 Implement resume counting
  action.c
Labels: bug

#4524 Track failure statistics in actions
  action.c
Labels: bug

#4525 omfwd: add stats counter for sent bytes
  tests/Makefile.am
  tests/omfwd_impstats-tcp.sh
  tests/omfwd_impstats-udp.sh
  tools/omfwd.c
Labels: enhancement

#4535 testbench: changed tlscommands for librelp tls tests.
  tests/diag.sh
  tests/imrelp-tls-cfgcmd.sh
  tests/sndrcv_relp_tls-cfgcmd.sh
Labels: bug, testbench
