Repository rsyslog/rsyslog, pull requests merged in 2021-09, with the labels that each got.

#4671 gnutls: Propagate PrioritizeSAN when accepting a new connection
  runtime/nsd_gtls.c
Labels: bug

#4674 queue: Add NULL check in qDeqLinkedList
  plugins/imdiag/imdiag.c
  runtime/queue.c
Labels: bug

#4673 core bugfix: use of property $wday terminates string
  runtime/msg.c
Labels: bug

#4666 imuxsock: fix rate limiting not working in default configuration
  runtime/ratelimit.c
  tests/Makefile.am
  tests/imuxsock_logger_ratelimit.sh
Labels: bug

#4662 testbench: fix privdrop tests under root user
  tests/privdrop_common.sh
  tests/privdropgroup.sh
  tests/privdropgroupid.sh
  tests/privdropuser.sh
  tests/privdropuserid.sh
Labels: bug, testbench

#4675 testbench: bump kafka and zookeeper versions
  tests/diag.sh
Labels: testbench

#4679 testbench: add testcase for queue discardSeverity (linkedlist)
  tests/Makefile.am
  tests/diag.sh
  tests/omfwd_fast_imuxsock.sh
Labels: testbench

#4470 imhttp updates - query parameter ingestion & basic auth support
  configure.ac
  contrib/imhttp/Makefile.am
  contrib/imhttp/imhttp.c
  tests/Makefile.am
  tests/imhttp-post-payload-basic-auth-vg.sh
  tests/imhttp-post-payload-basic-auth.sh
  tests/imhttp-post-payload-query-params-vg.sh
  tests/imhttp-post-payload-query-params.sh
  tests/testsuites/htpasswd
Labels: enhancement

#4681 openssl: extended output information on connection failure
  runtime/nsd_ossl.c
  runtime/nsd_ptcp.c
Labels: bug

#4691 testbench bugfix: no pid file wait on elasticsearch startup
  .github/workflows/run_ubuntu_20_distcheck.yml
  tests/Makefile.am
  tests/diag.sh
Labels: bug, testbench

#4696 testbench: disable some clickhouse tests
  tests/clickhouse-errorfile.sh
  tests/clickhouse-wrong-insert-syntax.sh
Labels: testbench

#4685 Fix ElasticSearch Test broken by ES incompatibility
  tests/diag.sh
  tests/es-bulk-retry.sh
Labels: testbench, help wanted
