Repository rsyslog/rsyslog, pull requests merged in 2021-04, with the labels that each got.

#4471 Add built-in function get_property() to access property vars
  grammar/rainerscript.c
  grammar/rainerscript.h
  tests/Makefile.am
  tests/rscript_get_property-vg.sh
  tests/rscript_get_property.sh
Labels: doc missing

#4543 NEW CONTRIB::IMHIREDIS:: input redis module
  Makefile.am
  configure.ac
  contrib/imhiredis/COPYING
  contrib/imhiredis/COPYING_LESSER
  contrib/imhiredis/Makefile.am
  contrib/imhiredis/README
  contrib/imhiredis/imhiredis.c
  runtime/rsyslog.h
Labels: enhancement

#4572 imjournal: flush buffer before fsync
  plugins/imjournal/imjournal.c
Labels: bug

#4542 MMDBLOOKUP::Improvement:: allow mmdb to be reloaded on HUP signal
  plugins/mmdblookup/mmdblookup.c
  tests/libmaxmindb.supp
Labels: bug

#4537 RainerScript::FIX:: handle foreach with empty arrays/objects
  runtime/ruleset.c
Labels: bug

#4441 phase 1: consolidate current imtcp input params in a single structure
  plugins/imdiag/imdiag.c
  plugins/imgssapi/imgssapi.c
  plugins/imtcp/imtcp.c
  runtime/netstrm.c
  runtime/netstrm.h
  runtime/nsd.h
  runtime/nsd_gtls.c
  runtime/nsd_ossl.c
  runtime/nsd_ptcp.c
  runtime/nsd_ptcp.h
  runtime/tcps_sess.c
  runtime/tcpsrv.c
  runtime/tcpsrv.h
  runtime/typedefs.h
Labels: cleanup

#4584 tcpsrv bugfix: potential sluggishnes and hang on shutdown
  runtime/tcpsrv.c
Labels: bug
