Repository rsyslog/rsyslog, pull requests merged in 2021-01, with the labels that each got.

#4498 testbench: fix year-dependendt clickhouse test
  tests/clickhouse-dflt-tpl.sh
Labels: bug, testbench

#4497 testbench: fix kafkacat issues
  tests/diag.sh
Labels: testbench

#4501 testbench: fix invalid sequence of kafka tests runs
  tests/Makefile.am
Labels: bug, testbench

#4480 I4446bis
  .github/workflows/run_kafka_distcheck.yml
  .github/workflows/run_ubuntu_20_distcheck.yml
  devtools/run-ci.sh
  tests/diag.sh
  tests/known_issues.supp
Labels: QA, testbench

#4373 QA: use github action VMs for systemd journal tests
  .github/workflows/run_journal.yml
  .github/workflows/run_ubuntu_18_codecov.yml
Labels: QA

#4512 lookup table bugfix: data race on lookup table reload
  grammar/rainerscript.c
Labels: bug

#4513 Fix race between key-lookup and lookup-table-reload
  grammar/rainerscript.c
Labels: bug
