Repository rsyslog/rsyslog, pull requests merged in 2022-05, with the labels that each got.

#4861 testbench: removed unused notworking tls tests
  tests/sndrcv_tls_certless_ossl_client.sh
Labels: testbench, cleanup

#4863 imptcp: set OS worker thread name
  plugins/imptcp/imptcp.c
Labels: enhancement

#4858 tcpsrv: do not decrease number of to be processed fds on error
  runtime/tcpsrv.c
Labels: bug

#4865 testbench bugfix: some valgrind tests were run when valgrind disabled
  tests/Makefile.am
Labels: bug, testbench

#4808 Elasticsearch 8.x support (Data Stream API)
  plugins/omelasticsearch/omelasticsearch.c
Labels: enhancement

#4820 imptcp bugfix: worker thread starvation on extreme traffic
  plugins/imptcp/imptcp.c
Labels: bug

#4876 tcpsrv/imtcp: slight performance improvements
  runtime/tcps_sess.c
  runtime/tcps_sess.h
  tests/diag.sh
Labels: enhancement

#4566 omelastisearch: allow omitting deprecated _type field
  plugins/omelasticsearch/omelasticsearch.c
  tests/Makefile.am
  tests/diag.sh
  tests/es-searchType-empty.sh
Labels: enhancement
