Repository rsyslog/rsyslog, pull requests merged in 2022-02, with the labels that each got.

#4795 omelasticsearch: Fix indexSuccess impstats counter in bulkmode
  plugins/omelasticsearch/omelasticsearch.c
  tests/es-bulk-retry.sh
Labels: bug

#4789 rscript: literal numbers were not compared correctly
  grammar/rainerscript.c
Labels: bug

#4786 testbench: adapt contentcheck for tlscommands tests
  tests/imtcp-tls-ossl-basic-tlscommands.sh
  tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
Labels: testbench

#4793 testbench: test cases for rscript comparisons
  tests/Makefile.am
  tests/rscript_number_comparison_LE-vg.sh
  tests/rscript_number_comparison_LE.sh
  tests/rscript_number_comparison_LT.sh
  tests/rscript_number_comparison_all-vg.sh
  tests/rscript_number_comparison_all.sh
Labels: testbench, QA

#4690 testbench: restore original order of ES test execution
  .github/workflows/run_ubuntu_20_distcheck.yml
  tests/Makefile.am
Labels: testbench

#4762 ompgsql: allow connection params via connection string
  configure.ac
  plugins/ompgsql/ompgsql.c
  runtime/syslogd-types.h
  tests/pgsql-basic-conninfo-vg.sh
Labels: enhancement

#4798 imfile: Remove inotify watch descriptor on inode change detected
  plugins/imfile/imfile.c
  tests/imfile-rename.sh
Labels: bug

#4805 regression fix: script string comparison did not work correctly
  grammar/rainerscript.c
Labels: bug
