Repository rsyslog/rsyslog, pull requests merged in 2022-07, with the labels that each got.

#4916 CI: improve use of github action matrix feature
  .github/workflows/ci_compile.yml
  .github/workflows/run_centos_7.yml.TO_DELETE
  .github/workflows/run_centos_8.yml.TO_DELETE
  .github/workflows/run_checks.yml
  .github/workflows/run_elasticsearch.yml.TO_DELETE
  .github/workflows/run_fedora_34.yml.TO_DELTE
  .github/workflows/run_fedora_35.yml.TO_DELTE
  .github/workflows/run_kafka_codecov.yml.TO_DELETE
  .github/workflows/run_tumbleweed.yml.TO_DELETE
  .github/workflows/run_ubuntu_18_codecov.yml.TO_DELETE
  .github/workflows/run_ubuntu_18_gtls_only.yml.TO_DELETE
  .github/workflows/run_ubuntu_20.yml.TO_DELETE
  .github/workflows/run_ubuntu_20_codecov.yml.TO_DELETE
  .github/workflows/run_ubuntu_20_distcheck.yml.TO_DELETE
  .github/workflows/run_ubuntu_20_san.yml.TO_DELETE
  .github/workflows/run_ubuntu_20_tsan.yml.TO_DELETE
  plugins/omlibdbi/omlibdbi.c
  runtime/conf.c
  runtime/rsyslog.h
  tests/CI/ubuntu22.04.supp
Labels: QA

#4921 MMDBLOOKUP::FIXED:: Avoid Rsyslog crashes when a mmdb file cannot be opened/read
  plugins/mmdblookup/mmdblookup.c
Labels: bug

#4925 CI: suppress TSAN exception for known-good case
  plugins/imptcp/imptcp.c
  tests/tsan-rt.supp
Labels: QA

#4923 stream cleanup: move error message to debug log, only
  runtime/stream.c
Labels: cleanup

#4926 CI: further modernizations
  .github/workflows/run_checks.yml
Labels: QA

#4934 CI: add new TSAN suppression
  tests/tsan-rt.supp
Labels: QA

#4939 Fix memory leak when free action worker data table
  action.c
Labels: bug

#4929 Fix memory leak when globally de-initialize GnuTLS
  runtime/nsd_gtls.c
Labels: bug

#4937 imptcp: slight tuning
  plugins/imptcp/imptcp.c
  tests/imptcp_multi_line.sh
Labels: enhancement
