Repository rsyslog/rsyslog, pull requests merged in 2022-11, with the labels that each got.

#5010 imjournal: add second fallback to the message identifier
  plugins/imjournal/imjournal.c
Labels: bug, enhancement

#5023 ksi bugfix: sending of too many signing requests fixed.
  runtime/lib_ksils12.c
  runtime/lib_ksils12.h
Labels: bug

#5026 kafka: fix building modules with static librdkafka
  plugins/omkafka/Makefile.am
Labels: bug

#5028 rsyslog.conf man page bugfix: description of selectors
  tools/rsyslog.conf.5
Labels: bug, doc

#5032 testbench: fix the wrong message injection object of instance 1
  tests/diag.sh
  tests/sndrcv.sh
  tests/sndrcv_failover.sh
  tests/sndrcv_gzip.sh
  tests/sndrcv_kafka-vg-rcvr.sh
  tests/sndrcv_kafka_fail.sh
  tests/sndrcv_kafka_failresume.sh
  tests/sndrcv_relp_dflt_pt.sh
  tests/sndrcv_relp_rebind.sh
  tests/sndrcv_relp_tls.sh
  tests/sndrcv_relp_tls_certvalid.sh
  tests/sndrcv_relp_tls_prio.sh
  tests/sndrcv_tls_anon_hostname.sh
  tests/sndrcv_tls_anon_ipv4.sh
  tests/sndrcv_tls_anon_ipv6.sh
  tests/sndrcv_tls_certvalid.sh
  tests/sndrcv_tls_certvalid_expired.sh
  tests/sndrcv_tls_certvalid_expired_defaultmode.sh
  tests/sndrcv_tls_gtls_serveranon_gtls_clientanon.sh
  tests/sndrcv_tls_gtls_servercert_gtls_clientanon.sh
  tests/sndrcv_tls_ossl_anon_ipv4.sh
  tests/sndrcv_tls_ossl_anon_rebind.sh
  tests/sndrcv_tls_ossl_certvalid_expired.sh
  tests/sndrcv_tls_ossl_certvalid_tlscommand.sh
  tests/sndrcv_udp_nonstdpt.sh
Labels: bug, testbench
