Repository rsyslog/rsyslog, pull requests merged in 2022-01, with the labels that each got.

#4768 CI: remove unnecessary dependency
  .github/workflows/run_journal.yml
Labels: bug, QA

#4763 Fix an use-after-free bug in omlibdbi.c
  plugins/omlibdbi/omlibdbi.c
Labels: bug

#4769 CI: cleanup journal test environment
  .github/workflows/run_journal.yml
Labels: QA

#4773 cleanup: remove unused variable
  runtime/strms_sess.c
Labels: cleanup

#4779 CI: remove fedora 33 based testing
  .github/workflows/run_fedora_33.yml
Labels: QA

#4775 ikmsg: fix EPIPE error check in the /dev/kmsg reader loop
  contrib/imkmsg/kmsg.c
Labels: bug

#4780 testbench: adjust ElasticSearch startup parameters
  tests/diag.sh
Labels: testbench
