Repository rsyslog/rsyslog, pull requests merged in 2022-12, with the labels that each got.

#5038 omprog bugfix: invalid status handling at called program startup
  plugins/omprog/omprog.c
Labels: bug

#5039 testbench: make python http server based tests more reliable
  tests/diag.sh
  tests/errfile-basic.sh
  tests/omhttp-auth.sh
  tests/omhttp-basic.sh
  tests/omhttp-batch-dynrestpath.sh
  tests/omhttp-batch-fail-with-400.sh
  tests/omhttp-batch-jsonarray-compress.sh
  tests/omhttp-batch-jsonarray-retry.sh
  tests/omhttp-batch-jsonarray.sh
  tests/omhttp-batch-kafkarest-retry.sh
  tests/omhttp-batch-kafkarest.sh
  tests/omhttp-batch-lokirest-retry.sh
  tests/omhttp-batch-lokirest.sh
  tests/omhttp-batch-newline.sh
  tests/omhttp-dynrestpath.sh
  tests/omhttp-httpheaderkey.sh
  tests/omhttp-multiplehttpheaders.sh
  tests/omhttp-retry.sh
  tests/omhttp_server.py
Labels: bug, testbench

#5040 Fix typos spotted by lintian
  tools/rsyslog.conf.5
Labels: bug, doc
