Repository rsyslog/rsyslog, pull requests merged in 2022-03, with the labels that each got.

#4812 glblGetMaxLine() fix when config not yet exists, fixes #4810
  runtime/glbl.c
Labels: bug

#4811 Add option to limit error file to configured size
  action.c
  action.h
  tests/Makefile.am
  tests/action-tx-errfile-maxsize.sh
  tests/diag.sh
  tests/omfwd-errfile-maxsize.sh
Labels: enhancement

#4815 Don't refer to errno when the pthread library fails
  plugins/imtcp/imtcp.c
  plugins/omelasticsearch/omelasticsearch.c
  runtime/lib_ksils12.c
  runtime/tcpsrv.c
  runtime/wti.c
  threads.c
Labels: bug

#4835 testbench: change git access protocol to cover github change
  tests/solaris/prep-libfastjson.sh
  tests/solaris/prep-librelp.sh
Labels: testbench

#4832 Add missing include to fix compilation error, resolves #4827
  contrib/omfile-hardened/omfile-hardened.c
Labels: bug

#4833 rsyslogd: adjust the order of doHUP() and processImInternal()
  tools/rsyslogd.c
Labels: bug
