Repository rsyslog/rsyslog, pull requests merged in 2022-04, with the labels that each got.

#4839 CI: move docker worker to github action
  .github/workflows/run_ubuntu_18_gtls_only.yml
Labels: QA

#4829 Fix: check ReportSuspension option before print message about action retry
  action.c
Labels: bug

#4792 omelasticsearch: add optional timeout for the index operation
  plugins/omelasticsearch/omelasticsearch.c
Labels: enhancement

#4758 add property options to support ISO week/year number
  runtime/datetime.c
  runtime/datetime.h
  runtime/msg.c
  template.c
  template.h
  tests/Makefile.am
  tests/timestamp-isoweek.sh
Labels: enhancement

#4842 bugfix: cosmetic data races
  tools/rsyslogd.c
Labels: bug

#4592 Include programname in a new JSON template
  runtime/rsconf.c
Labels: enhancement

#4823 gnutls bugfix: Fix error handling in gtlsRecordRecv
  runtime/nsd_gtls.c
  runtime/nsd_gtls.h
  runtime/nsdsel_gtls.c
  runtime/tcpsrv.c
  tests/imtcp-tls-basic.sh
Labels: bug

#4849 Fix non-null-terminated-string used with strlen
  plugins/omkafka/omkafka.c
Labels: bug

#4850 MMDBLOOKUP::FIXED:: Fix parsing of data received from mmdb lib
  plugins/mmdblookup/mmdblookup.c
Labels: bug, enhancement

#4857 mmanon bugfix: shortened IPv6 not always anonymized
  plugins/mmanon/mmanon.c
  tests/mmanon_ipv6_port.sh
Labels: bug
