Repository rsyslog/rsyslog, pull requests merged in 2022-08, with the labels that each got.

#4943 mmanon: Simplified and fixed IPv4 digit detection.
  plugins/mmanon/mmanon.c
  tests/Makefile.am
  tests/mmanon_recognize_ipv4.sh
  tests/mmanon_simple_mallformed_ipv4.sh
Labels: bug

#4900 strings.h is missing in several files
  runtime/nsd_ossl.c
  tests/tcpflood.c
Labels: bug

#4895 imfile bugfix: message loss/duplication when monitored file is rotated
  plugins/imfile/imfile.c
  runtime/stream.c
  runtime/stream.h
  tests/Makefile.am
  tests/imfile-logrotate-async.sh
  tests/inputfilegen.c
Labels: bug

#4974 openssl: fix osslLastSSLErrorMsg call
  runtime/nsd_ossl.c
Labels: bug

#4971 tcpsrv: cleanup - remove commented out code
  runtime/tcpsrv.c
Labels: cleanup

#4969 imtcp: add option notifyonconnectionopen
  plugins/imtcp/imtcp.c
  runtime/tcpsrv.c
  runtime/tcpsrv.h
  tests/allowed-sender-tcp-fail.sh
  tests/allowed-sender-tcp-hostname-fail.sh
  tests/imtcp-connection-msg-recieved.sh
Labels: enhancement, doc missing
