Repository rsyslog/rsyslog, pull requests merged in 2022-10, with the labels that each got.

#4951 omrabbitmq: Add TLS support
  contrib/omrabbitmq/omrabbitmq.c
Labels: enhancement, doc missing

#5004 core bugfix: local hostname invalid if no global() config object given
  runtime/glbl.c
Labels: bug

#5001 testbench: Adjusted timing for test imfile-logrotate-async.sh
  tests/imfile-logrotate-async.sh
  tests/inputfilegen.c
Labels: bug, testbench
