Repository rsyslog/rsyslog, pull requests merged in 2023-08, with the labels that each got.

#5208 lookup tables bugfix: reload on HUP did not work when backgrounded
  runtime/lookup.c
  runtime/lookup.h
  runtime/rsconf.c
  tests/Makefile.am
  tests/diag.sh
  tests/lookup_table-hup-backgrounded.sh
  tools/rsyslogd.c
Labels: bug

#5209 testbench: cleanup and improve some more imfile tests
  tests/imfile-endmsg.regex-vg.sh
  tests/imfile-endmsg.regex.sh
  tests/imfile-endregex-save-lf-persist.sh
  tests/imfile-endregex-save-lf.sh
  tests/imfile-endregex-timeout-none-polling.sh
  tests/imfile-endregex-timeout-none.sh
  tests/imfile-endregex-timeout-polling.sh
  tests/imfile-endregex-timeout-with-shutdown-polling.sh
  tests/imfile-endregex-timeout.sh
  tests/imfile-endregex-vg.sh
  tests/imfile-endregex.sh
Labels: testbench, QA

#5200 CI: fix and cleaup github workflow
  .github/workflows/run_centos_7.yml.TO_DELETE
  .github/workflows/run_centos_8.yml.TO_DELETE
  .github/workflows/run_checks.yml
  .github/workflows/run_elasticsearch.yml.TO_DELETE
  .github/workflows/run_fedora_34.yml.TO_DELTE
  .github/workflows/run_fedora_35.yml.TO_DELTE
  .github/workflows/run_kafka_codecov.yml.TO_DELETE
  .github/workflows/run_tumbleweed.yml.TO_DELETE
  .github/workflows/run_ubuntu_18_codecov.yml.TO_DELETE
  .github/workflows/run_ubuntu_18_gtls_only.yml.TO_DELETE
  .github/workflows/run_ubuntu_20.yml.TO_DELETE
  .github/workflows/run_ubuntu_20_codecov.yml.TO_DELETE
  .github/workflows/run_ubuntu_20_distcheck.yml.TO_DELETE
  .github/workflows/run_ubuntu_20_san.yml.TO_DELETE
  .github/workflows/run_ubuntu_20_tsan.yml.TO_DELETE
  .github/workflows/run_ubuntu_22.yml.DELETE_ME
Labels: QA

#5168 Clear undefined behavior in libgcry.c (GH #5167)
  runtime/libgcry.c
Labels: bug
