Repository rsyslog/rsyslog, pull requests merged in 2023-10, with the labels that each got.

#5232 tcp net subsystem: handle data race gracefully
  runtime/nsdsel_ptcp.c
Labels: bug

#5234 Add new global config option "libcapng.enable"
  runtime/glbl.c
  runtime/rsconf.c
  runtime/rsconf.h
  tools/rsyslogd.c
Labels: enhancement

#5253 testbench: bump zookeeper version to match current offering
  tests/diag.sh
Labels: testbench

#5255 replace debian sample systemd service file by readme
  platform/debian/rsyslog.service
  platform/debian/rsyslog.service.README
Labels: cleanup

#5240 Typo fixes
  tools/rsyslogd.8
Labels: bug, doc

#5247 use logind instead of utmp for wall messages with systemd
  tools/omusrmsg.c
Labels: enhancement

#5146 imjournal: Support input module
  plugins/imjournal/imjournal.c
Labels: enhancement, doc missing

#5262 imklog bugfix: keepKernelTimestamp=off config param did not work
  plugins/imklog/bsd.c
  plugins/imklog/imklog.c
Labels: bug
