Repository rsyslog/rsyslog, pull requests merged in 2023-06, with the labels that each got.

#5155 Fix typo
  ChangeLog
Labels: bug, doc

#5144 Add new global config option "libcapng.default"
  runtime/glbl.c
  runtime/rsconf.c
  runtime/rsconf.h
  tools/rsyslogd.c
Labels: doc missing

#5141 tests: mmexternal-SegFault-empty-jroot-vg.sh: fix typo
  tests/mmexternal-SegFault-empty-jroot-vg.sh
Labels: bug, testbench

#5165 testbench: use newer zookeeper version in tests
  tests/diag.sh
Labels: testbench

#5169 IMHIREDIS::FIXED:: Restore compatiblity with hiredis < v1.0.0
  contrib/imhiredis/imhiredis.c
Labels: bug

#5166 Do not try to drop capabilities when we don't have any
  tools/rsyslogd.c
Labels: bug
