Repository rsyslog/rsyslog, pull requests merged in 2023-01, with the labels that each got.

#5052 core bugfix: template system may generate invalid json
  template.c
  tests/Makefile.am
  tests/json-onempty-at-end.sh
Labels: bug

#5062 CI: use newer version of zookeeper
  tests/diag.sh
Labels: testbench

#5061 fix typo
  ChangeLog
Labels: bug

#5055 fix version number for next scheduled stable release
  configure.ac
Labels: bug

#5054 openssl: fix undefined reference to CRYPTO_set_id_callback
  runtime/nsd_ossl.c
Labels: bug

#5027 Fix ffaup thread safety
  contrib/ffaup/ffaup.c
Labels: bug

#5065 substring function: enhancement and hardening
  grammar/rainerscript.c
  tests/Makefile.am
  tests/func-substring-invld-startpos-vg.sh
  tests/func-substring-invld-startpos.sh
  tests/func-substring-large-endpos.sh
  tests/func-substring-large-neg-endpos.sh
  tests/func-substring-relative-endpos.sh
Labels: enhancement

#5051 Fixed wrong type conversion in cstrLen()
  runtime/stringbuf.h
Labels: bug

#4999 Introduce --enable-libcap-ng configure option
  configure.ac
  runtime/debug.c
  runtime/modules.c
  runtime/rsconf.c
  runtime/rsyslog.h
  tools/rsyslogd.c
Labels: enhancement

#5071 CI: fix github CodeQL settings
  .github/workflows/codeql.yml
Labels: bug, QA

#5074 Fixed wrong type conversion in cstrLen() for debug mode as well
  parse.h
  runtime/stream.c
  runtime/stringbuf.c
  runtime/stringbuf.h
Labels: bug

#5070 core/template: implement negative position.to
  runtime/msg.c
  template.c
  tests/Makefile.am
  tests/template-topos-neg.sh
Labels: enhancement, doc missing
