Repository rsyslog/rsyslog, pull requests merged in 2023-11, with the labels that each got.

#5267 imfile: remove state file on file delete fix
  plugins/imfile/imfile.c
Labels: bug

#5264 imkmsg: add params parseKernelTimestamp and fixKernelTimeStamp
  contrib/imkmsg/imkmsg.c
  contrib/imkmsg/imkmsg.h
  contrib/imkmsg/kmsg.c
Labels: bug, enhancement

#5278 imkmsg: add params "readMode" and "expectedBootCompleteSeconds"
  contrib/imkmsg/imkmsg.c
  contrib/imkmsg/imkmsg.h
  contrib/imkmsg/kmsg.c
Labels: enhancement
