Repository rsyslog/rsyslog, pull requests merged in 2023-09, with the labels that each got.

#5224 tcpflood bugfix: plain tcp send error not properly reported
  tests/tcpflood.c
Labels: bug, testbench

#5223 omprog bugfix: Add CAP_DAC_OVERRIDE to the bounding set
  tools/rsyslogd.c
Labels: bug

#5138 Add the 'batchsize' parameter to imhiredis so we can configure the si…
  contrib/imhiredis/README
  contrib/imhiredis/imhiredis.c
Labels: enhancement

#5220 Avoid crash on restart in imrelp SIGTTIN handler
  plugins/imrelp/imrelp.c
Labels: bug
