Repository rsyslog/rsyslog, pull requests merged in 2024-11, with the labels that each got.

#5488 nsd_ptcp: remove debugging messages emited to stderr
  runtime/nsd_ptcp.c
  tests/Makefile.am
Labels: bug

#5361 fix(lexer): typo and missing space when file can't be accessed
  grammar/lexer.l
Labels: bug

#5454 Fix runConf NULL pointer refence
  tools/rsyslogd.c
Labels: bug

#5490 cleanup: remove variables that are no longer used
  parse.c
  runtime/modules.c
Labels: cleanup

#5477 imjournal: Fix first message loss after journal rotation
  plugins/imjournal/imjournal.c
Labels: bug

#5492 libksi: make build under C11 C standard
  runtime/lib_ksi_queue.c
Labels: cleanup

#5493 cleanup: remove unused variable
  plugins/mmdblookup/mmdblookup.c
Labels: cleanup

#5366 Do not free the uninitialized cstring.
  runtime/obj.c
Labels: bug

#5505 imdiag bugfix: racy network driver selection
  plugins/imdiag/imdiag.c
Labels: bug, testbench
