Repository rsyslog/rsyslog, pull requests merged in 2024-10, with the labels that each got.

#5466 testbench: correctly apply socket options in minitcpsrvr
  tests/minitcpsrvr.c
Labels: bug

#5468 regression fix: build issue on Solaris 10
  tests/minitcpsrvr.c
Labels: bug, testbench

#5450 network subsystem: improve connection failure error message
  runtime/nsd_ptcp.c
Labels: enhancement
