Repository rsyslog/rsyslog, pull requests merged in 2024-12, with the labels that each got.

#5509 omazureeventhubs: Handle invalid URL characters in config parameters
  plugins/omazureeventhubs/omazureeventhubs.c
Labels: bug

#5513 mmkubernetes: nitfix
  contrib/mmkubernetes/mmkubernetes.c
Labels: cleanup

#5526 CI: remove libgrok-related codeql checks
  .github/workflows/codeql.yml
Labels: testbench

#5514 Gnu23 workaround
  .github/workflows/ci_compile.yml
  runtime/cfsysline.c
  runtime/linkedlist.c
  runtime/linkedlist.h
  runtime/obj-types.h
  runtime/obj.c
  runtime/obj.h
  runtime/queue.c
  runtime/rsconf.c
  runtime/rsyslog.h
  runtime/ruleset.c
  tests/sndrcv_tls_anon_rebind.sh
  tests/sndrcv_tls_client_missing_cert.sh
  threads.c
  tools/iminternal.c
Labels: cleanup
