Repository rsyslog/rsyslog, pull requests merged in 2025-08, with the labels that each got.

#5916 doc: imdocker had invalid legacy config stmt info - removed
  doc/source/configuration/modules/imdocker.rst
Labels: bug

#5924 docs: split omelasticsearch params into individual pages
  doc/source/configuration/modules/omelasticsearch.rst
  doc/source/reference/parameters/omelasticsearch-allowunsignedcerts.rst
  doc/source/reference/parameters/omelasticsearch-asyncrepl.rst
  doc/source/reference/parameters/omelasticsearch-bulkid.rst
  doc/source/reference/parameters/omelasticsearch-bulkmode.rst
  doc/source/reference/parameters/omelasticsearch-dynbulkid.rst
  doc/source/reference/parameters/omelasticsearch-dynparent.rst
  doc/source/reference/parameters/omelasticsearch-dynpipelinename.rst
  doc/source/reference/parameters/omelasticsearch-dynsearchindex.rst
  doc/source/reference/parameters/omelasticsearch-dynsearchtype.rst
  doc/source/reference/parameters/omelasticsearch-errorfile.rst
  doc/source/reference/parameters/omelasticsearch-esversion-major.rst
  doc/source/reference/parameters/omelasticsearch-healthchecktimeout.rst
  doc/source/reference/parameters/omelasticsearch-indextimeout.rst
  doc/source/reference/parameters/omelasticsearch-maxbytes.rst
  doc/source/reference/parameters/omelasticsearch-parent.rst
  doc/source/reference/parameters/omelasticsearch-pipelinename.rst
  doc/source/reference/parameters/omelasticsearch-pwd.rst
  doc/source/reference/parameters/omelasticsearch-ratelimit-burst.rst
  doc/source/reference/parameters/omelasticsearch-ratelimit-interval.rst
  doc/source/reference/parameters/omelasticsearch-rebindinterval.rst
  doc/source/reference/parameters/omelasticsearch-retryfailures.rst
  doc/source/reference/parameters/omelasticsearch-retryruleset.rst
  doc/source/reference/parameters/omelasticsearch-searchindex.rst
  doc/source/reference/parameters/omelasticsearch-searchtype.rst
  doc/source/reference/parameters/omelasticsearch-server.rst
  doc/source/reference/parameters/omelasticsearch-serverport.rst
  doc/source/reference/parameters/omelasticsearch-skippipelineifempty.rst
  doc/source/reference/parameters/omelasticsearch-skipverifyhost.rst
  doc/source/reference/parameters/omelasticsearch-template.rst
  doc/source/reference/parameters/omelasticsearch-timeout.rst
  doc/source/reference/parameters/omelasticsearch-tls-cacert.rst
  doc/source/reference/parameters/omelasticsearch-tls-mycert.rst
  doc/source/reference/parameters/omelasticsearch-tls-myprivkey.rst
  doc/source/reference/parameters/omelasticsearch-uid.rst
  doc/source/reference/parameters/omelasticsearch-usehttps.rst
  doc/source/reference/parameters/omelasticsearch-writeoperation.rst
Labels: codex

#5935 ommysql: remove long-standing non-needed TODO item
  plugins/ommysql/ommysql.c
Labels: cleanup

#5939 doc: split imudp parameter docs
  doc/source/configuration/modules/imudp.rst
  doc/source/reference/parameters/imudp-address.rst
  doc/source/reference/parameters/imudp-batchsize.rst
  doc/source/reference/parameters/imudp-defaulttz.rst
  doc/source/reference/parameters/imudp-device.rst
  doc/source/reference/parameters/imudp-ipfreebind.rst
  doc/source/reference/parameters/imudp-name-appendport.rst
  doc/source/reference/parameters/imudp-name.rst
  doc/source/reference/parameters/imudp-port.rst
  doc/source/reference/parameters/imudp-preservecase.rst
  doc/source/reference/parameters/imudp-ratelimit-burst.rst
  doc/source/reference/parameters/imudp-ratelimit-interval.rst
  doc/source/reference/parameters/imudp-rcvbufsize.rst
  doc/source/reference/parameters/imudp-ruleset.rst
  doc/source/reference/parameters/imudp-schedulingpolicy.rst
  doc/source/reference/parameters/imudp-schedulingpriority.rst
  doc/source/reference/parameters/imudp-threads.rst
  doc/source/reference/parameters/imudp-timerequery.rst
Labels: codex

#5932 doc: clarify reverse DNS cache TTL parameters
  doc/source/configuration/global/index.rst
  doc/source/configuration/input_directives/rsconf1_allowedsender.rst
  doc/source/configuration/input_directives/rsconf1_dropmsgswithmaliciousdnsptrrecords.rst
  doc/source/configuration/modules/imptcp.rst
  doc/source/configuration/modules/imtcp.rst
  doc/source/configuration/modules/imudp.rst
  doc/source/configuration/modules/omfwd.rst
  doc/source/configuration/properties.rst
  doc/source/rainerscript/global.rst
  doc/source/troubleshooting/troubleshoot.rst
Labels: codex

#5832 Enhance backticks with ${VAR} support
  doc/source/rainerscript/constant_strings.rst
  grammar/lexer.l
  tests/Makefile.am
  tests/rscript_backticks-vg.sh
  tests/rscript_backticks_braces_envvar.sh
  tests/rscript_backticks_empty_envvar.sh
  tests/rscript_backticks_static_text.sh
Labels: codex

#5945 Fix transaction suspension handling
  action.c
  tests/omhttp-batch-fail-with-400.sh
  tests/omhttp-retry-timeout.sh
  tests/omprog-feedback-mt.sh
  tests/omprog-feedback.sh
  tests/omprog-transactions-failed-messages.sh
Labels: bug

#5953 doc: warn against unofficial and outdated doc clones
  doc/source/index.rst
Labels: documentation

#5956 doc: set html_baseurl to emit canonical tags
  doc/source/conf.py
Labels: documentation

#5959 docs: update containers overview for new Docker images
  doc/source/containers/container_features.rst
  doc/source/containers/development_images.rst
  doc/source/containers/docker_specifics.rst
  doc/source/containers/index.rst
  doc/source/containers/user_images.rst
  doc/source/installation/rsyslog_docker.rst
Labels: documentation, codex

#5977 imuxsock: split input parameter docs into reference pages
  doc/source/configuration/modules/imuxsock.rst
  doc/source/reference/parameters/imuxsock-annotate.rst
  doc/source/reference/parameters/imuxsock-createpath.rst
  doc/source/reference/parameters/imuxsock-flowcontrol.rst
  doc/source/reference/parameters/imuxsock-hostname.rst
  doc/source/reference/parameters/imuxsock-ignoreownmessages.rst
  doc/source/reference/parameters/imuxsock-ignoretimestamp.rst
  doc/source/reference/parameters/imuxsock-parsehostname.rst
  doc/source/reference/parameters/imuxsock-parsetrusted.rst
  doc/source/reference/parameters/imuxsock-ratelimit-burst.rst
  doc/source/reference/parameters/imuxsock-ratelimit-interval.rst
  doc/source/reference/parameters/imuxsock-ratelimit-severity.rst
  doc/source/reference/parameters/imuxsock-ruleset.rst
  doc/source/reference/parameters/imuxsock-socket.rst
  doc/source/reference/parameters/imuxsock-syssock-annotate.rst
  doc/source/reference/parameters/imuxsock-syssock-flowcontrol.rst
  doc/source/reference/parameters/imuxsock-syssock-ignoreownmessages.rst
  doc/source/reference/parameters/imuxsock-syssock-ignoretimestamp.rst
  doc/source/reference/parameters/imuxsock-syssock-name.rst
  doc/source/reference/parameters/imuxsock-syssock-parsehostname.rst
  doc/source/reference/parameters/imuxsock-syssock-parsetrusted.rst
  doc/source/reference/parameters/imuxsock-syssock-ratelimit-burst.rst
  doc/source/reference/parameters/imuxsock-syssock-ratelimit-interval.rst
  doc/source/reference/parameters/imuxsock-syssock-ratelimit-severity.rst
  doc/source/reference/parameters/imuxsock-syssock-unlink.rst
  doc/source/reference/parameters/imuxsock-syssock-use.rst
  doc/source/reference/parameters/imuxsock-syssock-usepidfromsystem.rst
  doc/source/reference/parameters/imuxsock-syssock-usespecialparser.rst
  doc/source/reference/parameters/imuxsock-syssock-usesystimestamp.rst
  doc/source/reference/parameters/imuxsock-unlink.rst
  doc/source/reference/parameters/imuxsock-usepidfromsystem.rst
  doc/source/reference/parameters/imuxsock-usespecialparser.rst
  doc/source/reference/parameters/imuxsock-usesystimestamp.rst
Labels: codex

#5987 ci: add copilot support instruction files
  .github/copilot-instructions.md
  .github/instructions/docs.instructions.md
  .github/instructions/modules.contrib.instructions.md
  .github/instructions/modules.plugins.instructions.md
Labels: AI

#5981 ci: add clang static analyzer workflow
  .github/workflows/clang-analyzer.yml
Labels: codex

#6004 omhttp: guard rest path template access
  contrib/omhttp/omhttp.c
Labels: codex

#6007 AI: add base prompt for rsyslog C code review assistant
  ai/rsyslog_bug_finder/base_prompt.txt
Labels: AI

#5982 atomic: remove trailing semicolons from helper macros
  action.h
  plugins/imptcp/imptcp.c
  runtime/atomic.h
  runtime/prop.h
  runtime/queue.h
  runtime/statsobj.h
  runtime/wti.h
  runtime/wtp.h
  tools/omfwd.c
  tools/pmrfc3164.c
Labels: codex

#6003 doc: restructure templates docs into hub and refs
  doc/source/configuration/templates.rst
  doc/source/reference/templates/templates-examples.rst
  doc/source/reference/templates/templates-legacy.rst
  doc/source/reference/templates/templates-options.rst
  doc/source/reference/templates/templates-reserved-names.rst
  doc/source/reference/templates/templates-statement-constant.rst
  doc/source/reference/templates/templates-statement-property.rst
  doc/source/reference/templates/templates-type-list.rst
  doc/source/reference/templates/templates-type-plugin.rst
  doc/source/reference/templates/templates-type-string.rst
  doc/source/reference/templates/templates-type-subtree.rst
Labels: documentation, codex

#6008 imdocker: fix cosmetic memory leak
  contrib/imdocker/imdocker.c
Labels: cleanup

#6006 tcpsrv: revert PR 5806 because it was ineffective
  runtime/tcps_sess.c
  runtime/tcps_sess.h
  runtime/tcpsrv.c
Labels: cleanup

#6009 imjournal: initialize instance fields to avoid invalid free
  plugins/imjournal/imjournal.c
Labels: bug, codex

#5978 template: fix missing lenStr in subtree templates
  template.c
  tests/Makefile.am
  tests/omfwd-subtree-tpl.sh
Labels: codex

#6032 community: add welcome message to first few commits
  .github/workflows/contributor-welcome.yml
Labels: community

#6028 docs: fix minor typos in docs/source
  .github/workflows/clang-analyzer.yml
  doc/source/concepts/janitor.rst
  doc/source/concepts/messageparser.rst
  doc/source/concepts/multi_ruleset.rst
Labels: documentation

#6040 CI: fix doc_build check which was not always built
  .github/workflows/doc_build.yml
Labels: bug, CI

#6041 Add actions analysis
  .github/workflows/codeql.yml
Labels: CI

#5994 Add namespace support for omjournal
  configure.ac
  doc/source/configuration/modules/omjournal.rst
  plugins/omjournal/omjournal.c
  runtime/rsyslog.h
Labels: enhancement

#6043 Potential fix for code scanning alert no. 44: Commented-out code
  runtime/wtp.c
Labels: cleanup

#6046 CI: ensure static analyzer script only runs when actually needed
  .github/workflows/clang-analyzer.yml
Labels: CI

#6048 ci: cancel superseded workflow runs
  .github/workflows/ci.yml.template
  .github/workflows/ci_codestyle_check.yml
  .github/workflows/ci_compile.yml
  .github/workflows/codeql.yml
  .github/workflows/commit_style_check.yml
  .github/workflows/doc_build.yml
  .github/workflows/run_checks.yml
  .github/workflows/run_journal.yml
  .github/workflows/run_kafka_distcheck.yml
  .github/workflows/yaml_lint.yml
Labels: CI

#6050 core: some code cleanup
  runtime/rsconf.c
Labels: cleanup
