Repository rsyslog/rsyslog, pull requests merged in 2025-07, with the labels that each got.

#5746 Add style checker improvements
  devtools/rsyslog_stylecheck.py
  doc/source/development/internal_tooling.rst
Labels: codex

#5751 testbench nitfix: improper format spec corrected
  tests/test_id.c
Labels: cleanup

#5758 AI tools: Add directory for future AI/ML tooling
  ai/README.md
Labels: enhancement, AI

#5749 imtcp: prevent double-enqueue of descriptors via inQueue flag
  runtime/tcpsrv.c
  runtime/tcpsrv.h
Labels: bug

#5750 imkmsg fix: Handle EAGAIN/EWOULDBLOCK check portably
  contrib/imkmsg/kmsg.c
Labels: cleanup

#5752 nsd_ptcp fix: misleading error messages (regression from ad1fd21)
  runtime/nsd_ptcp.c
Labels: bug

#5748 scripting: add endswith operator to property filters and RainerScript
  AGENTS.md
  doc/source/_ext/rsyslog_lexer.py
  doc/source/configuration/filters.rst
  doc/source/rainerscript/expressions.rst
  grammar/grammar.y
  grammar/lexer.l
  grammar/rainerscript.c
  runtime/ruleset.c
  runtime/stringbuf.c
  runtime/stringbuf.h
  runtime/typedefs.h
  tests/Makefile.am
  tests/endswith-basic.sh
Labels: enhancement

#5769 dev doc: add design notes to queue subsystem files
  .github/ISSUE_TEMPLATE/1_support_question.md
  runtime/queue.c
  runtime/queue.h
Labels: documentation

#5768 Document MsgSetRawMsg side effects
  runtime/msg.c
Labels: codex

#5777 AI support: relax indention rules
  AGENTS.md
Labels: AI

#5775 Add Doxygen headers for statsobj
  runtime/statsobj.c
  runtime/statsobj.h
Labels: documentation, codex

#5779 docker: reflect new state of repo
  packaging/docker/README.md
Labels: cleanup

#5772 Document GTLS certificate chain behavior
  doc/source/configuration/modules/imtcp.rst
Labels: documentation, codex

#5781 Update README and unify dev container builds
  README.md
  packaging/docker/dev_env/Makefile
Labels: codex

#5785 docs: Fix minor typos
  doc/source/configuration/properties.rst
  doc/source/tutorials/tls_cert_ca.rst
Labels: documentation

#5787 build: adjust version tag used for daily stable build process
  configure.ac
Labels: cleanup

#5665 Add optional PCRE match function
  AGENTS.md
  Makefile.am
  configure.ac
  plugins/fmpcre/Makefile.am
  plugins/fmpcre/README.md
  plugins/fmpcre/fmpcre.c
  tests/Makefile.am
  tests/ffmpcre-basic.sh
Labels: enhancement, codex

#5782 impstats: add support for Prometheus metrics output format
  plugins/impstats/impstats.c
  tests/Makefile.am
  tests/stats-prometheus.sh
Labels: enhancement

#5788 doc: add FAQ with commonly misunderstood config sequences
  doc/source/faq/common-config-mistakes.rst
  doc/source/faq/index.rst
Labels: documentation

#5596 imptcp bugfix: potential socket leak
  plugins/imptcp/imptcp.c
Labels: bug, DO-NOT-MERGE_work-in-progress

#5653 imhttp: add simple http health check functionality
  contrib/imhttp/imhttp.c
  tests/Makefile.am
  tests/imhttp-healthcheck.sh
  tests/imhttp-metrics.sh
Labels: enhancement

#5260 TESTING: Enhance action resume interval sleep time
  action.c
Labels: do_first

#5754 Add mmaitag plugin with real Gemini provider
  Makefile.am
  configure.ac
  doc/source/configuration/modules/mmaitag.rst
  plugins/mmaitag/Makefile.am
  plugins/mmaitag/ai_provider.h
  plugins/mmaitag/ai_provider_gemini.c
  plugins/mmaitag/ai_provider_gemini_mock.c
  plugins/mmaitag/mmaitag.c
  tests/Makefile.am
  tests/mmaitag-basic.sh
  tests/mmaitag-invalid-key.sh
Labels: enhancement, do_first, codex

#5833 Fix connection timing log calculation
  runtime/nsd_ptcp.c
Labels: bug, codex

#5828 Improve action.c documentation
  AGENTS.md
  action.c
  action.h
Labels: codex

#5836 Add yamllint GitHub Action
  .github/workflows/yaml_lint.yml
Labels: codex

#5840 doc: PoC transformations of legacy stament doc
  doc/source/_ext/rsyslog_lexer.py
  doc/source/_templates_minimal/README
  doc/source/conf.py
  doc/source/configuration/action/index.rst
  doc/source/configuration/action/rsconf1_actionexeconlywhenpreviousissuspended.rst
  doc/source/configuration/action/rsconf1_actionresumeinterval.rst
  doc/source/configuration/action/rsconf1_dirowner.rst
  doc/source/configuration/actions.rst
  doc/source/configuration/modules/mmaitag.rst
  doc/source/configuration/modules/omjournal.rst
Labels: documentation

#5846 Add LICENSE file for docs
  doc/LICENSE
Labels: codex

#5844 Add JSON build targets
  doc/Makefile
Labels: codex

#5858 CI: Enhance PR validation and update branch name
  .github/workflows/commit_style_check.yml
  tests/CI/PR_validation.sh
Labels: testbench

#5870 doc: Restructure omfwd documentation
  doc/source/configuration/modules/omfwd.rst
  doc/source/configuration/modules/omfwd/parameters/basic.rst
  doc/source/configuration/modules/omfwd/parameters/module.rst
  doc/source/development/doc_reference_section_guidelines.rst
Labels: documentation

#5874 CI/AI: trigger Gemini review on each PR code update
  .gemini/config.yml
Labels: testbench, AI

#5871 imjournal: fix vulnerability in state file creation
  plugins/imjournal/imjournal.c
Labels: bug
