Repository rsyslog/rsyslog, pull requests merged in 2025-10, with the labels that each got.

#6210 ci/tests: add QRadar JSON ingest test; fix diagtalker buf
  tests/diagtalker.c
  tests/testsuites/qradar_json
  tests/validate_json_equality.py
  tests/validate_json_shell.sh
Labels: CI

#6215 Codex/refactor rsyslog module documentation
  doc/source/configuration/modules/im3195.rst
  doc/source/reference/parameters/im3195-input3195listenport.rst
Labels: documentation

#6216 CI: run real Elasticsearch instance in github action
  .github/workflows/elasticsearch-tests.yml
  devtools/devcontainer.sh
  tests/diag.sh
  tests/es-bulk-errfile-popul-def-interleaved.sh
  tests/es-execOnlyWhenPreviousSuspended.sh
  tests/es-writeoperation.sh
Labels: CI

#6218 CI: enhance doc workflow to check tarball completeness
  .github/workflows/doc_build.yml
  Makefile.am
  configure.ac
Labels: documentation

#6220 tests: retry omfwd load-balancer flake before failing
  tests/omfwd-lb-1target-retry-full_buf.sh
Labels: CI

#6217 mmjsonparse: add find-json mode to parse embedded JSON
  doc/source/configuration/modules/mmjsonparse.rst
  doc/source/development/engine_overview.rst
  doc/source/reference/parameters/mmjsonparse-allow_trailing.rst
  doc/source/reference/parameters/mmjsonparse-max_scan_bytes.rst
  doc/source/reference/parameters/mmjsonparse-mode.rst
  plugins/mmjsonparse/mmjsonparse.c
  tests/Makefile.am
  tests/mmjsonparse-find-json-basic.sh
  tests/mmjsonparse-find-json-invalid-mode.sh
  tests/mmjsonparse-find-json-invalid.sh
  tests/mmjsonparse-find-json-parser-validation.sh
  tests/mmjsonparse-find-json-scan-limit.sh
  tests/mmjsonparse-find-json-trailing.sh
Labels: enhancement

#6227 doc: update tutorials for rainerscript syntax
  doc/source/tutorials/database.rst
  doc/source/tutorials/log_rotation_fix_size.rst
  doc/source/tutorials/recording_pri.rst
  doc/source/tutorials/reliable_forwarding.rst
Labels: documentation

#6230 doc: im prove log pipeline documentation
  doc/source/concepts/index.rst
  doc/source/concepts/log_pipeline/design_patterns.rst
  doc/source/concepts/log_pipeline/example_json_transform.rst
  doc/source/concepts/log_pipeline/index.rst
  doc/source/concepts/log_pipeline/stages.rst
  doc/source/concepts/log_pipeline/troubleshooting.rst
  doc/source/getting_started/beginner_tutorials/04-message-pipeline.rst
Labels: documentation
