Repository rsyslog/rsyslog, pull requests merged in 2025-01, with the labels that each got.

#5533 netstrm TLS driver: move TLS retry handling to main driver
  runtime/nsd_gtls.c
  runtime/nsd_ossl.c
  runtime/nsdsel_gtls.c
  runtime/nsdsel_ossl.c
Labels: enhancement

#5538 imtcp: add "socketBacklog" parameter to configure TCP backlog size
  plugins/imtcp/imtcp.c
  runtime/netstrms.c
  runtime/netstrms.h
  runtime/nsd_ptcp.c
  runtime/tcpsrv.c
  runtime/tcpsrv.h
  tests/Makefile.am
  tests/imtcp-tls-gtls-manycon.sh
  tests/imtcp-tls-ossl-manycon.sh
  tests/manytcp-too-few-tls-vg.sh
  tests/manytcp.sh
Labels: enhancement, testbench

#5536 tcpflood test tool: enable multi threaded connection open
  tests/tcpflood.c
Labels: enhancement, testbench

#5527 Replaced inet_aton with inet_pton for IPv4 address conversion.
  plugins/omsnmp/omsnmp.c
Labels: bug, enhancement

#5541 testbench: remove es 6.0 based tests
  tests/Makefile.am
  tests/es-basic-es6.0.sh
Labels: testbench, cleanup

#5540 omfwd: align some parameters with imtcp names
  tools/omfwd.c
Labels: enhancement

#5543 testbench: Fix OpenSSL 3.x depreceated warnings in tcpflood
  tests/tcpflood.c
Labels: bug

#5544 testbench: fix flaky omhttp-batch-retry-metadata.sh test
  tests/omhttp-batch-retry-metadata.sh
  tests/omhttp-validate-response.py
Labels: bug
