Repository rsyslog/rsyslog, pull requests merged in 2025-06, with the labels that each got.

#5601 Omsendertrack
  Makefile.am
  configure.ac
  plugins/omsendertrack/Makefile.am
  plugins/omsendertrack/omsendertrack.c
  runtime/rsyslog.h
  tests/Makefile.am
  tests/omsendertrack-basic-vg.sh
  tests/omsendertrack-basic.sh
  tests/tcpflood.c
Labels: enhancement

#5655 Fix comment for parsSkipWhitespace
  parse.c
Labels: cleanup

#5659 docs: restructure contributor docs for clarity and AI agent readiness
  AGENTS.md
  CONTRIBUTING.md
  README.md
Labels: enhancement, doc

#5668 Document optional module dependencies
  AGENTS.md
Labels: codex

#5656 fix mime type typo
  plugins/omazureeventhubs/omazureeventhubs.c
Labels: bug

#5446 Add header includes to support compilation on FreeBSD
  plugins/imdtls/imdtls.c
  plugins/omdtls/omdtls.c
Labels: bug

#5673 imdocker: harden module buffer management
  contrib/imdocker/imdocker.c
Labels: bug

#5667 lookup: add new table type for regex-matches
  runtime/lookup.c
  runtime/lookup.h
  runtime/typedefs.h
Labels: enhancement

#5056 outchannel: eleminate type cast for compatibility reasons
  outchannel.c
Labels: bug

#5674 Fix misleading active target log in omfwd
  plugins/omazureeventhubs/omazureeventhubs.c
  runtime/lookup.c
  runtime/lookup.h
  tests/tcpflood.c
  tools/omfwd.c
  tools/omusrmsg.c
Labels: bug, codex

#5675 CI: new python-based codestyle checker
  devtools/check-codestyle.sh
  devtools/rsyslog_stylecheck.py
  plugins/imdtls/imdtls.c
  plugins/imklog/bsd.c
  plugins/mmaudit/mmaudit.c
  plugins/mmpstrucdata/mmpstrucdata.c
  plugins/omdtls/omdtls.c
  plugins/omjournal/omjournal.c
  plugins/ommail/ommail.c
  plugins/ommysql/ommysql.c
Labels: testbench

#5680 fix hashtable realloc memset range
  runtime/hashtable.c
Labels: bug, codex

#5699 some cleanup
  action.c
  contrib/ffaup/ffaup.c
  contrib/imczmq/imczmq.c
  contrib/impcap/dns_parser.c
  contrib/impcap/impcap.c
  contrib/omamqp1/omamqp1.c
  contrib/omczmq/omczmq.c
  contrib/omrabbitmq/omrabbitmq.c
  grammar/lexer.l
  grammar/rainerscript.c
  plugins/imdtls/imdtls.c
  plugins/mmanon/mmanon.c
  plugins/omgssapi/omgssapi.c
  plugins/omtesting/omtesting.c
  runtime/cfsysline.c
  runtime/dnscache.c
  runtime/modules.c
  runtime/msg.c
  runtime/msg.h
  runtime/net.c
  runtime/nsd_gtls.c
  runtime/nsd_ossl.c
  runtime/queue.c
  runtime/rsyslog.h
  runtime/statsobj.c
  runtime/stream.c
  runtime/tcpsrv.c
  runtime/typedefs.h
  template.c
Labels: documentation

#5698 doc: improve description of config parameter block handling
  AGENTS.md
  grammar/rainerscript.h
Labels: documentation

#5705 cleanup: fix some TODOs and remove outdated ones
  runtime/cfsysline.c
  runtime/conf.c
  runtime/datetime.c
  runtime/glbl.c
  runtime/janitor.c
  runtime/lib_ksils12.c
  runtime/libcry_common.c
  runtime/libgcry.c
  runtime/libossl.c
  runtime/netstrm.h
  runtime/netstrms.c
  runtime/nsd.h
  runtime/nsd_ptcp.c
  runtime/obj.c
  runtime/rsconf.h
Labels: cleanup

#5709 Add Doxygen comments to omsendertrack
  plugins/omsendertrack/omsendertrack.c
Labels: codex

#5716 Add omsendertrack statefile tests
  tests/Makefile.am
  tests/omsendertrack-statefile-vg.sh
  tests/omsendertrack-statefile.sh
Labels: codex

#5714 CI: Optimize compile check for doc-only changes
  .github/workflows/ci_compile.yml
  .github/workflows/codeql.yml
  .github/workflows/run_checks.yml
  .github/workflows/run_journal.yml
  .github/workflows/run_kafka_distcheck.yml
Labels: testbench

#5720 omsendertrack fix: memory leak in initHashTable
  plugins/omsendertrack/omsendertrack.c
Labels: bug

#5724 tcpsrv: fail to remove already-removed epoll fd is no error
  runtime/tcpsrv.c
Labels: bug

#5726 tcpsrv cleanup: remove TODO line that was scheduled to be removed
  runtime/tcpsrv.c
Labels: cleanup

#5728 CI: (try to) fix running compile checks only on code file changes
  .github/workflows/ci_compile.yml
Labels: bug, testbench

#5717 doc: first omsendertrack reference manual entry
  doc/source/configuration/modules/omsendertrack.rst
Labels: documentation

#5729 cleanup: remove stalled TODO item
  action.c
Labels: cleanup

#5736 CI: auto-generate testbench tools and refine AI agent instructions
  AGENTS.md
  tests/diag.sh
Labels: testbench, AI

#5731 fix off-by-one buffer overflow
  tools/rsyslogd.c
Labels: bug
