Repository rsyslog/rsyslog, pull requests merged in 2025-09, with the labels that each got.

#5972 omhttp: add profile support and revise HTTP retry semantics @#5957
  contrib/omhttp/omhttp.c
  tests/Makefile.am
  tests/omhttp-profile-loki.sh
Labels: enhancement

#6055 tools/rsyslog.conf.5: fix example Port= value
  tools/rsyslog.conf.5
Labels: documentation

#6062 CI: change zookeeper version to latest stable
  tests/diag.sh
Labels: CI

#5974 tcpflood: fix octet-counted framing delimiter
  tests/tcpflood.c
Labels: bug, CI, codex

#6066 CI: reconfigure gemmini code review bot
  .gemini/config.yml
Labels: CI

#6067 CI: more verbose info on kafka/zookeeper install
  tests/diag.sh
Labels: CI

#6074 Codex/refactor rsyslog parameter documentation
  doc/source/configuration/modules/mmkubernetes.rst
  doc/source/reference/parameters/mmkubernetes-allowunsignedcerts.rst
  doc/source/reference/parameters/mmkubernetes-annotation-match.rst
  doc/source/reference/parameters/mmkubernetes-busyretryinterval.rst
  doc/source/reference/parameters/mmkubernetes-cacheentryttl.rst
  doc/source/reference/parameters/mmkubernetes-cacheexpireinterval.rst
  doc/source/reference/parameters/mmkubernetes-containerrulebase.rst
  doc/source/reference/parameters/mmkubernetes-containerrules.rst
  doc/source/reference/parameters/mmkubernetes-de-dot-separator.rst
  doc/source/reference/parameters/mmkubernetes-de-dot.rst
  doc/source/reference/parameters/mmkubernetes-dstmetadatapath.rst
  doc/source/reference/parameters/mmkubernetes-filenamerulebase.rst
  doc/source/reference/parameters/mmkubernetes-filenamerules.rst
  doc/source/reference/parameters/mmkubernetes-kubernetesurl.rst
  doc/source/reference/parameters/mmkubernetes-skipverifyhost.rst
  doc/source/reference/parameters/mmkubernetes-srcmetadatapath.rst
  doc/source/reference/parameters/mmkubernetes-sslpartialchain.rst
  doc/source/reference/parameters/mmkubernetes-tls-cacert.rst
  doc/source/reference/parameters/mmkubernetes-tls-mycert.rst
  doc/source/reference/parameters/mmkubernetes-tls-myprivkey.rst
  doc/source/reference/parameters/mmkubernetes-token.rst
  doc/source/reference/parameters/mmkubernetes-tokenfile.rst
Labels: documentation

#6073 code style: fix macro formatting
  grammar/lexer.l
  plugins/ommongodb/ommongodb.c
  tools/logctl.c
Labels: cleanup

#5406 WiP: Replace libgcrypt-config with pkg-config
  configure.ac
Labels: bug, enhancement

#6088 devtools: use codecov uploader in CI script
  .github/workflows/run_checks.yml
  devtools/devcontainer.sh
  devtools/run-ci.sh
Labels: bug, enhancement

#6097 rainerscript: add toupper() function
  doc/source/rainerscript/functions/rs-toupper.rst
  grammar/rainerscript.c
  tests/Makefile.am
  tests/rscript_tolower.sh
  tests/rscript_toupper.sh
Labels: enhancement

#6104 CI: remove invalid codecov call from non-codecov test
  .github/workflows/run_checks.yml
Labels: CI

#6106 Codex/refactor rsyslog module parameter documentation wfwkdp
  doc/source/configuration/modules/mmrfc5424addhmac.rst
  doc/source/reference/parameters/mmrfc5424addhmac-hashfunction.rst
  doc/source/reference/parameters/mmrfc5424addhmac-key.rst
  doc/source/reference/parameters/mmrfc5424addhmac-sd-id.rst
Labels: documentation

#6102 CI: nitfix in diag.sh (cosmetic)
  tests/diag.sh
Labels: CI, cleanup

#6107 doc: update reference section guidelines.rst
  doc/source/development/doc_reference_section_guidelines.rst
Labels: documentation

#6108 CI remove old kafka codecov builder now the new one is present
  .github/workflows/run_checks.yml
Labels: CI

#6080 config script: add b64_decode function
  grammar/rainerscript.c
  tests/Makefile.am
  tests/rscript_b64_decode-vg.sh
  tests/rscript_b64_decode.sh
Labels: enhancement

#6115 doc: improg had a strangely worded limitation listed - corrected
  doc/source/configuration/modules/improg.rst
Labels: bug, documentation

#6116 docker: update Debian 13 build to inlcude more modules
  packaging/docker/dev_env/debian/base/13/Dockerfile
Labels: docker

#6132 doc: describe regex lookup table type
  doc/source/configuration/lookup_tables.rst
Labels: documentation

#6130 core: add doxygen comments to errmsg object
  runtime/errmsg.c
  runtime/errmsg.h
Labels: cleanup, AI

#6131 Codex/refactor rsyslog parameter documentation m59zdg
  doc/source/configuration/modules/mmtaghostname.rst
  doc/source/reference/parameters/mmtaghostname-forcelocalhostname.rst
  doc/source/reference/parameters/mmtaghostname-tag.rst
Labels: documentation

#6138 docs/getting_started: add AI assistants page
  doc/source/getting_started/ai-assistants.rst
  doc/source/getting_started/index.rst
Labels: documentation, AI

#6139 Codex/refactor rsyslog parameter documentation wxjwx4
  doc/source/configuration/modules/mmutf8fix.rst
  doc/source/reference/parameters/mmutf8fix-mode.rst
  doc/source/reference/parameters/mmutf8fix-replacementchar.rst
Labels: documentation

#6137 dev container: do not work-around libgcrypt dev interface change
  packaging/docker/dev_env/debian/base/sid/Dockerfile
Labels: CI

#6142 omkafka: allow sending static headers
  .github/workflows/run_checks.yml
  .github/workflows/run_kafka_distcheck.yml
  configure.ac
  devtools/devcontainer.sh
  doc/source/configuration/modules/omkafka.rst
  doc/source/reference/parameters/omkafka-kafkaheader.rst
  plugins/omkafka/omkafka.c
  tests/Makefile.am
  tests/omkafka-headers.sh
Labels: enhancement

#6160 tests/omelasticsearch: align suite with ES 7.14, reduce flakiness
  .github/workflows/run_checks.yml
  tests/diskqueue-multithread-es.sh
  tests/es-basic-abort.sh
  tests/es-basic-bulk.sh
  tests/es-basic-errfile-empty.sh
  tests/es-basic-errfile-popul.sh
  tests/es-basic-es7.14.sh
  tests/es-basic-ha-vg.sh
  tests/es-basic-ha.sh
  tests/es-basic-server.sh
  tests/es-basic-vgthread.sh
  tests/es-basic.sh
  tests/es-bulk-errfile-empty.sh
  tests/es-bulk-errfile-popul-def-format.sh
  tests/es-bulk-errfile-popul-def-interleaved.sh
  tests/es-bulk-errfile-popul-erronly-interleaved.sh
  tests/es-bulk-errfile-popul-erronly.sh
  tests/es-bulk-errfile-popul.sh
  tests/es-bulk-retry.sh
  tests/es-duplicated-ruleset.sh
  tests/es-execOnlyWhenPreviousSuspended.sh
  tests/es-maxbytes-bulk.sh
  tests/es-searchType-empty.sh
  tests/es-writeoperation.sh
Labels: bug, CI

#6163 CI: fix invalid download name for zookeeper
  tests/diag.sh
  tests/kafka-selftest.sh
Labels: bug, CI

#6152 mmleefparse: new message modification module for LEEF format
  Makefile.am
  configure.ac
  doc/source/configuration/modules/mmleefparse.rst
  packaging/docker/dev_env/debian/base/sid/Dockerfile
  packaging/docker/dev_env/ubuntu/base/22.04/Dockerfile
  packaging/docker/dev_env/ubuntu/base/24.04/Dockerfile
  plugins/mmleefparse/Makefile.am
  plugins/mmleefparse/mmleefparse.c
  tests/Makefile.am
  tests/mmleefparse_basic.sh
Labels: enhancement

#6164 CI: optimize kafka test execution time a bit
  .github/workflows/run_kafka_distcheck.yml
Labels: CI, cleanup

#6167 Codex/document mmaudit plugin with sphinx
  doc/source/configuration/modules/mmaudit.rst
Labels: documentation

#6172 Codex/refactor module documentation for parameters
  doc/source/configuration/modules/mmfields.rst
  doc/source/reference/parameters/mmfields-jsonroot.rst
  doc/source/reference/parameters/mmfields-separator.rst
Labels: documentation

#6181 omelasticsearch: omit _type by default; use typeless endpoint
  plugins/omelasticsearch/omelasticsearch.c
  tests/Makefile.am
  tests/es-basic-abort.sh
  tests/es-basic-bulk.sh
  tests/es-basic-errfile-empty.sh
  tests/es-basic-errfile-popul.sh
  tests/es-basic-ha-vg.sh
  tests/es-basic-ha.sh
  tests/es-basic-server.sh
  tests/es-basic-vgthread.sh
  tests/es-basic.sh
  tests/es-bulk-errfile-empty.sh
  tests/es-bulk-errfile-popul-def-format.sh
  tests/es-bulk-errfile-popul-def-interleaved.sh
  tests/es-bulk-errfile-popul-erronly-interleaved.sh
  tests/es-bulk-errfile-popul-erronly.sh
  tests/es-bulk-errfile-popul.sh
  tests/es-bulk-retry.sh
  tests/es-duplicated-ruleset.sh
  tests/es-execOnlyWhenPreviousSuspended.sh
  tests/es-maxbytes-bulk.sh
  tests/es-searchType-empty.sh
  tests/es-writeoperation.sh
Labels: bug

#6180 doc: update imjournal journald warning
  doc/source/configuration/modules/imjournal.rst
Labels: bug, documentation

#6183 docs: add agent guides and module metadata scaffolding
  AGENTS.md
  ai/rsyslog_code_doc_builder/base_prompt.txt
  contrib/AGENTS.md
  contrib/MODULE_METADATA_TEMPLATE.yaml
  doc/AGENTS.md
  doc/ai/module_map.yaml
  plugins/AGENTS.md
  plugins/MODULE_AGENTS_TEMPLATE.md
  plugins/MODULE_METADATA_TEMPLATE.yaml
  plugins/imkafka/AGENTS.md
  plugins/imkafka/MODULE_METADATA.yaml
  plugins/omelasticsearch/AGENTS.md
  plugins/omelasticsearch/MODULE_METADATA.yaml
  plugins/omkafka/AGENTS.md
  plugins/omkafka/MODULE_METADATA.yaml
  plugins/omruleset/AGENTS.md
  plugins/omruleset/MODULE_METADATA.yaml
  tools/AGENTS.md
  tools/MODULE_METADATA.json
Labels: documentation, AI

#6182 Codex/refactor rsyslog parameters documentation
  doc/source/configuration/modules/mmanon.rst
  doc/source/reference/parameters/mmanon-embeddedipv4-anonmode.rst
  doc/source/reference/parameters/mmanon-embeddedipv4-bits.rst
  doc/source/reference/parameters/mmanon-embeddedipv4-enable.rst
  doc/source/reference/parameters/mmanon-ipv4-bits.rst
  doc/source/reference/parameters/mmanon-ipv4-enable.rst
  doc/source/reference/parameters/mmanon-ipv4-mode.rst
  doc/source/reference/parameters/mmanon-ipv4-replacechar.rst
  doc/source/reference/parameters/mmanon-ipv6-anonmode.rst
  doc/source/reference/parameters/mmanon-ipv6-bits.rst
  doc/source/reference/parameters/mmanon-ipv6-enable.rst
Labels: documentation

#6187 AI: add missing AGENTS.md files
  runtime/AGENTS.md
  tests/AGENTS.md
Labels: documentation

#6191 ci: add openEuler 24.03 LTS container and CI job
  .github/workflows/run_checks.yml
  packaging/docker/dev_env/README.md
  packaging/docker/dev_env/openeuler/base/24.03-lts/Dockerfile
  packaging/docker/dev_env/openeuler/base/24.03-lts/build.sh
  packaging/docker/dev_env/openeuler/base/24.03-lts/tag-previous.sh
Labels: CI

#6199 AI: align AGENTS.md and README; expand harness tips
  tests/AGENTS.md
  tests/README
Labels: AI

#6204 CI containers: include mbedtls test environment
  packaging/docker/dev_env/debian/base/13/Dockerfile
  packaging/docker/dev_env/fedora/base/42/Dockerfile
  packaging/docker/dev_env/ubuntu/base/22.04/Dockerfile
  packaging/docker/dev_env/ubuntu/base/24.04/Dockerfile
Labels: CI
